// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fundInfoMoneys.proto

package com.howbuy.wireless.entity.protobuf;

public final class FundInfoMoneysProto {
  private FundInfoMoneysProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class FundInfoMoneys extends
      com.google.protobuf.GeneratedMessage {
    // Use FundInfoMoneys.newBuilder() to construct.
    private FundInfoMoneys() {
      initFields();
    }
    private FundInfoMoneys(boolean noInit) {}
    
    private static final FundInfoMoneys defaultInstance;
    public static FundInfoMoneys getDefaultInstance() {
      return defaultInstance;
    }
    
    public FundInfoMoneys getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.howbuy.wireless.entity.protobuf.FundInfoMoneysProto.internal_static_FundInfoMoneys_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.howbuy.wireless.entity.protobuf.FundInfoMoneysProto.internal_static_FundInfoMoneys_fieldAccessorTable;
    }
    
    // optional .common.Common common = 1;
    public static final int COMMON_FIELD_NUMBER = 1;
    private boolean hasCommon;
    private com.howbuy.wireless.entity.protobuf.CommonProtos.Common common_;
    public boolean hasCommon() { return hasCommon; }
    public com.howbuy.wireless.entity.protobuf.CommonProtos.Common getCommon() { return common_; }
    
    // required fixed64 serverTime = 2;
    public static final int SERVERTIME_FIELD_NUMBER = 2;
    private boolean hasServerTime;
    private long serverTime_ = 0L;
    public boolean hasServerTime() { return hasServerTime; }
    public long getServerTime() { return serverTime_; }
    
    // repeated .Moneys moneys = 3;
    public static final int MONEYS_FIELD_NUMBER = 3;
    private java.util.List<com.howbuy.wireless.entity.protobuf.MoneysProtos.Moneys> moneys_ =
      java.util.Collections.emptyList();
    public java.util.List<com.howbuy.wireless.entity.protobuf.MoneysProtos.Moneys> getMoneysList() {
      return moneys_;
    }
    public int getMoneysCount() { return moneys_.size(); }
    public com.howbuy.wireless.entity.protobuf.MoneysProtos.Moneys getMoneys(int index) {
      return moneys_.get(index);
    }
    
    // optional fixed64 dateVersion = 4;
    public static final int DATEVERSION_FIELD_NUMBER = 4;
    private boolean hasDateVersion;
    private long dateVersion_ = 0L;
    public boolean hasDateVersion() { return hasDateVersion; }
    public long getDateVersion() { return dateVersion_; }
    
    private void initFields() {
      common_ = com.howbuy.wireless.entity.protobuf.CommonProtos.Common.getDefaultInstance();
    }
    public final boolean isInitialized() {
      if (!hasServerTime) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasCommon()) {
        output.writeMessage(1, getCommon());
      }
      if (hasServerTime()) {
        output.writeFixed64(2, getServerTime());
      }
      for (com.howbuy.wireless.entity.protobuf.MoneysProtos.Moneys element : getMoneysList()) {
        output.writeMessage(3, element);
      }
      if (hasDateVersion()) {
        output.writeFixed64(4, getDateVersion());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasCommon()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getCommon());
      }
      if (hasServerTime()) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed64Size(2, getServerTime());
      }
      for (com.howbuy.wireless.entity.protobuf.MoneysProtos.Moneys element : getMoneysList()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, element);
      }
      if (hasDateVersion()) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed64Size(4, getDateVersion());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.howbuy.wireless.entity.protobuf.FundInfoMoneysProto.FundInfoMoneys parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.howbuy.wireless.entity.protobuf.FundInfoMoneysProto.FundInfoMoneys parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.howbuy.wireless.entity.protobuf.FundInfoMoneysProto.FundInfoMoneys parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.howbuy.wireless.entity.protobuf.FundInfoMoneysProto.FundInfoMoneys parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.howbuy.wireless.entity.protobuf.FundInfoMoneysProto.FundInfoMoneys parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.howbuy.wireless.entity.protobuf.FundInfoMoneysProto.FundInfoMoneys parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.howbuy.wireless.entity.protobuf.FundInfoMoneysProto.FundInfoMoneys parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.howbuy.wireless.entity.protobuf.FundInfoMoneysProto.FundInfoMoneys parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.howbuy.wireless.entity.protobuf.FundInfoMoneysProto.FundInfoMoneys parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.howbuy.wireless.entity.protobuf.FundInfoMoneysProto.FundInfoMoneys parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.howbuy.wireless.entity.protobuf.FundInfoMoneysProto.FundInfoMoneys prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.howbuy.wireless.entity.protobuf.FundInfoMoneysProto.FundInfoMoneys result;
      
      // Construct using com.howbuy.wireless.entity.protobuf.FundInfoMoneysProto.FundInfoMoneys.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.howbuy.wireless.entity.protobuf.FundInfoMoneysProto.FundInfoMoneys();
        return builder;
      }
      
      protected com.howbuy.wireless.entity.protobuf.FundInfoMoneysProto.FundInfoMoneys internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.howbuy.wireless.entity.protobuf.FundInfoMoneysProto.FundInfoMoneys();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.howbuy.wireless.entity.protobuf.FundInfoMoneysProto.FundInfoMoneys.getDescriptor();
      }
      
      public com.howbuy.wireless.entity.protobuf.FundInfoMoneysProto.FundInfoMoneys getDefaultInstanceForType() {
        return com.howbuy.wireless.entity.protobuf.FundInfoMoneysProto.FundInfoMoneys.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.howbuy.wireless.entity.protobuf.FundInfoMoneysProto.FundInfoMoneys build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.howbuy.wireless.entity.protobuf.FundInfoMoneysProto.FundInfoMoneys buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.howbuy.wireless.entity.protobuf.FundInfoMoneysProto.FundInfoMoneys buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        if (result.moneys_ != java.util.Collections.EMPTY_LIST) {
          result.moneys_ =
            java.util.Collections.unmodifiableList(result.moneys_);
        }
        com.howbuy.wireless.entity.protobuf.FundInfoMoneysProto.FundInfoMoneys returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.howbuy.wireless.entity.protobuf.FundInfoMoneysProto.FundInfoMoneys) {
          return mergeFrom((com.howbuy.wireless.entity.protobuf.FundInfoMoneysProto.FundInfoMoneys)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.howbuy.wireless.entity.protobuf.FundInfoMoneysProto.FundInfoMoneys other) {
        if (other == com.howbuy.wireless.entity.protobuf.FundInfoMoneysProto.FundInfoMoneys.getDefaultInstance()) return this;
        if (other.hasCommon()) {
          mergeCommon(other.getCommon());
        }
        if (other.hasServerTime()) {
          setServerTime(other.getServerTime());
        }
        if (!other.moneys_.isEmpty()) {
          if (result.moneys_.isEmpty()) {
            result.moneys_ = new java.util.ArrayList<com.howbuy.wireless.entity.protobuf.MoneysProtos.Moneys>();
          }
          result.moneys_.addAll(other.moneys_);
        }
        if (other.hasDateVersion()) {
          setDateVersion(other.getDateVersion());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              com.howbuy.wireless.entity.protobuf.CommonProtos.Common.Builder subBuilder = com.howbuy.wireless.entity.protobuf.CommonProtos.Common.newBuilder();
              if (hasCommon()) {
                subBuilder.mergeFrom(getCommon());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setCommon(subBuilder.buildPartial());
              break;
            }
            case 17: {
              setServerTime(input.readFixed64());
              break;
            }
            case 26: {
              com.howbuy.wireless.entity.protobuf.MoneysProtos.Moneys.Builder subBuilder = com.howbuy.wireless.entity.protobuf.MoneysProtos.Moneys.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addMoneys(subBuilder.buildPartial());
              break;
            }
            case 33: {
              setDateVersion(input.readFixed64());
              break;
            }
          }
        }
      }
      
      
      // optional .common.Common common = 1;
      public boolean hasCommon() {
        return result.hasCommon();
      }
      public com.howbuy.wireless.entity.protobuf.CommonProtos.Common getCommon() {
        return result.getCommon();
      }
      public Builder setCommon(com.howbuy.wireless.entity.protobuf.CommonProtos.Common value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasCommon = true;
        result.common_ = value;
        return this;
      }
      public Builder setCommon(com.howbuy.wireless.entity.protobuf.CommonProtos.Common.Builder builderForValue) {
        result.hasCommon = true;
        result.common_ = builderForValue.build();
        return this;
      }
      public Builder mergeCommon(com.howbuy.wireless.entity.protobuf.CommonProtos.Common value) {
        if (result.hasCommon() &&
            result.common_ != com.howbuy.wireless.entity.protobuf.CommonProtos.Common.getDefaultInstance()) {
          result.common_ =
            com.howbuy.wireless.entity.protobuf.CommonProtos.Common.newBuilder(result.common_).mergeFrom(value).buildPartial();
        } else {
          result.common_ = value;
        }
        result.hasCommon = true;
        return this;
      }
      public Builder clearCommon() {
        result.hasCommon = false;
        result.common_ = com.howbuy.wireless.entity.protobuf.CommonProtos.Common.getDefaultInstance();
        return this;
      }
      
      // required fixed64 serverTime = 2;
      public boolean hasServerTime() {
        return result.hasServerTime();
      }
      public long getServerTime() {
        return result.getServerTime();
      }
      public Builder setServerTime(long value) {
        result.hasServerTime = true;
        result.serverTime_ = value;
        return this;
      }
      public Builder clearServerTime() {
        result.hasServerTime = false;
        result.serverTime_ = 0L;
        return this;
      }
      
      // repeated .Moneys moneys = 3;
      public java.util.List<com.howbuy.wireless.entity.protobuf.MoneysProtos.Moneys> getMoneysList() {
        return java.util.Collections.unmodifiableList(result.moneys_);
      }
      public int getMoneysCount() {
        return result.getMoneysCount();
      }
      public com.howbuy.wireless.entity.protobuf.MoneysProtos.Moneys getMoneys(int index) {
        return result.getMoneys(index);
      }
      public Builder setMoneys(int index, com.howbuy.wireless.entity.protobuf.MoneysProtos.Moneys value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.moneys_.set(index, value);
        return this;
      }
      public Builder setMoneys(int index, com.howbuy.wireless.entity.protobuf.MoneysProtos.Moneys.Builder builderForValue) {
        result.moneys_.set(index, builderForValue.build());
        return this;
      }
      public Builder addMoneys(com.howbuy.wireless.entity.protobuf.MoneysProtos.Moneys value) {
        if (value == null) {
          throw new NullPointerException();
        }
        if (result.moneys_.isEmpty()) {
          result.moneys_ = new java.util.ArrayList<com.howbuy.wireless.entity.protobuf.MoneysProtos.Moneys>();
        }
        result.moneys_.add(value);
        return this;
      }
      public Builder addMoneys(com.howbuy.wireless.entity.protobuf.MoneysProtos.Moneys.Builder builderForValue) {
        if (result.moneys_.isEmpty()) {
          result.moneys_ = new java.util.ArrayList<com.howbuy.wireless.entity.protobuf.MoneysProtos.Moneys>();
        }
        result.moneys_.add(builderForValue.build());
        return this;
      }
      public Builder addAllMoneys(
          java.lang.Iterable<? extends com.howbuy.wireless.entity.protobuf.MoneysProtos.Moneys> values) {
        if (result.moneys_.isEmpty()) {
          result.moneys_ = new java.util.ArrayList<com.howbuy.wireless.entity.protobuf.MoneysProtos.Moneys>();
        }
        super.addAll(values, result.moneys_);
        return this;
      }
      public Builder clearMoneys() {
        result.moneys_ = java.util.Collections.emptyList();
        return this;
      }
      
      // optional fixed64 dateVersion = 4;
      public boolean hasDateVersion() {
        return result.hasDateVersion();
      }
      public long getDateVersion() {
        return result.getDateVersion();
      }
      public Builder setDateVersion(long value) {
        result.hasDateVersion = true;
        result.dateVersion_ = value;
        return this;
      }
      public Builder clearDateVersion() {
        result.hasDateVersion = false;
        result.dateVersion_ = 0L;
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:FundInfoMoneys)
    }
    
    static {
      defaultInstance = new FundInfoMoneys(true);
      com.howbuy.wireless.entity.protobuf.FundInfoMoneysProto.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:FundInfoMoneys)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_FundInfoMoneys_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_FundInfoMoneys_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024fundInfoMoneys.proto\032\014moneys.proto\032\014co" +
      "mmon.proto\"r\n\016FundInfoMoneys\022\036\n\006common\030\001" +
      " \001(\0132\016.common.Common\022\022\n\nserverTime\030\002 \002(\006" +
      "\022\027\n\006moneys\030\003 \003(\0132\007.Moneys\022\023\n\013dateVersion" +
      "\030\004 \001(\006B:\n#com.howbuy.wireless.entity.pro" +
      "tobufB\023FundInfoMoneysProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_FundInfoMoneys_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_FundInfoMoneys_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_FundInfoMoneys_descriptor,
              new java.lang.String[] { "Common", "ServerTime", "Moneys", "DateVersion", },
              com.howbuy.wireless.entity.protobuf.FundInfoMoneysProto.FundInfoMoneys.class,
              com.howbuy.wireless.entity.protobuf.FundInfoMoneysProto.FundInfoMoneys.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.howbuy.wireless.entity.protobuf.MoneysProtos.getDescriptor(),
          com.howbuy.wireless.entity.protobuf.CommonProtos.getDescriptor(),
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
