// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fundInfoSimusOfPage.proto

package com.howbuy.wireless.entity.protobuf;

public final class FundInfoSimusOfPageProto {
  private FundInfoSimusOfPageProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class FundInfoSimusOfPage extends
      com.google.protobuf.GeneratedMessage {
    // Use FundInfoSimusOfPage.newBuilder() to construct.
    private FundInfoSimusOfPage() {
      initFields();
    }
    private FundInfoSimusOfPage(boolean noInit) {}
    
    private static final FundInfoSimusOfPage defaultInstance;
    public static FundInfoSimusOfPage getDefaultInstance() {
      return defaultInstance;
    }
    
    public FundInfoSimusOfPage getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.howbuy.wireless.entity.protobuf.FundInfoSimusOfPageProto.internal_static_FundInfoSimusOfPage_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.howbuy.wireless.entity.protobuf.FundInfoSimusOfPageProto.internal_static_FundInfoSimusOfPage_fieldAccessorTable;
    }
    
    // optional .common.Common common = 1;
    public static final int COMMON_FIELD_NUMBER = 1;
    private boolean hasCommon;
    private com.howbuy.wireless.entity.protobuf.CommonProtos.Common common_;
    public boolean hasCommon() { return hasCommon; }
    public com.howbuy.wireless.entity.protobuf.CommonProtos.Common getCommon() { return common_; }
    
    // repeated .SimusOfPage simusOfPage = 2;
    public static final int SIMUSOFPAGE_FIELD_NUMBER = 2;
    private java.util.List<com.howbuy.wireless.entity.protobuf.SimusOfPageProtos.SimusOfPage> simusOfPage_ =
      java.util.Collections.emptyList();
    public java.util.List<com.howbuy.wireless.entity.protobuf.SimusOfPageProtos.SimusOfPage> getSimusOfPageList() {
      return simusOfPage_;
    }
    public int getSimusOfPageCount() { return simusOfPage_.size(); }
    public com.howbuy.wireless.entity.protobuf.SimusOfPageProtos.SimusOfPage getSimusOfPage(int index) {
      return simusOfPage_.get(index);
    }
    
    // optional int32 sumPage = 3;
    public static final int SUMPAGE_FIELD_NUMBER = 3;
    private boolean hasSumPage;
    private int sumPage_ = 0;
    public boolean hasSumPage() { return hasSumPage; }
    public int getSumPage() { return sumPage_; }
    
    private void initFields() {
      common_ = com.howbuy.wireless.entity.protobuf.CommonProtos.Common.getDefaultInstance();
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasCommon()) {
        output.writeMessage(1, getCommon());
      }
      for (com.howbuy.wireless.entity.protobuf.SimusOfPageProtos.SimusOfPage element : getSimusOfPageList()) {
        output.writeMessage(2, element);
      }
      if (hasSumPage()) {
        output.writeInt32(3, getSumPage());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasCommon()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getCommon());
      }
      for (com.howbuy.wireless.entity.protobuf.SimusOfPageProtos.SimusOfPage element : getSimusOfPageList()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, element);
      }
      if (hasSumPage()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, getSumPage());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.howbuy.wireless.entity.protobuf.FundInfoSimusOfPageProto.FundInfoSimusOfPage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.howbuy.wireless.entity.protobuf.FundInfoSimusOfPageProto.FundInfoSimusOfPage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.howbuy.wireless.entity.protobuf.FundInfoSimusOfPageProto.FundInfoSimusOfPage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.howbuy.wireless.entity.protobuf.FundInfoSimusOfPageProto.FundInfoSimusOfPage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.howbuy.wireless.entity.protobuf.FundInfoSimusOfPageProto.FundInfoSimusOfPage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.howbuy.wireless.entity.protobuf.FundInfoSimusOfPageProto.FundInfoSimusOfPage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.howbuy.wireless.entity.protobuf.FundInfoSimusOfPageProto.FundInfoSimusOfPage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.howbuy.wireless.entity.protobuf.FundInfoSimusOfPageProto.FundInfoSimusOfPage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.howbuy.wireless.entity.protobuf.FundInfoSimusOfPageProto.FundInfoSimusOfPage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.howbuy.wireless.entity.protobuf.FundInfoSimusOfPageProto.FundInfoSimusOfPage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.howbuy.wireless.entity.protobuf.FundInfoSimusOfPageProto.FundInfoSimusOfPage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.howbuy.wireless.entity.protobuf.FundInfoSimusOfPageProto.FundInfoSimusOfPage result;
      
      // Construct using com.howbuy.wireless.entity.protobuf.FundInfoSimusOfPageProto.FundInfoSimusOfPage.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.howbuy.wireless.entity.protobuf.FundInfoSimusOfPageProto.FundInfoSimusOfPage();
        return builder;
      }
      
      protected com.howbuy.wireless.entity.protobuf.FundInfoSimusOfPageProto.FundInfoSimusOfPage internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.howbuy.wireless.entity.protobuf.FundInfoSimusOfPageProto.FundInfoSimusOfPage();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.howbuy.wireless.entity.protobuf.FundInfoSimusOfPageProto.FundInfoSimusOfPage.getDescriptor();
      }
      
      public com.howbuy.wireless.entity.protobuf.FundInfoSimusOfPageProto.FundInfoSimusOfPage getDefaultInstanceForType() {
        return com.howbuy.wireless.entity.protobuf.FundInfoSimusOfPageProto.FundInfoSimusOfPage.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.howbuy.wireless.entity.protobuf.FundInfoSimusOfPageProto.FundInfoSimusOfPage build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.howbuy.wireless.entity.protobuf.FundInfoSimusOfPageProto.FundInfoSimusOfPage buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.howbuy.wireless.entity.protobuf.FundInfoSimusOfPageProto.FundInfoSimusOfPage buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        if (result.simusOfPage_ != java.util.Collections.EMPTY_LIST) {
          result.simusOfPage_ =
            java.util.Collections.unmodifiableList(result.simusOfPage_);
        }
        com.howbuy.wireless.entity.protobuf.FundInfoSimusOfPageProto.FundInfoSimusOfPage returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.howbuy.wireless.entity.protobuf.FundInfoSimusOfPageProto.FundInfoSimusOfPage) {
          return mergeFrom((com.howbuy.wireless.entity.protobuf.FundInfoSimusOfPageProto.FundInfoSimusOfPage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.howbuy.wireless.entity.protobuf.FundInfoSimusOfPageProto.FundInfoSimusOfPage other) {
        if (other == com.howbuy.wireless.entity.protobuf.FundInfoSimusOfPageProto.FundInfoSimusOfPage.getDefaultInstance()) return this;
        if (other.hasCommon()) {
          mergeCommon(other.getCommon());
        }
        if (!other.simusOfPage_.isEmpty()) {
          if (result.simusOfPage_.isEmpty()) {
            result.simusOfPage_ = new java.util.ArrayList<com.howbuy.wireless.entity.protobuf.SimusOfPageProtos.SimusOfPage>();
          }
          result.simusOfPage_.addAll(other.simusOfPage_);
        }
        if (other.hasSumPage()) {
          setSumPage(other.getSumPage());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              com.howbuy.wireless.entity.protobuf.CommonProtos.Common.Builder subBuilder = com.howbuy.wireless.entity.protobuf.CommonProtos.Common.newBuilder();
              if (hasCommon()) {
                subBuilder.mergeFrom(getCommon());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setCommon(subBuilder.buildPartial());
              break;
            }
            case 18: {
              com.howbuy.wireless.entity.protobuf.SimusOfPageProtos.SimusOfPage.Builder subBuilder = com.howbuy.wireless.entity.protobuf.SimusOfPageProtos.SimusOfPage.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addSimusOfPage(subBuilder.buildPartial());
              break;
            }
            case 24: {
              setSumPage(input.readInt32());
              break;
            }
          }
        }
      }
      
      
      // optional .common.Common common = 1;
      public boolean hasCommon() {
        return result.hasCommon();
      }
      public com.howbuy.wireless.entity.protobuf.CommonProtos.Common getCommon() {
        return result.getCommon();
      }
      public Builder setCommon(com.howbuy.wireless.entity.protobuf.CommonProtos.Common value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasCommon = true;
        result.common_ = value;
        return this;
      }
      public Builder setCommon(com.howbuy.wireless.entity.protobuf.CommonProtos.Common.Builder builderForValue) {
        result.hasCommon = true;
        result.common_ = builderForValue.build();
        return this;
      }
      public Builder mergeCommon(com.howbuy.wireless.entity.protobuf.CommonProtos.Common value) {
        if (result.hasCommon() &&
            result.common_ != com.howbuy.wireless.entity.protobuf.CommonProtos.Common.getDefaultInstance()) {
          result.common_ =
            com.howbuy.wireless.entity.protobuf.CommonProtos.Common.newBuilder(result.common_).mergeFrom(value).buildPartial();
        } else {
          result.common_ = value;
        }
        result.hasCommon = true;
        return this;
      }
      public Builder clearCommon() {
        result.hasCommon = false;
        result.common_ = com.howbuy.wireless.entity.protobuf.CommonProtos.Common.getDefaultInstance();
        return this;
      }
      
      // repeated .SimusOfPage simusOfPage = 2;
      public java.util.List<com.howbuy.wireless.entity.protobuf.SimusOfPageProtos.SimusOfPage> getSimusOfPageList() {
        return java.util.Collections.unmodifiableList(result.simusOfPage_);
      }
      public int getSimusOfPageCount() {
        return result.getSimusOfPageCount();
      }
      public com.howbuy.wireless.entity.protobuf.SimusOfPageProtos.SimusOfPage getSimusOfPage(int index) {
        return result.getSimusOfPage(index);
      }
      public Builder setSimusOfPage(int index, com.howbuy.wireless.entity.protobuf.SimusOfPageProtos.SimusOfPage value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.simusOfPage_.set(index, value);
        return this;
      }
      public Builder setSimusOfPage(int index, com.howbuy.wireless.entity.protobuf.SimusOfPageProtos.SimusOfPage.Builder builderForValue) {
        result.simusOfPage_.set(index, builderForValue.build());
        return this;
      }
      public Builder addSimusOfPage(com.howbuy.wireless.entity.protobuf.SimusOfPageProtos.SimusOfPage value) {
        if (value == null) {
          throw new NullPointerException();
        }
        if (result.simusOfPage_.isEmpty()) {
          result.simusOfPage_ = new java.util.ArrayList<com.howbuy.wireless.entity.protobuf.SimusOfPageProtos.SimusOfPage>();
        }
        result.simusOfPage_.add(value);
        return this;
      }
      public Builder addSimusOfPage(com.howbuy.wireless.entity.protobuf.SimusOfPageProtos.SimusOfPage.Builder builderForValue) {
        if (result.simusOfPage_.isEmpty()) {
          result.simusOfPage_ = new java.util.ArrayList<com.howbuy.wireless.entity.protobuf.SimusOfPageProtos.SimusOfPage>();
        }
        result.simusOfPage_.add(builderForValue.build());
        return this;
      }
      public Builder addAllSimusOfPage(
          java.lang.Iterable<? extends com.howbuy.wireless.entity.protobuf.SimusOfPageProtos.SimusOfPage> values) {
        if (result.simusOfPage_.isEmpty()) {
          result.simusOfPage_ = new java.util.ArrayList<com.howbuy.wireless.entity.protobuf.SimusOfPageProtos.SimusOfPage>();
        }
        super.addAll(values, result.simusOfPage_);
        return this;
      }
      public Builder clearSimusOfPage() {
        result.simusOfPage_ = java.util.Collections.emptyList();
        return this;
      }
      
      // optional int32 sumPage = 3;
      public boolean hasSumPage() {
        return result.hasSumPage();
      }
      public int getSumPage() {
        return result.getSumPage();
      }
      public Builder setSumPage(int value) {
        result.hasSumPage = true;
        result.sumPage_ = value;
        return this;
      }
      public Builder clearSumPage() {
        result.hasSumPage = false;
        result.sumPage_ = 0;
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:FundInfoSimusOfPage)
    }
    
    static {
      defaultInstance = new FundInfoSimusOfPage(true);
      com.howbuy.wireless.entity.protobuf.FundInfoSimusOfPageProto.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:FundInfoSimusOfPage)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_FundInfoSimusOfPage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_FundInfoSimusOfPage_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031fundInfoSimusOfPage.proto\032\021simusOfPage" +
      ".proto\032\014common.proto\"i\n\023FundInfoSimusOfP" +
      "age\022\036\n\006common\030\001 \001(\0132\016.common.Common\022!\n\013s" +
      "imusOfPage\030\002 \003(\0132\014.SimusOfPage\022\017\n\007sumPag" +
      "e\030\003 \001(\005B?\n#com.howbuy.wireless.entity.pr" +
      "otobufB\030FundInfoSimusOfPageProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_FundInfoSimusOfPage_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_FundInfoSimusOfPage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_FundInfoSimusOfPage_descriptor,
              new java.lang.String[] { "Common", "SimusOfPage", "SumPage", },
              com.howbuy.wireless.entity.protobuf.FundInfoSimusOfPageProto.FundInfoSimusOfPage.class,
              com.howbuy.wireless.entity.protobuf.FundInfoSimusOfPageProto.FundInfoSimusOfPage.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.howbuy.wireless.entity.protobuf.SimusOfPageProtos.getDescriptor(),
          com.howbuy.wireless.entity.protobuf.CommonProtos.getDescriptor(),
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
