// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Fundfixed.proto

package com.howbuy.wireless.entity.protobuf;

public final class FundfixedProtos {
  private FundfixedProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class Fundfixed extends
      com.google.protobuf.GeneratedMessage {
    // Use Fundfixed.newBuilder() to construct.
    private Fundfixed() {
      initFields();
    }
    private Fundfixed(boolean noInit) {}
    
    private static final Fundfixed defaultInstance;
    public static Fundfixed getDefaultInstance() {
      return defaultInstance;
    }
    
    public Fundfixed getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.howbuy.wireless.entity.protobuf.FundfixedProtos.internal_static_Fundfixed_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.howbuy.wireless.entity.protobuf.FundfixedProtos.internal_static_Fundfixed_fieldAccessorTable;
    }
    
    // optional string code = 1;
    public static final int CODE_FIELD_NUMBER = 1;
    private boolean hasCode;
    private java.lang.String code_ = "";
    public boolean hasCode() { return hasCode; }
    public java.lang.String getCode() { return code_; }
    
    // optional string dthb1n = 2;
    public static final int DTHB1N_FIELD_NUMBER = 2;
    private boolean hasDthb1N;
    private java.lang.String dthb1N_ = "";
    public boolean hasDthb1N() { return hasDthb1N; }
    public java.lang.String getDthb1N() { return dthb1N_; }
    
    // optional string dthb2n = 3;
    public static final int DTHB2N_FIELD_NUMBER = 3;
    private boolean hasDthb2N;
    private java.lang.String dthb2N_ = "";
    public boolean hasDthb2N() { return hasDthb2N; }
    public java.lang.String getDthb2N() { return dthb2N_; }
    
    // optional string dthb3n = 4;
    public static final int DTHB3N_FIELD_NUMBER = 4;
    private boolean hasDthb3N;
    private java.lang.String dthb3N_ = "";
    public boolean hasDthb3N() { return hasDthb3N; }
    public java.lang.String getDthb3N() { return dthb3N_; }
    
    // optional string dthb4n = 5;
    public static final int DTHB4N_FIELD_NUMBER = 5;
    private boolean hasDthb4N;
    private java.lang.String dthb4N_ = "";
    public boolean hasDthb4N() { return hasDthb4N; }
    public java.lang.String getDthb4N() { return dthb4N_; }
    
    // optional string dthb5n = 6;
    public static final int DTHB5N_FIELD_NUMBER = 6;
    private boolean hasDthb5N;
    private java.lang.String dthb5N_ = "";
    public boolean hasDthb5N() { return hasDthb5N; }
    public java.lang.String getDthb5N() { return dthb5N_; }
    
    // optional string jjjz = 7;
    public static final int JJJZ_FIELD_NUMBER = 7;
    private boolean hasJjjz;
    private java.lang.String jjjz_ = "";
    public boolean hasJjjz() { return hasJjjz; }
    public java.lang.String getJjjz() { return jjjz_; }
    
    // optional string ljjz = 8;
    public static final int LJJZ_FIELD_NUMBER = 8;
    private boolean hasLjjz;
    private java.lang.String ljjz_ = "";
    public boolean hasLjjz() { return hasLjjz; }
    public java.lang.String getLjjz() { return ljjz_; }
    
    // optional string jzrq = 9;
    public static final int JZRQ_FIELD_NUMBER = 9;
    private boolean hasJzrq;
    private java.lang.String jzrq_ = "";
    public boolean hasJzrq() { return hasJzrq; }
    public java.lang.String getJzrq() { return jzrq_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasCode()) {
        output.writeString(1, getCode());
      }
      if (hasDthb1N()) {
        output.writeString(2, getDthb1N());
      }
      if (hasDthb2N()) {
        output.writeString(3, getDthb2N());
      }
      if (hasDthb3N()) {
        output.writeString(4, getDthb3N());
      }
      if (hasDthb4N()) {
        output.writeString(5, getDthb4N());
      }
      if (hasDthb5N()) {
        output.writeString(6, getDthb5N());
      }
      if (hasJjjz()) {
        output.writeString(7, getJjjz());
      }
      if (hasLjjz()) {
        output.writeString(8, getLjjz());
      }
      if (hasJzrq()) {
        output.writeString(9, getJzrq());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasCode()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getCode());
      }
      if (hasDthb1N()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getDthb1N());
      }
      if (hasDthb2N()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(3, getDthb2N());
      }
      if (hasDthb3N()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(4, getDthb3N());
      }
      if (hasDthb4N()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(5, getDthb4N());
      }
      if (hasDthb5N()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(6, getDthb5N());
      }
      if (hasJjjz()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(7, getJjjz());
      }
      if (hasLjjz()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(8, getLjjz());
      }
      if (hasJzrq()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(9, getJzrq());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.howbuy.wireless.entity.protobuf.FundfixedProtos.Fundfixed parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.howbuy.wireless.entity.protobuf.FundfixedProtos.Fundfixed parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.howbuy.wireless.entity.protobuf.FundfixedProtos.Fundfixed parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.howbuy.wireless.entity.protobuf.FundfixedProtos.Fundfixed parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.howbuy.wireless.entity.protobuf.FundfixedProtos.Fundfixed parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.howbuy.wireless.entity.protobuf.FundfixedProtos.Fundfixed parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.howbuy.wireless.entity.protobuf.FundfixedProtos.Fundfixed parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.howbuy.wireless.entity.protobuf.FundfixedProtos.Fundfixed parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.howbuy.wireless.entity.protobuf.FundfixedProtos.Fundfixed parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.howbuy.wireless.entity.protobuf.FundfixedProtos.Fundfixed parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.howbuy.wireless.entity.protobuf.FundfixedProtos.Fundfixed prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.howbuy.wireless.entity.protobuf.FundfixedProtos.Fundfixed result;
      
      // Construct using com.howbuy.wireless.entity.protobuf.FundfixedProtos.Fundfixed.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.howbuy.wireless.entity.protobuf.FundfixedProtos.Fundfixed();
        return builder;
      }
      
      protected com.howbuy.wireless.entity.protobuf.FundfixedProtos.Fundfixed internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.howbuy.wireless.entity.protobuf.FundfixedProtos.Fundfixed();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.howbuy.wireless.entity.protobuf.FundfixedProtos.Fundfixed.getDescriptor();
      }
      
      public com.howbuy.wireless.entity.protobuf.FundfixedProtos.Fundfixed getDefaultInstanceForType() {
        return com.howbuy.wireless.entity.protobuf.FundfixedProtos.Fundfixed.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.howbuy.wireless.entity.protobuf.FundfixedProtos.Fundfixed build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.howbuy.wireless.entity.protobuf.FundfixedProtos.Fundfixed buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.howbuy.wireless.entity.protobuf.FundfixedProtos.Fundfixed buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.howbuy.wireless.entity.protobuf.FundfixedProtos.Fundfixed returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.howbuy.wireless.entity.protobuf.FundfixedProtos.Fundfixed) {
          return mergeFrom((com.howbuy.wireless.entity.protobuf.FundfixedProtos.Fundfixed)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.howbuy.wireless.entity.protobuf.FundfixedProtos.Fundfixed other) {
        if (other == com.howbuy.wireless.entity.protobuf.FundfixedProtos.Fundfixed.getDefaultInstance()) return this;
        if (other.hasCode()) {
          setCode(other.getCode());
        }
        if (other.hasDthb1N()) {
          setDthb1N(other.getDthb1N());
        }
        if (other.hasDthb2N()) {
          setDthb2N(other.getDthb2N());
        }
        if (other.hasDthb3N()) {
          setDthb3N(other.getDthb3N());
        }
        if (other.hasDthb4N()) {
          setDthb4N(other.getDthb4N());
        }
        if (other.hasDthb5N()) {
          setDthb5N(other.getDthb5N());
        }
        if (other.hasJjjz()) {
          setJjjz(other.getJjjz());
        }
        if (other.hasLjjz()) {
          setLjjz(other.getLjjz());
        }
        if (other.hasJzrq()) {
          setJzrq(other.getJzrq());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              setCode(input.readString());
              break;
            }
            case 18: {
              setDthb1N(input.readString());
              break;
            }
            case 26: {
              setDthb2N(input.readString());
              break;
            }
            case 34: {
              setDthb3N(input.readString());
              break;
            }
            case 42: {
              setDthb4N(input.readString());
              break;
            }
            case 50: {
              setDthb5N(input.readString());
              break;
            }
            case 58: {
              setJjjz(input.readString());
              break;
            }
            case 66: {
              setLjjz(input.readString());
              break;
            }
            case 74: {
              setJzrq(input.readString());
              break;
            }
          }
        }
      }
      
      
      // optional string code = 1;
      public boolean hasCode() {
        return result.hasCode();
      }
      public java.lang.String getCode() {
        return result.getCode();
      }
      public Builder setCode(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasCode = true;
        result.code_ = value;
        return this;
      }
      public Builder clearCode() {
        result.hasCode = false;
        result.code_ = getDefaultInstance().getCode();
        return this;
      }
      
      // optional string dthb1n = 2;
      public boolean hasDthb1N() {
        return result.hasDthb1N();
      }
      public java.lang.String getDthb1N() {
        return result.getDthb1N();
      }
      public Builder setDthb1N(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasDthb1N = true;
        result.dthb1N_ = value;
        return this;
      }
      public Builder clearDthb1N() {
        result.hasDthb1N = false;
        result.dthb1N_ = getDefaultInstance().getDthb1N();
        return this;
      }
      
      // optional string dthb2n = 3;
      public boolean hasDthb2N() {
        return result.hasDthb2N();
      }
      public java.lang.String getDthb2N() {
        return result.getDthb2N();
      }
      public Builder setDthb2N(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasDthb2N = true;
        result.dthb2N_ = value;
        return this;
      }
      public Builder clearDthb2N() {
        result.hasDthb2N = false;
        result.dthb2N_ = getDefaultInstance().getDthb2N();
        return this;
      }
      
      // optional string dthb3n = 4;
      public boolean hasDthb3N() {
        return result.hasDthb3N();
      }
      public java.lang.String getDthb3N() {
        return result.getDthb3N();
      }
      public Builder setDthb3N(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasDthb3N = true;
        result.dthb3N_ = value;
        return this;
      }
      public Builder clearDthb3N() {
        result.hasDthb3N = false;
        result.dthb3N_ = getDefaultInstance().getDthb3N();
        return this;
      }
      
      // optional string dthb4n = 5;
      public boolean hasDthb4N() {
        return result.hasDthb4N();
      }
      public java.lang.String getDthb4N() {
        return result.getDthb4N();
      }
      public Builder setDthb4N(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasDthb4N = true;
        result.dthb4N_ = value;
        return this;
      }
      public Builder clearDthb4N() {
        result.hasDthb4N = false;
        result.dthb4N_ = getDefaultInstance().getDthb4N();
        return this;
      }
      
      // optional string dthb5n = 6;
      public boolean hasDthb5N() {
        return result.hasDthb5N();
      }
      public java.lang.String getDthb5N() {
        return result.getDthb5N();
      }
      public Builder setDthb5N(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasDthb5N = true;
        result.dthb5N_ = value;
        return this;
      }
      public Builder clearDthb5N() {
        result.hasDthb5N = false;
        result.dthb5N_ = getDefaultInstance().getDthb5N();
        return this;
      }
      
      // optional string jjjz = 7;
      public boolean hasJjjz() {
        return result.hasJjjz();
      }
      public java.lang.String getJjjz() {
        return result.getJjjz();
      }
      public Builder setJjjz(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasJjjz = true;
        result.jjjz_ = value;
        return this;
      }
      public Builder clearJjjz() {
        result.hasJjjz = false;
        result.jjjz_ = getDefaultInstance().getJjjz();
        return this;
      }
      
      // optional string ljjz = 8;
      public boolean hasLjjz() {
        return result.hasLjjz();
      }
      public java.lang.String getLjjz() {
        return result.getLjjz();
      }
      public Builder setLjjz(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasLjjz = true;
        result.ljjz_ = value;
        return this;
      }
      public Builder clearLjjz() {
        result.hasLjjz = false;
        result.ljjz_ = getDefaultInstance().getLjjz();
        return this;
      }
      
      // optional string jzrq = 9;
      public boolean hasJzrq() {
        return result.hasJzrq();
      }
      public java.lang.String getJzrq() {
        return result.getJzrq();
      }
      public Builder setJzrq(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasJzrq = true;
        result.jzrq_ = value;
        return this;
      }
      public Builder clearJzrq() {
        result.hasJzrq = false;
        result.jzrq_ = getDefaultInstance().getJzrq();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:Fundfixed)
    }
    
    static {
      defaultInstance = new Fundfixed(true);
      com.howbuy.wireless.entity.protobuf.FundfixedProtos.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:Fundfixed)
  }
  
  public static final class FundFixedUpdate extends
      com.google.protobuf.GeneratedMessage {
    // Use FundFixedUpdate.newBuilder() to construct.
    private FundFixedUpdate() {
      initFields();
    }
    private FundFixedUpdate(boolean noInit) {}
    
    private static final FundFixedUpdate defaultInstance;
    public static FundFixedUpdate getDefaultInstance() {
      return defaultInstance;
    }
    
    public FundFixedUpdate getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.howbuy.wireless.entity.protobuf.FundfixedProtos.internal_static_FundFixedUpdate_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.howbuy.wireless.entity.protobuf.FundfixedProtos.internal_static_FundFixedUpdate_fieldAccessorTable;
    }
    
    // optional .common.Common common = 1;
    public static final int COMMON_FIELD_NUMBER = 1;
    private boolean hasCommon;
    private com.howbuy.wireless.entity.protobuf.CommonProtos.Common common_;
    public boolean hasCommon() { return hasCommon; }
    public com.howbuy.wireless.entity.protobuf.CommonProtos.Common getCommon() { return common_; }
    
    // optional int32 sumPage = 2;
    public static final int SUMPAGE_FIELD_NUMBER = 2;
    private boolean hasSumPage;
    private int sumPage_ = 0;
    public boolean hasSumPage() { return hasSumPage; }
    public int getSumPage() { return sumPage_; }
    
    // repeated .Fundfixed fundfixed = 3;
    public static final int FUNDFIXED_FIELD_NUMBER = 3;
    private java.util.List<com.howbuy.wireless.entity.protobuf.FundfixedProtos.Fundfixed> fundfixed_ =
      java.util.Collections.emptyList();
    public java.util.List<com.howbuy.wireless.entity.protobuf.FundfixedProtos.Fundfixed> getFundfixedList() {
      return fundfixed_;
    }
    public int getFundfixedCount() { return fundfixed_.size(); }
    public com.howbuy.wireless.entity.protobuf.FundfixedProtos.Fundfixed getFundfixed(int index) {
      return fundfixed_.get(index);
    }
    
    private void initFields() {
      common_ = com.howbuy.wireless.entity.protobuf.CommonProtos.Common.getDefaultInstance();
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasCommon()) {
        output.writeMessage(1, getCommon());
      }
      if (hasSumPage()) {
        output.writeInt32(2, getSumPage());
      }
      for (com.howbuy.wireless.entity.protobuf.FundfixedProtos.Fundfixed element : getFundfixedList()) {
        output.writeMessage(3, element);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasCommon()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getCommon());
      }
      if (hasSumPage()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, getSumPage());
      }
      for (com.howbuy.wireless.entity.protobuf.FundfixedProtos.Fundfixed element : getFundfixedList()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, element);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.howbuy.wireless.entity.protobuf.FundfixedProtos.FundFixedUpdate parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.howbuy.wireless.entity.protobuf.FundfixedProtos.FundFixedUpdate parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.howbuy.wireless.entity.protobuf.FundfixedProtos.FundFixedUpdate parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.howbuy.wireless.entity.protobuf.FundfixedProtos.FundFixedUpdate parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.howbuy.wireless.entity.protobuf.FundfixedProtos.FundFixedUpdate parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.howbuy.wireless.entity.protobuf.FundfixedProtos.FundFixedUpdate parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.howbuy.wireless.entity.protobuf.FundfixedProtos.FundFixedUpdate parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.howbuy.wireless.entity.protobuf.FundfixedProtos.FundFixedUpdate parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.howbuy.wireless.entity.protobuf.FundfixedProtos.FundFixedUpdate parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.howbuy.wireless.entity.protobuf.FundfixedProtos.FundFixedUpdate parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.howbuy.wireless.entity.protobuf.FundfixedProtos.FundFixedUpdate prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.howbuy.wireless.entity.protobuf.FundfixedProtos.FundFixedUpdate result;
      
      // Construct using com.howbuy.wireless.entity.protobuf.FundfixedProtos.FundFixedUpdate.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.howbuy.wireless.entity.protobuf.FundfixedProtos.FundFixedUpdate();
        return builder;
      }
      
      protected com.howbuy.wireless.entity.protobuf.FundfixedProtos.FundFixedUpdate internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.howbuy.wireless.entity.protobuf.FundfixedProtos.FundFixedUpdate();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.howbuy.wireless.entity.protobuf.FundfixedProtos.FundFixedUpdate.getDescriptor();
      }
      
      public com.howbuy.wireless.entity.protobuf.FundfixedProtos.FundFixedUpdate getDefaultInstanceForType() {
        return com.howbuy.wireless.entity.protobuf.FundfixedProtos.FundFixedUpdate.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.howbuy.wireless.entity.protobuf.FundfixedProtos.FundFixedUpdate build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.howbuy.wireless.entity.protobuf.FundfixedProtos.FundFixedUpdate buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.howbuy.wireless.entity.protobuf.FundfixedProtos.FundFixedUpdate buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        if (result.fundfixed_ != java.util.Collections.EMPTY_LIST) {
          result.fundfixed_ =
            java.util.Collections.unmodifiableList(result.fundfixed_);
        }
        com.howbuy.wireless.entity.protobuf.FundfixedProtos.FundFixedUpdate returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.howbuy.wireless.entity.protobuf.FundfixedProtos.FundFixedUpdate) {
          return mergeFrom((com.howbuy.wireless.entity.protobuf.FundfixedProtos.FundFixedUpdate)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.howbuy.wireless.entity.protobuf.FundfixedProtos.FundFixedUpdate other) {
        if (other == com.howbuy.wireless.entity.protobuf.FundfixedProtos.FundFixedUpdate.getDefaultInstance()) return this;
        if (other.hasCommon()) {
          mergeCommon(other.getCommon());
        }
        if (other.hasSumPage()) {
          setSumPage(other.getSumPage());
        }
        if (!other.fundfixed_.isEmpty()) {
          if (result.fundfixed_.isEmpty()) {
            result.fundfixed_ = new java.util.ArrayList<com.howbuy.wireless.entity.protobuf.FundfixedProtos.Fundfixed>();
          }
          result.fundfixed_.addAll(other.fundfixed_);
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              com.howbuy.wireless.entity.protobuf.CommonProtos.Common.Builder subBuilder = com.howbuy.wireless.entity.protobuf.CommonProtos.Common.newBuilder();
              if (hasCommon()) {
                subBuilder.mergeFrom(getCommon());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setCommon(subBuilder.buildPartial());
              break;
            }
            case 16: {
              setSumPage(input.readInt32());
              break;
            }
            case 26: {
              com.howbuy.wireless.entity.protobuf.FundfixedProtos.Fundfixed.Builder subBuilder = com.howbuy.wireless.entity.protobuf.FundfixedProtos.Fundfixed.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addFundfixed(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      
      // optional .common.Common common = 1;
      public boolean hasCommon() {
        return result.hasCommon();
      }
      public com.howbuy.wireless.entity.protobuf.CommonProtos.Common getCommon() {
        return result.getCommon();
      }
      public Builder setCommon(com.howbuy.wireless.entity.protobuf.CommonProtos.Common value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasCommon = true;
        result.common_ = value;
        return this;
      }
      public Builder setCommon(com.howbuy.wireless.entity.protobuf.CommonProtos.Common.Builder builderForValue) {
        result.hasCommon = true;
        result.common_ = builderForValue.build();
        return this;
      }
      public Builder mergeCommon(com.howbuy.wireless.entity.protobuf.CommonProtos.Common value) {
        if (result.hasCommon() &&
            result.common_ != com.howbuy.wireless.entity.protobuf.CommonProtos.Common.getDefaultInstance()) {
          result.common_ =
            com.howbuy.wireless.entity.protobuf.CommonProtos.Common.newBuilder(result.common_).mergeFrom(value).buildPartial();
        } else {
          result.common_ = value;
        }
        result.hasCommon = true;
        return this;
      }
      public Builder clearCommon() {
        result.hasCommon = false;
        result.common_ = com.howbuy.wireless.entity.protobuf.CommonProtos.Common.getDefaultInstance();
        return this;
      }
      
      // optional int32 sumPage = 2;
      public boolean hasSumPage() {
        return result.hasSumPage();
      }
      public int getSumPage() {
        return result.getSumPage();
      }
      public Builder setSumPage(int value) {
        result.hasSumPage = true;
        result.sumPage_ = value;
        return this;
      }
      public Builder clearSumPage() {
        result.hasSumPage = false;
        result.sumPage_ = 0;
        return this;
      }
      
      // repeated .Fundfixed fundfixed = 3;
      public java.util.List<com.howbuy.wireless.entity.protobuf.FundfixedProtos.Fundfixed> getFundfixedList() {
        return java.util.Collections.unmodifiableList(result.fundfixed_);
      }
      public int getFundfixedCount() {
        return result.getFundfixedCount();
      }
      public com.howbuy.wireless.entity.protobuf.FundfixedProtos.Fundfixed getFundfixed(int index) {
        return result.getFundfixed(index);
      }
      public Builder setFundfixed(int index, com.howbuy.wireless.entity.protobuf.FundfixedProtos.Fundfixed value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.fundfixed_.set(index, value);
        return this;
      }
      public Builder setFundfixed(int index, com.howbuy.wireless.entity.protobuf.FundfixedProtos.Fundfixed.Builder builderForValue) {
        result.fundfixed_.set(index, builderForValue.build());
        return this;
      }
      public Builder addFundfixed(com.howbuy.wireless.entity.protobuf.FundfixedProtos.Fundfixed value) {
        if (value == null) {
          throw new NullPointerException();
        }
        if (result.fundfixed_.isEmpty()) {
          result.fundfixed_ = new java.util.ArrayList<com.howbuy.wireless.entity.protobuf.FundfixedProtos.Fundfixed>();
        }
        result.fundfixed_.add(value);
        return this;
      }
      public Builder addFundfixed(com.howbuy.wireless.entity.protobuf.FundfixedProtos.Fundfixed.Builder builderForValue) {
        if (result.fundfixed_.isEmpty()) {
          result.fundfixed_ = new java.util.ArrayList<com.howbuy.wireless.entity.protobuf.FundfixedProtos.Fundfixed>();
        }
        result.fundfixed_.add(builderForValue.build());
        return this;
      }
      public Builder addAllFundfixed(
          java.lang.Iterable<? extends com.howbuy.wireless.entity.protobuf.FundfixedProtos.Fundfixed> values) {
        if (result.fundfixed_.isEmpty()) {
          result.fundfixed_ = new java.util.ArrayList<com.howbuy.wireless.entity.protobuf.FundfixedProtos.Fundfixed>();
        }
        super.addAll(values, result.fundfixed_);
        return this;
      }
      public Builder clearFundfixed() {
        result.fundfixed_ = java.util.Collections.emptyList();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:FundFixedUpdate)
    }
    
    static {
      defaultInstance = new FundFixedUpdate(true);
      com.howbuy.wireless.entity.protobuf.FundfixedProtos.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:FundFixedUpdate)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Fundfixed_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Fundfixed_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_FundFixedUpdate_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_FundFixedUpdate_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017Fundfixed.proto\032\014common.proto\"\223\001\n\tFund" +
      "fixed\022\014\n\004code\030\001 \001(\t\022\016\n\006dthb1n\030\002 \001(\t\022\016\n\006d" +
      "thb2n\030\003 \001(\t\022\016\n\006dthb3n\030\004 \001(\t\022\016\n\006dthb4n\030\005 " +
      "\001(\t\022\016\n\006dthb5n\030\006 \001(\t\022\014\n\004jjjz\030\007 \001(\t\022\014\n\004ljj" +
      "z\030\010 \001(\t\022\014\n\004jzrq\030\t \001(\t\"a\n\017FundFixedUpdate" +
      "\022\036\n\006common\030\001 \001(\0132\016.common.Common\022\017\n\007sumP" +
      "age\030\002 \001(\005\022\035\n\tfundfixed\030\003 \003(\0132\n.Fundfixed" +
      "B6\n#com.howbuy.wireless.entity.protobufB" +
      "\017FundfixedProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_Fundfixed_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_Fundfixed_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Fundfixed_descriptor,
              new java.lang.String[] { "Code", "Dthb1N", "Dthb2N", "Dthb3N", "Dthb4N", "Dthb5N", "Jjjz", "Ljjz", "Jzrq", },
              com.howbuy.wireless.entity.protobuf.FundfixedProtos.Fundfixed.class,
              com.howbuy.wireless.entity.protobuf.FundfixedProtos.Fundfixed.Builder.class);
          internal_static_FundFixedUpdate_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_FundFixedUpdate_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_FundFixedUpdate_descriptor,
              new java.lang.String[] { "Common", "SumPage", "Fundfixed", },
              com.howbuy.wireless.entity.protobuf.FundfixedProtos.FundFixedUpdate.class,
              com.howbuy.wireless.entity.protobuf.FundfixedProtos.FundFixedUpdate.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.howbuy.wireless.entity.protobuf.CommonProtos.getDescriptor(),
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
