// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fundInfoMoneysOfPage.proto

package com.howbuy.wireless.entity.protobuf;

public final class FundInfoMoneysOfPageProto {
  private FundInfoMoneysOfPageProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class FundInfoMoneysOfPage extends
      com.google.protobuf.GeneratedMessage {
    // Use FundInfoMoneysOfPage.newBuilder() to construct.
    private FundInfoMoneysOfPage() {
      initFields();
    }
    private FundInfoMoneysOfPage(boolean noInit) {}
    
    private static final FundInfoMoneysOfPage defaultInstance;
    public static FundInfoMoneysOfPage getDefaultInstance() {
      return defaultInstance;
    }
    
    public FundInfoMoneysOfPage getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.howbuy.wireless.entity.protobuf.FundInfoMoneysOfPageProto.internal_static_FundInfoMoneysOfPage_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.howbuy.wireless.entity.protobuf.FundInfoMoneysOfPageProto.internal_static_FundInfoMoneysOfPage_fieldAccessorTable;
    }
    
    // optional .common.Common common = 1;
    public static final int COMMON_FIELD_NUMBER = 1;
    private boolean hasCommon;
    private com.howbuy.wireless.entity.protobuf.CommonProtos.Common common_;
    public boolean hasCommon() { return hasCommon; }
    public com.howbuy.wireless.entity.protobuf.CommonProtos.Common getCommon() { return common_; }
    
    // repeated .MoneysOfPage moneysOfPage = 2;
    public static final int MONEYSOFPAGE_FIELD_NUMBER = 2;
    private java.util.List<com.howbuy.wireless.entity.protobuf.MoneysOfPageProtos.MoneysOfPage> moneysOfPage_ =
      java.util.Collections.emptyList();
    public java.util.List<com.howbuy.wireless.entity.protobuf.MoneysOfPageProtos.MoneysOfPage> getMoneysOfPageList() {
      return moneysOfPage_;
    }
    public int getMoneysOfPageCount() { return moneysOfPage_.size(); }
    public com.howbuy.wireless.entity.protobuf.MoneysOfPageProtos.MoneysOfPage getMoneysOfPage(int index) {
      return moneysOfPage_.get(index);
    }
    
    // optional int32 sumPage = 3;
    public static final int SUMPAGE_FIELD_NUMBER = 3;
    private boolean hasSumPage;
    private int sumPage_ = 0;
    public boolean hasSumPage() { return hasSumPage; }
    public int getSumPage() { return sumPage_; }
    
    private void initFields() {
      common_ = com.howbuy.wireless.entity.protobuf.CommonProtos.Common.getDefaultInstance();
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasCommon()) {
        output.writeMessage(1, getCommon());
      }
      for (com.howbuy.wireless.entity.protobuf.MoneysOfPageProtos.MoneysOfPage element : getMoneysOfPageList()) {
        output.writeMessage(2, element);
      }
      if (hasSumPage()) {
        output.writeInt32(3, getSumPage());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasCommon()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getCommon());
      }
      for (com.howbuy.wireless.entity.protobuf.MoneysOfPageProtos.MoneysOfPage element : getMoneysOfPageList()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, element);
      }
      if (hasSumPage()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, getSumPage());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.howbuy.wireless.entity.protobuf.FundInfoMoneysOfPageProto.FundInfoMoneysOfPage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.howbuy.wireless.entity.protobuf.FundInfoMoneysOfPageProto.FundInfoMoneysOfPage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.howbuy.wireless.entity.protobuf.FundInfoMoneysOfPageProto.FundInfoMoneysOfPage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.howbuy.wireless.entity.protobuf.FundInfoMoneysOfPageProto.FundInfoMoneysOfPage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.howbuy.wireless.entity.protobuf.FundInfoMoneysOfPageProto.FundInfoMoneysOfPage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.howbuy.wireless.entity.protobuf.FundInfoMoneysOfPageProto.FundInfoMoneysOfPage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.howbuy.wireless.entity.protobuf.FundInfoMoneysOfPageProto.FundInfoMoneysOfPage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.howbuy.wireless.entity.protobuf.FundInfoMoneysOfPageProto.FundInfoMoneysOfPage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.howbuy.wireless.entity.protobuf.FundInfoMoneysOfPageProto.FundInfoMoneysOfPage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.howbuy.wireless.entity.protobuf.FundInfoMoneysOfPageProto.FundInfoMoneysOfPage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.howbuy.wireless.entity.protobuf.FundInfoMoneysOfPageProto.FundInfoMoneysOfPage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.howbuy.wireless.entity.protobuf.FundInfoMoneysOfPageProto.FundInfoMoneysOfPage result;
      
      // Construct using com.howbuy.wireless.entity.protobuf.FundInfoMoneysOfPageProto.FundInfoMoneysOfPage.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.howbuy.wireless.entity.protobuf.FundInfoMoneysOfPageProto.FundInfoMoneysOfPage();
        return builder;
      }
      
      protected com.howbuy.wireless.entity.protobuf.FundInfoMoneysOfPageProto.FundInfoMoneysOfPage internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.howbuy.wireless.entity.protobuf.FundInfoMoneysOfPageProto.FundInfoMoneysOfPage();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.howbuy.wireless.entity.protobuf.FundInfoMoneysOfPageProto.FundInfoMoneysOfPage.getDescriptor();
      }
      
      public com.howbuy.wireless.entity.protobuf.FundInfoMoneysOfPageProto.FundInfoMoneysOfPage getDefaultInstanceForType() {
        return com.howbuy.wireless.entity.protobuf.FundInfoMoneysOfPageProto.FundInfoMoneysOfPage.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.howbuy.wireless.entity.protobuf.FundInfoMoneysOfPageProto.FundInfoMoneysOfPage build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.howbuy.wireless.entity.protobuf.FundInfoMoneysOfPageProto.FundInfoMoneysOfPage buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.howbuy.wireless.entity.protobuf.FundInfoMoneysOfPageProto.FundInfoMoneysOfPage buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        if (result.moneysOfPage_ != java.util.Collections.EMPTY_LIST) {
          result.moneysOfPage_ =
            java.util.Collections.unmodifiableList(result.moneysOfPage_);
        }
        com.howbuy.wireless.entity.protobuf.FundInfoMoneysOfPageProto.FundInfoMoneysOfPage returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.howbuy.wireless.entity.protobuf.FundInfoMoneysOfPageProto.FundInfoMoneysOfPage) {
          return mergeFrom((com.howbuy.wireless.entity.protobuf.FundInfoMoneysOfPageProto.FundInfoMoneysOfPage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.howbuy.wireless.entity.protobuf.FundInfoMoneysOfPageProto.FundInfoMoneysOfPage other) {
        if (other == com.howbuy.wireless.entity.protobuf.FundInfoMoneysOfPageProto.FundInfoMoneysOfPage.getDefaultInstance()) return this;
        if (other.hasCommon()) {
          mergeCommon(other.getCommon());
        }
        if (!other.moneysOfPage_.isEmpty()) {
          if (result.moneysOfPage_.isEmpty()) {
            result.moneysOfPage_ = new java.util.ArrayList<com.howbuy.wireless.entity.protobuf.MoneysOfPageProtos.MoneysOfPage>();
          }
          result.moneysOfPage_.addAll(other.moneysOfPage_);
        }
        if (other.hasSumPage()) {
          setSumPage(other.getSumPage());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              com.howbuy.wireless.entity.protobuf.CommonProtos.Common.Builder subBuilder = com.howbuy.wireless.entity.protobuf.CommonProtos.Common.newBuilder();
              if (hasCommon()) {
                subBuilder.mergeFrom(getCommon());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setCommon(subBuilder.buildPartial());
              break;
            }
            case 18: {
              com.howbuy.wireless.entity.protobuf.MoneysOfPageProtos.MoneysOfPage.Builder subBuilder = com.howbuy.wireless.entity.protobuf.MoneysOfPageProtos.MoneysOfPage.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addMoneysOfPage(subBuilder.buildPartial());
              break;
            }
            case 24: {
              setSumPage(input.readInt32());
              break;
            }
          }
        }
      }
      
      
      // optional .common.Common common = 1;
      public boolean hasCommon() {
        return result.hasCommon();
      }
      public com.howbuy.wireless.entity.protobuf.CommonProtos.Common getCommon() {
        return result.getCommon();
      }
      public Builder setCommon(com.howbuy.wireless.entity.protobuf.CommonProtos.Common value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasCommon = true;
        result.common_ = value;
        return this;
      }
      public Builder setCommon(com.howbuy.wireless.entity.protobuf.CommonProtos.Common.Builder builderForValue) {
        result.hasCommon = true;
        result.common_ = builderForValue.build();
        return this;
      }
      public Builder mergeCommon(com.howbuy.wireless.entity.protobuf.CommonProtos.Common value) {
        if (result.hasCommon() &&
            result.common_ != com.howbuy.wireless.entity.protobuf.CommonProtos.Common.getDefaultInstance()) {
          result.common_ =
            com.howbuy.wireless.entity.protobuf.CommonProtos.Common.newBuilder(result.common_).mergeFrom(value).buildPartial();
        } else {
          result.common_ = value;
        }
        result.hasCommon = true;
        return this;
      }
      public Builder clearCommon() {
        result.hasCommon = false;
        result.common_ = com.howbuy.wireless.entity.protobuf.CommonProtos.Common.getDefaultInstance();
        return this;
      }
      
      // repeated .MoneysOfPage moneysOfPage = 2;
      public java.util.List<com.howbuy.wireless.entity.protobuf.MoneysOfPageProtos.MoneysOfPage> getMoneysOfPageList() {
        return java.util.Collections.unmodifiableList(result.moneysOfPage_);
      }
      public int getMoneysOfPageCount() {
        return result.getMoneysOfPageCount();
      }
      public com.howbuy.wireless.entity.protobuf.MoneysOfPageProtos.MoneysOfPage getMoneysOfPage(int index) {
        return result.getMoneysOfPage(index);
      }
      public Builder setMoneysOfPage(int index, com.howbuy.wireless.entity.protobuf.MoneysOfPageProtos.MoneysOfPage value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.moneysOfPage_.set(index, value);
        return this;
      }
      public Builder setMoneysOfPage(int index, com.howbuy.wireless.entity.protobuf.MoneysOfPageProtos.MoneysOfPage.Builder builderForValue) {
        result.moneysOfPage_.set(index, builderForValue.build());
        return this;
      }
      public Builder addMoneysOfPage(com.howbuy.wireless.entity.protobuf.MoneysOfPageProtos.MoneysOfPage value) {
        if (value == null) {
          throw new NullPointerException();
        }
        if (result.moneysOfPage_.isEmpty()) {
          result.moneysOfPage_ = new java.util.ArrayList<com.howbuy.wireless.entity.protobuf.MoneysOfPageProtos.MoneysOfPage>();
        }
        result.moneysOfPage_.add(value);
        return this;
      }
      public Builder addMoneysOfPage(com.howbuy.wireless.entity.protobuf.MoneysOfPageProtos.MoneysOfPage.Builder builderForValue) {
        if (result.moneysOfPage_.isEmpty()) {
          result.moneysOfPage_ = new java.util.ArrayList<com.howbuy.wireless.entity.protobuf.MoneysOfPageProtos.MoneysOfPage>();
        }
        result.moneysOfPage_.add(builderForValue.build());
        return this;
      }
      public Builder addAllMoneysOfPage(
          java.lang.Iterable<? extends com.howbuy.wireless.entity.protobuf.MoneysOfPageProtos.MoneysOfPage> values) {
        if (result.moneysOfPage_.isEmpty()) {
          result.moneysOfPage_ = new java.util.ArrayList<com.howbuy.wireless.entity.protobuf.MoneysOfPageProtos.MoneysOfPage>();
        }
        super.addAll(values, result.moneysOfPage_);
        return this;
      }
      public Builder clearMoneysOfPage() {
        result.moneysOfPage_ = java.util.Collections.emptyList();
        return this;
      }
      
      // optional int32 sumPage = 3;
      public boolean hasSumPage() {
        return result.hasSumPage();
      }
      public int getSumPage() {
        return result.getSumPage();
      }
      public Builder setSumPage(int value) {
        result.hasSumPage = true;
        result.sumPage_ = value;
        return this;
      }
      public Builder clearSumPage() {
        result.hasSumPage = false;
        result.sumPage_ = 0;
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:FundInfoMoneysOfPage)
    }
    
    static {
      defaultInstance = new FundInfoMoneysOfPage(true);
      com.howbuy.wireless.entity.protobuf.FundInfoMoneysOfPageProto.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:FundInfoMoneysOfPage)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_FundInfoMoneysOfPage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_FundInfoMoneysOfPage_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032fundInfoMoneysOfPage.proto\032\022moneysOfPa" +
      "ge.proto\032\014common.proto\"l\n\024FundInfoMoneys" +
      "OfPage\022\036\n\006common\030\001 \001(\0132\016.common.Common\022#" +
      "\n\014moneysOfPage\030\002 \003(\0132\r.MoneysOfPage\022\017\n\007s" +
      "umPage\030\003 \001(\005B@\n#com.howbuy.wireless.enti" +
      "ty.protobufB\031FundInfoMoneysOfPageProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_FundInfoMoneysOfPage_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_FundInfoMoneysOfPage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_FundInfoMoneysOfPage_descriptor,
              new java.lang.String[] { "Common", "MoneysOfPage", "SumPage", },
              com.howbuy.wireless.entity.protobuf.FundInfoMoneysOfPageProto.FundInfoMoneysOfPage.class,
              com.howbuy.wireless.entity.protobuf.FundInfoMoneysOfPageProto.FundInfoMoneysOfPage.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.howbuy.wireless.entity.protobuf.MoneysOfPageProtos.getDescriptor(),
          com.howbuy.wireless.entity.protobuf.CommonProtos.getDescriptor(),
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
