// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fundCompanyInfoList.proto

package com.howbuy.wireless.entity.protobuf;

public final class FundCompanyInfoListProto {
  private FundCompanyInfoListProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class FundCompanyInfoList extends
      com.google.protobuf.GeneratedMessage {
    // Use FundCompanyInfoList.newBuilder() to construct.
    private FundCompanyInfoList() {
      initFields();
    }
    private FundCompanyInfoList(boolean noInit) {}
    
    private static final FundCompanyInfoList defaultInstance;
    public static FundCompanyInfoList getDefaultInstance() {
      return defaultInstance;
    }
    
    public FundCompanyInfoList getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.howbuy.wireless.entity.protobuf.FundCompanyInfoListProto.internal_static_FundCompanyInfoList_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.howbuy.wireless.entity.protobuf.FundCompanyInfoListProto.internal_static_FundCompanyInfoList_fieldAccessorTable;
    }
    
    // optional .common.Common common = 1;
    public static final int COMMON_FIELD_NUMBER = 1;
    private boolean hasCommon;
    private com.howbuy.wireless.entity.protobuf.CommonProtos.Common common_;
    public boolean hasCommon() { return hasCommon; }
    public com.howbuy.wireless.entity.protobuf.CommonProtos.Common getCommon() { return common_; }
    
    // optional string newestCompanyInfoVer = 2;
    public static final int NEWESTCOMPANYINFOVER_FIELD_NUMBER = 2;
    private boolean hasNewestCompanyInfoVer;
    private java.lang.String newestCompanyInfoVer_ = "";
    public boolean hasNewestCompanyInfoVer() { return hasNewestCompanyInfoVer; }
    public java.lang.String getNewestCompanyInfoVer() { return newestCompanyInfoVer_; }
    
    // repeated .FundCompanyInfo fundCompanyInfo = 3;
    public static final int FUNDCOMPANYINFO_FIELD_NUMBER = 3;
    private java.util.List<com.howbuy.wireless.entity.protobuf.FundCompanyInfoProtos.FundCompanyInfo> fundCompanyInfo_ =
      java.util.Collections.emptyList();
    public java.util.List<com.howbuy.wireless.entity.protobuf.FundCompanyInfoProtos.FundCompanyInfo> getFundCompanyInfoList() {
      return fundCompanyInfo_;
    }
    public int getFundCompanyInfoCount() { return fundCompanyInfo_.size(); }
    public com.howbuy.wireless.entity.protobuf.FundCompanyInfoProtos.FundCompanyInfo getFundCompanyInfo(int index) {
      return fundCompanyInfo_.get(index);
    }
    
    private void initFields() {
      common_ = com.howbuy.wireless.entity.protobuf.CommonProtos.Common.getDefaultInstance();
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasCommon()) {
        output.writeMessage(1, getCommon());
      }
      if (hasNewestCompanyInfoVer()) {
        output.writeString(2, getNewestCompanyInfoVer());
      }
      for (com.howbuy.wireless.entity.protobuf.FundCompanyInfoProtos.FundCompanyInfo element : getFundCompanyInfoList()) {
        output.writeMessage(3, element);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasCommon()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getCommon());
      }
      if (hasNewestCompanyInfoVer()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getNewestCompanyInfoVer());
      }
      for (com.howbuy.wireless.entity.protobuf.FundCompanyInfoProtos.FundCompanyInfo element : getFundCompanyInfoList()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, element);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.howbuy.wireless.entity.protobuf.FundCompanyInfoListProto.FundCompanyInfoList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.howbuy.wireless.entity.protobuf.FundCompanyInfoListProto.FundCompanyInfoList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.howbuy.wireless.entity.protobuf.FundCompanyInfoListProto.FundCompanyInfoList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.howbuy.wireless.entity.protobuf.FundCompanyInfoListProto.FundCompanyInfoList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.howbuy.wireless.entity.protobuf.FundCompanyInfoListProto.FundCompanyInfoList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.howbuy.wireless.entity.protobuf.FundCompanyInfoListProto.FundCompanyInfoList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.howbuy.wireless.entity.protobuf.FundCompanyInfoListProto.FundCompanyInfoList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.howbuy.wireless.entity.protobuf.FundCompanyInfoListProto.FundCompanyInfoList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.howbuy.wireless.entity.protobuf.FundCompanyInfoListProto.FundCompanyInfoList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.howbuy.wireless.entity.protobuf.FundCompanyInfoListProto.FundCompanyInfoList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.howbuy.wireless.entity.protobuf.FundCompanyInfoListProto.FundCompanyInfoList prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.howbuy.wireless.entity.protobuf.FundCompanyInfoListProto.FundCompanyInfoList result;
      
      // Construct using com.howbuy.wireless.entity.protobuf.FundCompanyInfoListProto.FundCompanyInfoList.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.howbuy.wireless.entity.protobuf.FundCompanyInfoListProto.FundCompanyInfoList();
        return builder;
      }
      
      protected com.howbuy.wireless.entity.protobuf.FundCompanyInfoListProto.FundCompanyInfoList internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.howbuy.wireless.entity.protobuf.FundCompanyInfoListProto.FundCompanyInfoList();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.howbuy.wireless.entity.protobuf.FundCompanyInfoListProto.FundCompanyInfoList.getDescriptor();
      }
      
      public com.howbuy.wireless.entity.protobuf.FundCompanyInfoListProto.FundCompanyInfoList getDefaultInstanceForType() {
        return com.howbuy.wireless.entity.protobuf.FundCompanyInfoListProto.FundCompanyInfoList.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.howbuy.wireless.entity.protobuf.FundCompanyInfoListProto.FundCompanyInfoList build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.howbuy.wireless.entity.protobuf.FundCompanyInfoListProto.FundCompanyInfoList buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.howbuy.wireless.entity.protobuf.FundCompanyInfoListProto.FundCompanyInfoList buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        if (result.fundCompanyInfo_ != java.util.Collections.EMPTY_LIST) {
          result.fundCompanyInfo_ =
            java.util.Collections.unmodifiableList(result.fundCompanyInfo_);
        }
        com.howbuy.wireless.entity.protobuf.FundCompanyInfoListProto.FundCompanyInfoList returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.howbuy.wireless.entity.protobuf.FundCompanyInfoListProto.FundCompanyInfoList) {
          return mergeFrom((com.howbuy.wireless.entity.protobuf.FundCompanyInfoListProto.FundCompanyInfoList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.howbuy.wireless.entity.protobuf.FundCompanyInfoListProto.FundCompanyInfoList other) {
        if (other == com.howbuy.wireless.entity.protobuf.FundCompanyInfoListProto.FundCompanyInfoList.getDefaultInstance()) return this;
        if (other.hasCommon()) {
          mergeCommon(other.getCommon());
        }
        if (other.hasNewestCompanyInfoVer()) {
          setNewestCompanyInfoVer(other.getNewestCompanyInfoVer());
        }
        if (!other.fundCompanyInfo_.isEmpty()) {
          if (result.fundCompanyInfo_.isEmpty()) {
            result.fundCompanyInfo_ = new java.util.ArrayList<com.howbuy.wireless.entity.protobuf.FundCompanyInfoProtos.FundCompanyInfo>();
          }
          result.fundCompanyInfo_.addAll(other.fundCompanyInfo_);
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              com.howbuy.wireless.entity.protobuf.CommonProtos.Common.Builder subBuilder = com.howbuy.wireless.entity.protobuf.CommonProtos.Common.newBuilder();
              if (hasCommon()) {
                subBuilder.mergeFrom(getCommon());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setCommon(subBuilder.buildPartial());
              break;
            }
            case 18: {
              setNewestCompanyInfoVer(input.readString());
              break;
            }
            case 26: {
              com.howbuy.wireless.entity.protobuf.FundCompanyInfoProtos.FundCompanyInfo.Builder subBuilder = com.howbuy.wireless.entity.protobuf.FundCompanyInfoProtos.FundCompanyInfo.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addFundCompanyInfo(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      
      // optional .common.Common common = 1;
      public boolean hasCommon() {
        return result.hasCommon();
      }
      public com.howbuy.wireless.entity.protobuf.CommonProtos.Common getCommon() {
        return result.getCommon();
      }
      public Builder setCommon(com.howbuy.wireless.entity.protobuf.CommonProtos.Common value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasCommon = true;
        result.common_ = value;
        return this;
      }
      public Builder setCommon(com.howbuy.wireless.entity.protobuf.CommonProtos.Common.Builder builderForValue) {
        result.hasCommon = true;
        result.common_ = builderForValue.build();
        return this;
      }
      public Builder mergeCommon(com.howbuy.wireless.entity.protobuf.CommonProtos.Common value) {
        if (result.hasCommon() &&
            result.common_ != com.howbuy.wireless.entity.protobuf.CommonProtos.Common.getDefaultInstance()) {
          result.common_ =
            com.howbuy.wireless.entity.protobuf.CommonProtos.Common.newBuilder(result.common_).mergeFrom(value).buildPartial();
        } else {
          result.common_ = value;
        }
        result.hasCommon = true;
        return this;
      }
      public Builder clearCommon() {
        result.hasCommon = false;
        result.common_ = com.howbuy.wireless.entity.protobuf.CommonProtos.Common.getDefaultInstance();
        return this;
      }
      
      // optional string newestCompanyInfoVer = 2;
      public boolean hasNewestCompanyInfoVer() {
        return result.hasNewestCompanyInfoVer();
      }
      public java.lang.String getNewestCompanyInfoVer() {
        return result.getNewestCompanyInfoVer();
      }
      public Builder setNewestCompanyInfoVer(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasNewestCompanyInfoVer = true;
        result.newestCompanyInfoVer_ = value;
        return this;
      }
      public Builder clearNewestCompanyInfoVer() {
        result.hasNewestCompanyInfoVer = false;
        result.newestCompanyInfoVer_ = getDefaultInstance().getNewestCompanyInfoVer();
        return this;
      }
      
      // repeated .FundCompanyInfo fundCompanyInfo = 3;
      public java.util.List<com.howbuy.wireless.entity.protobuf.FundCompanyInfoProtos.FundCompanyInfo> getFundCompanyInfoList() {
        return java.util.Collections.unmodifiableList(result.fundCompanyInfo_);
      }
      public int getFundCompanyInfoCount() {
        return result.getFundCompanyInfoCount();
      }
      public com.howbuy.wireless.entity.protobuf.FundCompanyInfoProtos.FundCompanyInfo getFundCompanyInfo(int index) {
        return result.getFundCompanyInfo(index);
      }
      public Builder setFundCompanyInfo(int index, com.howbuy.wireless.entity.protobuf.FundCompanyInfoProtos.FundCompanyInfo value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.fundCompanyInfo_.set(index, value);
        return this;
      }
      public Builder setFundCompanyInfo(int index, com.howbuy.wireless.entity.protobuf.FundCompanyInfoProtos.FundCompanyInfo.Builder builderForValue) {
        result.fundCompanyInfo_.set(index, builderForValue.build());
        return this;
      }
      public Builder addFundCompanyInfo(com.howbuy.wireless.entity.protobuf.FundCompanyInfoProtos.FundCompanyInfo value) {
        if (value == null) {
          throw new NullPointerException();
        }
        if (result.fundCompanyInfo_.isEmpty()) {
          result.fundCompanyInfo_ = new java.util.ArrayList<com.howbuy.wireless.entity.protobuf.FundCompanyInfoProtos.FundCompanyInfo>();
        }
        result.fundCompanyInfo_.add(value);
        return this;
      }
      public Builder addFundCompanyInfo(com.howbuy.wireless.entity.protobuf.FundCompanyInfoProtos.FundCompanyInfo.Builder builderForValue) {
        if (result.fundCompanyInfo_.isEmpty()) {
          result.fundCompanyInfo_ = new java.util.ArrayList<com.howbuy.wireless.entity.protobuf.FundCompanyInfoProtos.FundCompanyInfo>();
        }
        result.fundCompanyInfo_.add(builderForValue.build());
        return this;
      }
      public Builder addAllFundCompanyInfo(
          java.lang.Iterable<? extends com.howbuy.wireless.entity.protobuf.FundCompanyInfoProtos.FundCompanyInfo> values) {
        if (result.fundCompanyInfo_.isEmpty()) {
          result.fundCompanyInfo_ = new java.util.ArrayList<com.howbuy.wireless.entity.protobuf.FundCompanyInfoProtos.FundCompanyInfo>();
        }
        super.addAll(values, result.fundCompanyInfo_);
        return this;
      }
      public Builder clearFundCompanyInfo() {
        result.fundCompanyInfo_ = java.util.Collections.emptyList();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:FundCompanyInfoList)
    }
    
    static {
      defaultInstance = new FundCompanyInfoList(true);
      com.howbuy.wireless.entity.protobuf.FundCompanyInfoListProto.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:FundCompanyInfoList)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_FundCompanyInfoList_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_FundCompanyInfoList_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031fundCompanyInfoList.proto\032\025fundCompany" +
      "Info.proto\032\014common.proto\"~\n\023FundCompanyI" +
      "nfoList\022\036\n\006common\030\001 \001(\0132\016.common.Common\022" +
      "\034\n\024newestCompanyInfoVer\030\002 \001(\t\022)\n\017fundCom" +
      "panyInfo\030\003 \003(\0132\020.FundCompanyInfoB?\n#com." +
      "howbuy.wireless.entity.protobufB\030FundCom" +
      "panyInfoListProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_FundCompanyInfoList_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_FundCompanyInfoList_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_FundCompanyInfoList_descriptor,
              new java.lang.String[] { "Common", "NewestCompanyInfoVer", "FundCompanyInfo", },
              com.howbuy.wireless.entity.protobuf.FundCompanyInfoListProto.FundCompanyInfoList.class,
              com.howbuy.wireless.entity.protobuf.FundCompanyInfoListProto.FundCompanyInfoList.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.howbuy.wireless.entity.protobuf.FundCompanyInfoProtos.getDescriptor(),
          com.howbuy.wireless.entity.protobuf.CommonProtos.getDescriptor(),
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
