// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: historyFundNetValueChart.proto

package com.howbuy.wireless.entity.protobuf;

public final class HistoryFundNetValueChartProtos {
  private HistoryFundNetValueChartProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class HistoryFundNetValueChart extends
      com.google.protobuf.GeneratedMessage {
    // Use HistoryFundNetValueChart.newBuilder() to construct.
    private HistoryFundNetValueChart() {
      initFields();
    }
    private HistoryFundNetValueChart(boolean noInit) {}
    
    private static final HistoryFundNetValueChart defaultInstance;
    public static HistoryFundNetValueChart getDefaultInstance() {
      return defaultInstance;
    }
    
    public HistoryFundNetValueChart getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.howbuy.wireless.entity.protobuf.HistoryFundNetValueChartProtos.internal_static_HistoryFundNetValueChart_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.howbuy.wireless.entity.protobuf.HistoryFundNetValueChartProtos.internal_static_HistoryFundNetValueChart_fieldAccessorTable;
    }
    
    // optional .common.Common common = 1;
    public static final int COMMON_FIELD_NUMBER = 1;
    private boolean hasCommon;
    private com.howbuy.wireless.entity.protobuf.CommonProtos.Common common_;
    public boolean hasCommon() { return hasCommon; }
    public com.howbuy.wireless.entity.protobuf.CommonProtos.Common getCommon() { return common_; }
    
    // optional string now = 2;
    public static final int NOW_FIELD_NUMBER = 2;
    private boolean hasNow;
    private java.lang.String now_ = "";
    public boolean hasNow() { return hasNow; }
    public java.lang.String getNow() { return now_; }
    
    // repeated .NetValueInfo netValueInfo = 3;
    public static final int NETVALUEINFO_FIELD_NUMBER = 3;
    private java.util.List<com.howbuy.wireless.entity.protobuf.HistoryFundNetValueChartProtos.NetValueInfo> netValueInfo_ =
      java.util.Collections.emptyList();
    public java.util.List<com.howbuy.wireless.entity.protobuf.HistoryFundNetValueChartProtos.NetValueInfo> getNetValueInfoList() {
      return netValueInfo_;
    }
    public int getNetValueInfoCount() { return netValueInfo_.size(); }
    public com.howbuy.wireless.entity.protobuf.HistoryFundNetValueChartProtos.NetValueInfo getNetValueInfo(int index) {
      return netValueInfo_.get(index);
    }
    
    // repeated .ShareInfo shareInfo = 4;
    public static final int SHAREINFO_FIELD_NUMBER = 4;
    private java.util.List<com.howbuy.wireless.entity.protobuf.HistoryFundNetValueChartProtos.ShareInfo> shareInfo_ =
      java.util.Collections.emptyList();
    public java.util.List<com.howbuy.wireless.entity.protobuf.HistoryFundNetValueChartProtos.ShareInfo> getShareInfoList() {
      return shareInfo_;
    }
    public int getShareInfoCount() { return shareInfo_.size(); }
    public com.howbuy.wireless.entity.protobuf.HistoryFundNetValueChartProtos.ShareInfo getShareInfo(int index) {
      return shareInfo_.get(index);
    }
    
    // repeated .PartitionInfo partitionInfo = 5;
    public static final int PARTITIONINFO_FIELD_NUMBER = 5;
    private java.util.List<com.howbuy.wireless.entity.protobuf.HistoryFundNetValueChartProtos.PartitionInfo> partitionInfo_ =
      java.util.Collections.emptyList();
    public java.util.List<com.howbuy.wireless.entity.protobuf.HistoryFundNetValueChartProtos.PartitionInfo> getPartitionInfoList() {
      return partitionInfo_;
    }
    public int getPartitionInfoCount() { return partitionInfo_.size(); }
    public com.howbuy.wireless.entity.protobuf.HistoryFundNetValueChartProtos.PartitionInfo getPartitionInfo(int index) {
      return partitionInfo_.get(index);
    }
    
    private void initFields() {
      common_ = com.howbuy.wireless.entity.protobuf.CommonProtos.Common.getDefaultInstance();
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasCommon()) {
        output.writeMessage(1, getCommon());
      }
      if (hasNow()) {
        output.writeString(2, getNow());
      }
      for (com.howbuy.wireless.entity.protobuf.HistoryFundNetValueChartProtos.NetValueInfo element : getNetValueInfoList()) {
        output.writeMessage(3, element);
      }
      for (com.howbuy.wireless.entity.protobuf.HistoryFundNetValueChartProtos.ShareInfo element : getShareInfoList()) {
        output.writeMessage(4, element);
      }
      for (com.howbuy.wireless.entity.protobuf.HistoryFundNetValueChartProtos.PartitionInfo element : getPartitionInfoList()) {
        output.writeMessage(5, element);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasCommon()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getCommon());
      }
      if (hasNow()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getNow());
      }
      for (com.howbuy.wireless.entity.protobuf.HistoryFundNetValueChartProtos.NetValueInfo element : getNetValueInfoList()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, element);
      }
      for (com.howbuy.wireless.entity.protobuf.HistoryFundNetValueChartProtos.ShareInfo element : getShareInfoList()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, element);
      }
      for (com.howbuy.wireless.entity.protobuf.HistoryFundNetValueChartProtos.PartitionInfo element : getPartitionInfoList()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, element);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.howbuy.wireless.entity.protobuf.HistoryFundNetValueChartProtos.HistoryFundNetValueChart parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.howbuy.wireless.entity.protobuf.HistoryFundNetValueChartProtos.HistoryFundNetValueChart parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.howbuy.wireless.entity.protobuf.HistoryFundNetValueChartProtos.HistoryFundNetValueChart parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.howbuy.wireless.entity.protobuf.HistoryFundNetValueChartProtos.HistoryFundNetValueChart parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.howbuy.wireless.entity.protobuf.HistoryFundNetValueChartProtos.HistoryFundNetValueChart parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.howbuy.wireless.entity.protobuf.HistoryFundNetValueChartProtos.HistoryFundNetValueChart parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.howbuy.wireless.entity.protobuf.HistoryFundNetValueChartProtos.HistoryFundNetValueChart parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.howbuy.wireless.entity.protobuf.HistoryFundNetValueChartProtos.HistoryFundNetValueChart parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.howbuy.wireless.entity.protobuf.HistoryFundNetValueChartProtos.HistoryFundNetValueChart parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.howbuy.wireless.entity.protobuf.HistoryFundNetValueChartProtos.HistoryFundNetValueChart parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.howbuy.wireless.entity.protobuf.HistoryFundNetValueChartProtos.HistoryFundNetValueChart prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.howbuy.wireless.entity.protobuf.HistoryFundNetValueChartProtos.HistoryFundNetValueChart result;
      
      // Construct using com.howbuy.wireless.entity.protobuf.HistoryFundNetValueChartProtos.HistoryFundNetValueChart.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.howbuy.wireless.entity.protobuf.HistoryFundNetValueChartProtos.HistoryFundNetValueChart();
        return builder;
      }
      
      protected com.howbuy.wireless.entity.protobuf.HistoryFundNetValueChartProtos.HistoryFundNetValueChart internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.howbuy.wireless.entity.protobuf.HistoryFundNetValueChartProtos.HistoryFundNetValueChart();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.howbuy.wireless.entity.protobuf.HistoryFundNetValueChartProtos.HistoryFundNetValueChart.getDescriptor();
      }
      
      public com.howbuy.wireless.entity.protobuf.HistoryFundNetValueChartProtos.HistoryFundNetValueChart getDefaultInstanceForType() {
        return com.howbuy.wireless.entity.protobuf.HistoryFundNetValueChartProtos.HistoryFundNetValueChart.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.howbuy.wireless.entity.protobuf.HistoryFundNetValueChartProtos.HistoryFundNetValueChart build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.howbuy.wireless.entity.protobuf.HistoryFundNetValueChartProtos.HistoryFundNetValueChart buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.howbuy.wireless.entity.protobuf.HistoryFundNetValueChartProtos.HistoryFundNetValueChart buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        if (result.netValueInfo_ != java.util.Collections.EMPTY_LIST) {
          result.netValueInfo_ =
            java.util.Collections.unmodifiableList(result.netValueInfo_);
        }
        if (result.shareInfo_ != java.util.Collections.EMPTY_LIST) {
          result.shareInfo_ =
            java.util.Collections.unmodifiableList(result.shareInfo_);
        }
        if (result.partitionInfo_ != java.util.Collections.EMPTY_LIST) {
          result.partitionInfo_ =
            java.util.Collections.unmodifiableList(result.partitionInfo_);
        }
        com.howbuy.wireless.entity.protobuf.HistoryFundNetValueChartProtos.HistoryFundNetValueChart returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.howbuy.wireless.entity.protobuf.HistoryFundNetValueChartProtos.HistoryFundNetValueChart) {
          return mergeFrom((com.howbuy.wireless.entity.protobuf.HistoryFundNetValueChartProtos.HistoryFundNetValueChart)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.howbuy.wireless.entity.protobuf.HistoryFundNetValueChartProtos.HistoryFundNetValueChart other) {
        if (other == com.howbuy.wireless.entity.protobuf.HistoryFundNetValueChartProtos.HistoryFundNetValueChart.getDefaultInstance()) return this;
        if (other.hasCommon()) {
          mergeCommon(other.getCommon());
        }
        if (other.hasNow()) {
          setNow(other.getNow());
        }
        if (!other.netValueInfo_.isEmpty()) {
          if (result.netValueInfo_.isEmpty()) {
            result.netValueInfo_ = new java.util.ArrayList<com.howbuy.wireless.entity.protobuf.HistoryFundNetValueChartProtos.NetValueInfo>();
          }
          result.netValueInfo_.addAll(other.netValueInfo_);
        }
        if (!other.shareInfo_.isEmpty()) {
          if (result.shareInfo_.isEmpty()) {
            result.shareInfo_ = new java.util.ArrayList<com.howbuy.wireless.entity.protobuf.HistoryFundNetValueChartProtos.ShareInfo>();
          }
          result.shareInfo_.addAll(other.shareInfo_);
        }
        if (!other.partitionInfo_.isEmpty()) {
          if (result.partitionInfo_.isEmpty()) {
            result.partitionInfo_ = new java.util.ArrayList<com.howbuy.wireless.entity.protobuf.HistoryFundNetValueChartProtos.PartitionInfo>();
          }
          result.partitionInfo_.addAll(other.partitionInfo_);
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              com.howbuy.wireless.entity.protobuf.CommonProtos.Common.Builder subBuilder = com.howbuy.wireless.entity.protobuf.CommonProtos.Common.newBuilder();
              if (hasCommon()) {
                subBuilder.mergeFrom(getCommon());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setCommon(subBuilder.buildPartial());
              break;
            }
            case 18: {
              setNow(input.readString());
              break;
            }
            case 26: {
              com.howbuy.wireless.entity.protobuf.HistoryFundNetValueChartProtos.NetValueInfo.Builder subBuilder = com.howbuy.wireless.entity.protobuf.HistoryFundNetValueChartProtos.NetValueInfo.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addNetValueInfo(subBuilder.buildPartial());
              break;
            }
            case 34: {
              com.howbuy.wireless.entity.protobuf.HistoryFundNetValueChartProtos.ShareInfo.Builder subBuilder = com.howbuy.wireless.entity.protobuf.HistoryFundNetValueChartProtos.ShareInfo.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addShareInfo(subBuilder.buildPartial());
              break;
            }
            case 42: {
              com.howbuy.wireless.entity.protobuf.HistoryFundNetValueChartProtos.PartitionInfo.Builder subBuilder = com.howbuy.wireless.entity.protobuf.HistoryFundNetValueChartProtos.PartitionInfo.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addPartitionInfo(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      
      // optional .common.Common common = 1;
      public boolean hasCommon() {
        return result.hasCommon();
      }
      public com.howbuy.wireless.entity.protobuf.CommonProtos.Common getCommon() {
        return result.getCommon();
      }
      public Builder setCommon(com.howbuy.wireless.entity.protobuf.CommonProtos.Common value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasCommon = true;
        result.common_ = value;
        return this;
      }
      public Builder setCommon(com.howbuy.wireless.entity.protobuf.CommonProtos.Common.Builder builderForValue) {
        result.hasCommon = true;
        result.common_ = builderForValue.build();
        return this;
      }
      public Builder mergeCommon(com.howbuy.wireless.entity.protobuf.CommonProtos.Common value) {
        if (result.hasCommon() &&
            result.common_ != com.howbuy.wireless.entity.protobuf.CommonProtos.Common.getDefaultInstance()) {
          result.common_ =
            com.howbuy.wireless.entity.protobuf.CommonProtos.Common.newBuilder(result.common_).mergeFrom(value).buildPartial();
        } else {
          result.common_ = value;
        }
        result.hasCommon = true;
        return this;
      }
      public Builder clearCommon() {
        result.hasCommon = false;
        result.common_ = com.howbuy.wireless.entity.protobuf.CommonProtos.Common.getDefaultInstance();
        return this;
      }
      
      // optional string now = 2;
      public boolean hasNow() {
        return result.hasNow();
      }
      public java.lang.String getNow() {
        return result.getNow();
      }
      public Builder setNow(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasNow = true;
        result.now_ = value;
        return this;
      }
      public Builder clearNow() {
        result.hasNow = false;
        result.now_ = getDefaultInstance().getNow();
        return this;
      }
      
      // repeated .NetValueInfo netValueInfo = 3;
      public java.util.List<com.howbuy.wireless.entity.protobuf.HistoryFundNetValueChartProtos.NetValueInfo> getNetValueInfoList() {
        return java.util.Collections.unmodifiableList(result.netValueInfo_);
      }
      public int getNetValueInfoCount() {
        return result.getNetValueInfoCount();
      }
      public com.howbuy.wireless.entity.protobuf.HistoryFundNetValueChartProtos.NetValueInfo getNetValueInfo(int index) {
        return result.getNetValueInfo(index);
      }
      public Builder setNetValueInfo(int index, com.howbuy.wireless.entity.protobuf.HistoryFundNetValueChartProtos.NetValueInfo value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.netValueInfo_.set(index, value);
        return this;
      }
      public Builder setNetValueInfo(int index, com.howbuy.wireless.entity.protobuf.HistoryFundNetValueChartProtos.NetValueInfo.Builder builderForValue) {
        result.netValueInfo_.set(index, builderForValue.build());
        return this;
      }
      public Builder addNetValueInfo(com.howbuy.wireless.entity.protobuf.HistoryFundNetValueChartProtos.NetValueInfo value) {
        if (value == null) {
          throw new NullPointerException();
        }
        if (result.netValueInfo_.isEmpty()) {
          result.netValueInfo_ = new java.util.ArrayList<com.howbuy.wireless.entity.protobuf.HistoryFundNetValueChartProtos.NetValueInfo>();
        }
        result.netValueInfo_.add(value);
        return this;
      }
      public Builder addNetValueInfo(com.howbuy.wireless.entity.protobuf.HistoryFundNetValueChartProtos.NetValueInfo.Builder builderForValue) {
        if (result.netValueInfo_.isEmpty()) {
          result.netValueInfo_ = new java.util.ArrayList<com.howbuy.wireless.entity.protobuf.HistoryFundNetValueChartProtos.NetValueInfo>();
        }
        result.netValueInfo_.add(builderForValue.build());
        return this;
      }
      public Builder addAllNetValueInfo(
          java.lang.Iterable<? extends com.howbuy.wireless.entity.protobuf.HistoryFundNetValueChartProtos.NetValueInfo> values) {
        if (result.netValueInfo_.isEmpty()) {
          result.netValueInfo_ = new java.util.ArrayList<com.howbuy.wireless.entity.protobuf.HistoryFundNetValueChartProtos.NetValueInfo>();
        }
        super.addAll(values, result.netValueInfo_);
        return this;
      }
      public Builder clearNetValueInfo() {
        result.netValueInfo_ = java.util.Collections.emptyList();
        return this;
      }
      
      // repeated .ShareInfo shareInfo = 4;
      public java.util.List<com.howbuy.wireless.entity.protobuf.HistoryFundNetValueChartProtos.ShareInfo> getShareInfoList() {
        return java.util.Collections.unmodifiableList(result.shareInfo_);
      }
      public int getShareInfoCount() {
        return result.getShareInfoCount();
      }
      public com.howbuy.wireless.entity.protobuf.HistoryFundNetValueChartProtos.ShareInfo getShareInfo(int index) {
        return result.getShareInfo(index);
      }
      public Builder setShareInfo(int index, com.howbuy.wireless.entity.protobuf.HistoryFundNetValueChartProtos.ShareInfo value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.shareInfo_.set(index, value);
        return this;
      }
      public Builder setShareInfo(int index, com.howbuy.wireless.entity.protobuf.HistoryFundNetValueChartProtos.ShareInfo.Builder builderForValue) {
        result.shareInfo_.set(index, builderForValue.build());
        return this;
      }
      public Builder addShareInfo(com.howbuy.wireless.entity.protobuf.HistoryFundNetValueChartProtos.ShareInfo value) {
        if (value == null) {
          throw new NullPointerException();
        }
        if (result.shareInfo_.isEmpty()) {
          result.shareInfo_ = new java.util.ArrayList<com.howbuy.wireless.entity.protobuf.HistoryFundNetValueChartProtos.ShareInfo>();
        }
        result.shareInfo_.add(value);
        return this;
      }
      public Builder addShareInfo(com.howbuy.wireless.entity.protobuf.HistoryFundNetValueChartProtos.ShareInfo.Builder builderForValue) {
        if (result.shareInfo_.isEmpty()) {
          result.shareInfo_ = new java.util.ArrayList<com.howbuy.wireless.entity.protobuf.HistoryFundNetValueChartProtos.ShareInfo>();
        }
        result.shareInfo_.add(builderForValue.build());
        return this;
      }
      public Builder addAllShareInfo(
          java.lang.Iterable<? extends com.howbuy.wireless.entity.protobuf.HistoryFundNetValueChartProtos.ShareInfo> values) {
        if (result.shareInfo_.isEmpty()) {
          result.shareInfo_ = new java.util.ArrayList<com.howbuy.wireless.entity.protobuf.HistoryFundNetValueChartProtos.ShareInfo>();
        }
        super.addAll(values, result.shareInfo_);
        return this;
      }
      public Builder clearShareInfo() {
        result.shareInfo_ = java.util.Collections.emptyList();
        return this;
      }
      
      // repeated .PartitionInfo partitionInfo = 5;
      public java.util.List<com.howbuy.wireless.entity.protobuf.HistoryFundNetValueChartProtos.PartitionInfo> getPartitionInfoList() {
        return java.util.Collections.unmodifiableList(result.partitionInfo_);
      }
      public int getPartitionInfoCount() {
        return result.getPartitionInfoCount();
      }
      public com.howbuy.wireless.entity.protobuf.HistoryFundNetValueChartProtos.PartitionInfo getPartitionInfo(int index) {
        return result.getPartitionInfo(index);
      }
      public Builder setPartitionInfo(int index, com.howbuy.wireless.entity.protobuf.HistoryFundNetValueChartProtos.PartitionInfo value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.partitionInfo_.set(index, value);
        return this;
      }
      public Builder setPartitionInfo(int index, com.howbuy.wireless.entity.protobuf.HistoryFundNetValueChartProtos.PartitionInfo.Builder builderForValue) {
        result.partitionInfo_.set(index, builderForValue.build());
        return this;
      }
      public Builder addPartitionInfo(com.howbuy.wireless.entity.protobuf.HistoryFundNetValueChartProtos.PartitionInfo value) {
        if (value == null) {
          throw new NullPointerException();
        }
        if (result.partitionInfo_.isEmpty()) {
          result.partitionInfo_ = new java.util.ArrayList<com.howbuy.wireless.entity.protobuf.HistoryFundNetValueChartProtos.PartitionInfo>();
        }
        result.partitionInfo_.add(value);
        return this;
      }
      public Builder addPartitionInfo(com.howbuy.wireless.entity.protobuf.HistoryFundNetValueChartProtos.PartitionInfo.Builder builderForValue) {
        if (result.partitionInfo_.isEmpty()) {
          result.partitionInfo_ = new java.util.ArrayList<com.howbuy.wireless.entity.protobuf.HistoryFundNetValueChartProtos.PartitionInfo>();
        }
        result.partitionInfo_.add(builderForValue.build());
        return this;
      }
      public Builder addAllPartitionInfo(
          java.lang.Iterable<? extends com.howbuy.wireless.entity.protobuf.HistoryFundNetValueChartProtos.PartitionInfo> values) {
        if (result.partitionInfo_.isEmpty()) {
          result.partitionInfo_ = new java.util.ArrayList<com.howbuy.wireless.entity.protobuf.HistoryFundNetValueChartProtos.PartitionInfo>();
        }
        super.addAll(values, result.partitionInfo_);
        return this;
      }
      public Builder clearPartitionInfo() {
        result.partitionInfo_ = java.util.Collections.emptyList();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:HistoryFundNetValueChart)
    }
    
    static {
      defaultInstance = new HistoryFundNetValueChart(true);
      com.howbuy.wireless.entity.protobuf.HistoryFundNetValueChartProtos.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:HistoryFundNetValueChart)
  }
  
  public static final class NetValueInfo extends
      com.google.protobuf.GeneratedMessage {
    // Use NetValueInfo.newBuilder() to construct.
    private NetValueInfo() {
      initFields();
    }
    private NetValueInfo(boolean noInit) {}
    
    private static final NetValueInfo defaultInstance;
    public static NetValueInfo getDefaultInstance() {
      return defaultInstance;
    }
    
    public NetValueInfo getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.howbuy.wireless.entity.protobuf.HistoryFundNetValueChartProtos.internal_static_NetValueInfo_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.howbuy.wireless.entity.protobuf.HistoryFundNetValueChartProtos.internal_static_NetValueInfo_fieldAccessorTable;
    }
    
    // optional string jzrq = 1;
    public static final int JZRQ_FIELD_NUMBER = 1;
    private boolean hasJzrq;
    private java.lang.String jzrq_ = "";
    public boolean hasJzrq() { return hasJzrq; }
    public java.lang.String getJzrq() { return jzrq_; }
    
    // optional string jjjz = 2;
    public static final int JJJZ_FIELD_NUMBER = 2;
    private boolean hasJjjz;
    private java.lang.String jjjz_ = "";
    public boolean hasJjjz() { return hasJjjz; }
    public java.lang.String getJjjz() { return jjjz_; }
    
    // optional string hbxx = 3;
    public static final int HBXX_FIELD_NUMBER = 3;
    private boolean hasHbxx;
    private java.lang.String hbxx_ = "";
    public boolean hasHbxx() { return hasHbxx; }
    public java.lang.String getHbxx() { return hbxx_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasJzrq()) {
        output.writeString(1, getJzrq());
      }
      if (hasJjjz()) {
        output.writeString(2, getJjjz());
      }
      if (hasHbxx()) {
        output.writeString(3, getHbxx());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasJzrq()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getJzrq());
      }
      if (hasJjjz()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getJjjz());
      }
      if (hasHbxx()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(3, getHbxx());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.howbuy.wireless.entity.protobuf.HistoryFundNetValueChartProtos.NetValueInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.howbuy.wireless.entity.protobuf.HistoryFundNetValueChartProtos.NetValueInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.howbuy.wireless.entity.protobuf.HistoryFundNetValueChartProtos.NetValueInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.howbuy.wireless.entity.protobuf.HistoryFundNetValueChartProtos.NetValueInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.howbuy.wireless.entity.protobuf.HistoryFundNetValueChartProtos.NetValueInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.howbuy.wireless.entity.protobuf.HistoryFundNetValueChartProtos.NetValueInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.howbuy.wireless.entity.protobuf.HistoryFundNetValueChartProtos.NetValueInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.howbuy.wireless.entity.protobuf.HistoryFundNetValueChartProtos.NetValueInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.howbuy.wireless.entity.protobuf.HistoryFundNetValueChartProtos.NetValueInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.howbuy.wireless.entity.protobuf.HistoryFundNetValueChartProtos.NetValueInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.howbuy.wireless.entity.protobuf.HistoryFundNetValueChartProtos.NetValueInfo prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.howbuy.wireless.entity.protobuf.HistoryFundNetValueChartProtos.NetValueInfo result;
      
      // Construct using com.howbuy.wireless.entity.protobuf.HistoryFundNetValueChartProtos.NetValueInfo.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.howbuy.wireless.entity.protobuf.HistoryFundNetValueChartProtos.NetValueInfo();
        return builder;
      }
      
      protected com.howbuy.wireless.entity.protobuf.HistoryFundNetValueChartProtos.NetValueInfo internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.howbuy.wireless.entity.protobuf.HistoryFundNetValueChartProtos.NetValueInfo();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.howbuy.wireless.entity.protobuf.HistoryFundNetValueChartProtos.NetValueInfo.getDescriptor();
      }
      
      public com.howbuy.wireless.entity.protobuf.HistoryFundNetValueChartProtos.NetValueInfo getDefaultInstanceForType() {
        return com.howbuy.wireless.entity.protobuf.HistoryFundNetValueChartProtos.NetValueInfo.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.howbuy.wireless.entity.protobuf.HistoryFundNetValueChartProtos.NetValueInfo build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.howbuy.wireless.entity.protobuf.HistoryFundNetValueChartProtos.NetValueInfo buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.howbuy.wireless.entity.protobuf.HistoryFundNetValueChartProtos.NetValueInfo buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.howbuy.wireless.entity.protobuf.HistoryFundNetValueChartProtos.NetValueInfo returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.howbuy.wireless.entity.protobuf.HistoryFundNetValueChartProtos.NetValueInfo) {
          return mergeFrom((com.howbuy.wireless.entity.protobuf.HistoryFundNetValueChartProtos.NetValueInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.howbuy.wireless.entity.protobuf.HistoryFundNetValueChartProtos.NetValueInfo other) {
        if (other == com.howbuy.wireless.entity.protobuf.HistoryFundNetValueChartProtos.NetValueInfo.getDefaultInstance()) return this;
        if (other.hasJzrq()) {
          setJzrq(other.getJzrq());
        }
        if (other.hasJjjz()) {
          setJjjz(other.getJjjz());
        }
        if (other.hasHbxx()) {
          setHbxx(other.getHbxx());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              setJzrq(input.readString());
              break;
            }
            case 18: {
              setJjjz(input.readString());
              break;
            }
            case 26: {
              setHbxx(input.readString());
              break;
            }
          }
        }
      }
      
      
      // optional string jzrq = 1;
      public boolean hasJzrq() {
        return result.hasJzrq();
      }
      public java.lang.String getJzrq() {
        return result.getJzrq();
      }
      public Builder setJzrq(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasJzrq = true;
        result.jzrq_ = value;
        return this;
      }
      public Builder clearJzrq() {
        result.hasJzrq = false;
        result.jzrq_ = getDefaultInstance().getJzrq();
        return this;
      }
      
      // optional string jjjz = 2;
      public boolean hasJjjz() {
        return result.hasJjjz();
      }
      public java.lang.String getJjjz() {
        return result.getJjjz();
      }
      public Builder setJjjz(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasJjjz = true;
        result.jjjz_ = value;
        return this;
      }
      public Builder clearJjjz() {
        result.hasJjjz = false;
        result.jjjz_ = getDefaultInstance().getJjjz();
        return this;
      }
      
      // optional string hbxx = 3;
      public boolean hasHbxx() {
        return result.hasHbxx();
      }
      public java.lang.String getHbxx() {
        return result.getHbxx();
      }
      public Builder setHbxx(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasHbxx = true;
        result.hbxx_ = value;
        return this;
      }
      public Builder clearHbxx() {
        result.hasHbxx = false;
        result.hbxx_ = getDefaultInstance().getHbxx();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:NetValueInfo)
    }
    
    static {
      defaultInstance = new NetValueInfo(true);
      com.howbuy.wireless.entity.protobuf.HistoryFundNetValueChartProtos.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:NetValueInfo)
  }
  
  public static final class ShareInfo extends
      com.google.protobuf.GeneratedMessage {
    // Use ShareInfo.newBuilder() to construct.
    private ShareInfo() {
      initFields();
    }
    private ShareInfo(boolean noInit) {}
    
    private static final ShareInfo defaultInstance;
    public static ShareInfo getDefaultInstance() {
      return defaultInstance;
    }
    
    public ShareInfo getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.howbuy.wireless.entity.protobuf.HistoryFundNetValueChartProtos.internal_static_ShareInfo_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.howbuy.wireless.entity.protobuf.HistoryFundNetValueChartProtos.internal_static_ShareInfo_fieldAccessorTable;
    }
    
    // optional string fhrq = 1;
    public static final int FHRQ_FIELD_NUMBER = 1;
    private boolean hasFhrq;
    private java.lang.String fhrq_ = "";
    public boolean hasFhrq() { return hasFhrq; }
    public java.lang.String getFhrq() { return fhrq_; }
    
    // optional string dwfh = 2;
    public static final int DWFH_FIELD_NUMBER = 2;
    private boolean hasDwfh;
    private java.lang.String dwfh_ = "";
    public boolean hasDwfh() { return hasDwfh; }
    public java.lang.String getDwfh() { return dwfh_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasFhrq()) {
        output.writeString(1, getFhrq());
      }
      if (hasDwfh()) {
        output.writeString(2, getDwfh());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasFhrq()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getFhrq());
      }
      if (hasDwfh()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getDwfh());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.howbuy.wireless.entity.protobuf.HistoryFundNetValueChartProtos.ShareInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.howbuy.wireless.entity.protobuf.HistoryFundNetValueChartProtos.ShareInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.howbuy.wireless.entity.protobuf.HistoryFundNetValueChartProtos.ShareInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.howbuy.wireless.entity.protobuf.HistoryFundNetValueChartProtos.ShareInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.howbuy.wireless.entity.protobuf.HistoryFundNetValueChartProtos.ShareInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.howbuy.wireless.entity.protobuf.HistoryFundNetValueChartProtos.ShareInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.howbuy.wireless.entity.protobuf.HistoryFundNetValueChartProtos.ShareInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.howbuy.wireless.entity.protobuf.HistoryFundNetValueChartProtos.ShareInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.howbuy.wireless.entity.protobuf.HistoryFundNetValueChartProtos.ShareInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.howbuy.wireless.entity.protobuf.HistoryFundNetValueChartProtos.ShareInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.howbuy.wireless.entity.protobuf.HistoryFundNetValueChartProtos.ShareInfo prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.howbuy.wireless.entity.protobuf.HistoryFundNetValueChartProtos.ShareInfo result;
      
      // Construct using com.howbuy.wireless.entity.protobuf.HistoryFundNetValueChartProtos.ShareInfo.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.howbuy.wireless.entity.protobuf.HistoryFundNetValueChartProtos.ShareInfo();
        return builder;
      }
      
      protected com.howbuy.wireless.entity.protobuf.HistoryFundNetValueChartProtos.ShareInfo internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.howbuy.wireless.entity.protobuf.HistoryFundNetValueChartProtos.ShareInfo();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.howbuy.wireless.entity.protobuf.HistoryFundNetValueChartProtos.ShareInfo.getDescriptor();
      }
      
      public com.howbuy.wireless.entity.protobuf.HistoryFundNetValueChartProtos.ShareInfo getDefaultInstanceForType() {
        return com.howbuy.wireless.entity.protobuf.HistoryFundNetValueChartProtos.ShareInfo.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.howbuy.wireless.entity.protobuf.HistoryFundNetValueChartProtos.ShareInfo build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.howbuy.wireless.entity.protobuf.HistoryFundNetValueChartProtos.ShareInfo buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.howbuy.wireless.entity.protobuf.HistoryFundNetValueChartProtos.ShareInfo buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.howbuy.wireless.entity.protobuf.HistoryFundNetValueChartProtos.ShareInfo returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.howbuy.wireless.entity.protobuf.HistoryFundNetValueChartProtos.ShareInfo) {
          return mergeFrom((com.howbuy.wireless.entity.protobuf.HistoryFundNetValueChartProtos.ShareInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.howbuy.wireless.entity.protobuf.HistoryFundNetValueChartProtos.ShareInfo other) {
        if (other == com.howbuy.wireless.entity.protobuf.HistoryFundNetValueChartProtos.ShareInfo.getDefaultInstance()) return this;
        if (other.hasFhrq()) {
          setFhrq(other.getFhrq());
        }
        if (other.hasDwfh()) {
          setDwfh(other.getDwfh());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              setFhrq(input.readString());
              break;
            }
            case 18: {
              setDwfh(input.readString());
              break;
            }
          }
        }
      }
      
      
      // optional string fhrq = 1;
      public boolean hasFhrq() {
        return result.hasFhrq();
      }
      public java.lang.String getFhrq() {
        return result.getFhrq();
      }
      public Builder setFhrq(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasFhrq = true;
        result.fhrq_ = value;
        return this;
      }
      public Builder clearFhrq() {
        result.hasFhrq = false;
        result.fhrq_ = getDefaultInstance().getFhrq();
        return this;
      }
      
      // optional string dwfh = 2;
      public boolean hasDwfh() {
        return result.hasDwfh();
      }
      public java.lang.String getDwfh() {
        return result.getDwfh();
      }
      public Builder setDwfh(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasDwfh = true;
        result.dwfh_ = value;
        return this;
      }
      public Builder clearDwfh() {
        result.hasDwfh = false;
        result.dwfh_ = getDefaultInstance().getDwfh();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:ShareInfo)
    }
    
    static {
      defaultInstance = new ShareInfo(true);
      com.howbuy.wireless.entity.protobuf.HistoryFundNetValueChartProtos.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:ShareInfo)
  }
  
  public static final class PartitionInfo extends
      com.google.protobuf.GeneratedMessage {
    // Use PartitionInfo.newBuilder() to construct.
    private PartitionInfo() {
      initFields();
    }
    private PartitionInfo(boolean noInit) {}
    
    private static final PartitionInfo defaultInstance;
    public static PartitionInfo getDefaultInstance() {
      return defaultInstance;
    }
    
    public PartitionInfo getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.howbuy.wireless.entity.protobuf.HistoryFundNetValueChartProtos.internal_static_PartitionInfo_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.howbuy.wireless.entity.protobuf.HistoryFundNetValueChartProtos.internal_static_PartitionInfo_fieldAccessorTable;
    }
    
    // optional string fcrq = 1;
    public static final int FCRQ_FIELD_NUMBER = 1;
    private boolean hasFcrq;
    private java.lang.String fcrq_ = "";
    public boolean hasFcrq() { return hasFcrq; }
    public java.lang.String getFcrq() { return fcrq_; }
    
    // optional string fcbl = 2;
    public static final int FCBL_FIELD_NUMBER = 2;
    private boolean hasFcbl;
    private java.lang.String fcbl_ = "";
    public boolean hasFcbl() { return hasFcbl; }
    public java.lang.String getFcbl() { return fcbl_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasFcrq()) {
        output.writeString(1, getFcrq());
      }
      if (hasFcbl()) {
        output.writeString(2, getFcbl());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasFcrq()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getFcrq());
      }
      if (hasFcbl()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getFcbl());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.howbuy.wireless.entity.protobuf.HistoryFundNetValueChartProtos.PartitionInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.howbuy.wireless.entity.protobuf.HistoryFundNetValueChartProtos.PartitionInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.howbuy.wireless.entity.protobuf.HistoryFundNetValueChartProtos.PartitionInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.howbuy.wireless.entity.protobuf.HistoryFundNetValueChartProtos.PartitionInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.howbuy.wireless.entity.protobuf.HistoryFundNetValueChartProtos.PartitionInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.howbuy.wireless.entity.protobuf.HistoryFundNetValueChartProtos.PartitionInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.howbuy.wireless.entity.protobuf.HistoryFundNetValueChartProtos.PartitionInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.howbuy.wireless.entity.protobuf.HistoryFundNetValueChartProtos.PartitionInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.howbuy.wireless.entity.protobuf.HistoryFundNetValueChartProtos.PartitionInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.howbuy.wireless.entity.protobuf.HistoryFundNetValueChartProtos.PartitionInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.howbuy.wireless.entity.protobuf.HistoryFundNetValueChartProtos.PartitionInfo prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.howbuy.wireless.entity.protobuf.HistoryFundNetValueChartProtos.PartitionInfo result;
      
      // Construct using com.howbuy.wireless.entity.protobuf.HistoryFundNetValueChartProtos.PartitionInfo.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.howbuy.wireless.entity.protobuf.HistoryFundNetValueChartProtos.PartitionInfo();
        return builder;
      }
      
      protected com.howbuy.wireless.entity.protobuf.HistoryFundNetValueChartProtos.PartitionInfo internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.howbuy.wireless.entity.protobuf.HistoryFundNetValueChartProtos.PartitionInfo();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.howbuy.wireless.entity.protobuf.HistoryFundNetValueChartProtos.PartitionInfo.getDescriptor();
      }
      
      public com.howbuy.wireless.entity.protobuf.HistoryFundNetValueChartProtos.PartitionInfo getDefaultInstanceForType() {
        return com.howbuy.wireless.entity.protobuf.HistoryFundNetValueChartProtos.PartitionInfo.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.howbuy.wireless.entity.protobuf.HistoryFundNetValueChartProtos.PartitionInfo build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.howbuy.wireless.entity.protobuf.HistoryFundNetValueChartProtos.PartitionInfo buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.howbuy.wireless.entity.protobuf.HistoryFundNetValueChartProtos.PartitionInfo buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.howbuy.wireless.entity.protobuf.HistoryFundNetValueChartProtos.PartitionInfo returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.howbuy.wireless.entity.protobuf.HistoryFundNetValueChartProtos.PartitionInfo) {
          return mergeFrom((com.howbuy.wireless.entity.protobuf.HistoryFundNetValueChartProtos.PartitionInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.howbuy.wireless.entity.protobuf.HistoryFundNetValueChartProtos.PartitionInfo other) {
        if (other == com.howbuy.wireless.entity.protobuf.HistoryFundNetValueChartProtos.PartitionInfo.getDefaultInstance()) return this;
        if (other.hasFcrq()) {
          setFcrq(other.getFcrq());
        }
        if (other.hasFcbl()) {
          setFcbl(other.getFcbl());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              setFcrq(input.readString());
              break;
            }
            case 18: {
              setFcbl(input.readString());
              break;
            }
          }
        }
      }
      
      
      // optional string fcrq = 1;
      public boolean hasFcrq() {
        return result.hasFcrq();
      }
      public java.lang.String getFcrq() {
        return result.getFcrq();
      }
      public Builder setFcrq(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasFcrq = true;
        result.fcrq_ = value;
        return this;
      }
      public Builder clearFcrq() {
        result.hasFcrq = false;
        result.fcrq_ = getDefaultInstance().getFcrq();
        return this;
      }
      
      // optional string fcbl = 2;
      public boolean hasFcbl() {
        return result.hasFcbl();
      }
      public java.lang.String getFcbl() {
        return result.getFcbl();
      }
      public Builder setFcbl(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasFcbl = true;
        result.fcbl_ = value;
        return this;
      }
      public Builder clearFcbl() {
        result.hasFcbl = false;
        result.fcbl_ = getDefaultInstance().getFcbl();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:PartitionInfo)
    }
    
    static {
      defaultInstance = new PartitionInfo(true);
      com.howbuy.wireless.entity.protobuf.HistoryFundNetValueChartProtos.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:PartitionInfo)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_HistoryFundNetValueChart_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_HistoryFundNetValueChart_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_NetValueInfo_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_NetValueInfo_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ShareInfo_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ShareInfo_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_PartitionInfo_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_PartitionInfo_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\036historyFundNetValueChart.proto\032\014common" +
      ".proto\"\262\001\n\030HistoryFundNetValueChart\022\036\n\006c" +
      "ommon\030\001 \001(\0132\016.common.Common\022\013\n\003now\030\002 \001(\t" +
      "\022#\n\014netValueInfo\030\003 \003(\0132\r.NetValueInfo\022\035\n" +
      "\tshareInfo\030\004 \003(\0132\n.ShareInfo\022%\n\rpartitio" +
      "nInfo\030\005 \003(\0132\016.PartitionInfo\"8\n\014NetValueI" +
      "nfo\022\014\n\004jzrq\030\001 \001(\t\022\014\n\004jjjz\030\002 \001(\t\022\014\n\004hbxx\030" +
      "\003 \001(\t\"\'\n\tShareInfo\022\014\n\004fhrq\030\001 \001(\t\022\014\n\004dwfh" +
      "\030\002 \001(\t\"+\n\rPartitionInfo\022\014\n\004fcrq\030\001 \001(\t\022\014\n" +
      "\004fcbl\030\002 \001(\tBE\n#com.howbuy.wireless.entit",
      "y.protobufB\036HistoryFundNetValueChartProt" +
      "os"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_HistoryFundNetValueChart_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_HistoryFundNetValueChart_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_HistoryFundNetValueChart_descriptor,
              new java.lang.String[] { "Common", "Now", "NetValueInfo", "ShareInfo", "PartitionInfo", },
              com.howbuy.wireless.entity.protobuf.HistoryFundNetValueChartProtos.HistoryFundNetValueChart.class,
              com.howbuy.wireless.entity.protobuf.HistoryFundNetValueChartProtos.HistoryFundNetValueChart.Builder.class);
          internal_static_NetValueInfo_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_NetValueInfo_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_NetValueInfo_descriptor,
              new java.lang.String[] { "Jzrq", "Jjjz", "Hbxx", },
              com.howbuy.wireless.entity.protobuf.HistoryFundNetValueChartProtos.NetValueInfo.class,
              com.howbuy.wireless.entity.protobuf.HistoryFundNetValueChartProtos.NetValueInfo.Builder.class);
          internal_static_ShareInfo_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_ShareInfo_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ShareInfo_descriptor,
              new java.lang.String[] { "Fhrq", "Dwfh", },
              com.howbuy.wireless.entity.protobuf.HistoryFundNetValueChartProtos.ShareInfo.class,
              com.howbuy.wireless.entity.protobuf.HistoryFundNetValueChartProtos.ShareInfo.Builder.class);
          internal_static_PartitionInfo_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_PartitionInfo_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_PartitionInfo_descriptor,
              new java.lang.String[] { "Fcrq", "Fcbl", },
              com.howbuy.wireless.entity.protobuf.HistoryFundNetValueChartProtos.PartitionInfo.class,
              com.howbuy.wireless.entity.protobuf.HistoryFundNetValueChartProtos.PartitionInfo.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.howbuy.wireless.entity.protobuf.CommonProtos.getDescriptor(),
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
