// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hostDistribution.proto

package com.howbuy.wireless.entity.protobuf;

public final class HostDistributionProtos {
  private HostDistributionProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class HostDistribution extends
      com.google.protobuf.GeneratedMessage {
    // Use HostDistribution.newBuilder() to construct.
    private HostDistribution() {
      initFields();
    }
    private HostDistribution(boolean noInit) {}
    
    private static final HostDistribution defaultInstance;
    public static HostDistribution getDefaultInstance() {
      return defaultInstance;
    }
    
    public HostDistribution getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.howbuy.wireless.entity.protobuf.HostDistributionProtos.internal_static_HostDistribution_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.howbuy.wireless.entity.protobuf.HostDistributionProtos.internal_static_HostDistribution_fieldAccessorTable;
    }
    
    // optional string versionNeedUpdate = 4;
    public static final int VERSIONNEEDUPDATE_FIELD_NUMBER = 4;
    private boolean hasVersionNeedUpdate;
    private java.lang.String versionNeedUpdate_ = "";
    public boolean hasVersionNeedUpdate() { return hasVersionNeedUpdate; }
    public java.lang.String getVersionNeedUpdate() { return versionNeedUpdate_; }
    
    // optional string updateUrl = 5;
    public static final int UPDATEURL_FIELD_NUMBER = 5;
    private boolean hasUpdateUrl;
    private java.lang.String updateUrl_ = "";
    public boolean hasUpdateUrl() { return hasUpdateUrl; }
    public java.lang.String getUpdateUrl() { return updateUrl_; }
    
    // optional fixed64 serverTime = 6;
    public static final int SERVERTIME_FIELD_NUMBER = 6;
    private boolean hasServerTime;
    private long serverTime_ = 0L;
    public boolean hasServerTime() { return hasServerTime; }
    public long getServerTime() { return serverTime_; }
    
    // optional string basicInfoNeedUpdate = 8;
    public static final int BASICINFONEEDUPDATE_FIELD_NUMBER = 8;
    private boolean hasBasicInfoNeedUpdate;
    private java.lang.String basicInfoNeedUpdate_ = "";
    public boolean hasBasicInfoNeedUpdate() { return hasBasicInfoNeedUpdate; }
    public java.lang.String getBasicInfoNeedUpdate() { return basicInfoNeedUpdate_; }
    
    // optional string managerNeedUpdate = 9;
    public static final int MANAGERNEEDUPDATE_FIELD_NUMBER = 9;
    private boolean hasManagerNeedUpdate;
    private java.lang.String managerNeedUpdate_ = "";
    public boolean hasManagerNeedUpdate() { return hasManagerNeedUpdate; }
    public java.lang.String getManagerNeedUpdate() { return managerNeedUpdate_; }
    
    // optional string companyNeedUpdate = 10;
    public static final int COMPANYNEEDUPDATE_FIELD_NUMBER = 10;
    private boolean hasCompanyNeedUpdate;
    private java.lang.String companyNeedUpdate_ = "";
    public boolean hasCompanyNeedUpdate() { return hasCompanyNeedUpdate; }
    public java.lang.String getCompanyNeedUpdate() { return companyNeedUpdate_; }
    
    // optional string newsTypeNeedUpdate = 11;
    public static final int NEWSTYPENEEDUPDATE_FIELD_NUMBER = 11;
    private boolean hasNewsTypeNeedUpdate;
    private java.lang.String newsTypeNeedUpdate_ = "";
    public boolean hasNewsTypeNeedUpdate() { return hasNewsTypeNeedUpdate; }
    public java.lang.String getNewsTypeNeedUpdate() { return newsTypeNeedUpdate_; }
    
    // optional string opinionTypeNeedUpdate = 12;
    public static final int OPINIONTYPENEEDUPDATE_FIELD_NUMBER = 12;
    private boolean hasOpinionTypeNeedUpdate;
    private java.lang.String opinionTypeNeedUpdate_ = "";
    public boolean hasOpinionTypeNeedUpdate() { return hasOpinionTypeNeedUpdate; }
    public java.lang.String getOpinionTypeNeedUpdate() { return opinionTypeNeedUpdate_; }
    
    // optional .common.Common common = 13;
    public static final int COMMON_FIELD_NUMBER = 13;
    private boolean hasCommon;
    private com.howbuy.wireless.entity.protobuf.CommonProtos.Common common_;
    public boolean hasCommon() { return hasCommon; }
    public com.howbuy.wireless.entity.protobuf.CommonProtos.Common getCommon() { return common_; }
    
    // repeated .common.PhoneNewsType phoneNewsType = 14;
    public static final int PHONENEWSTYPE_FIELD_NUMBER = 14;
    private java.util.List<com.howbuy.wireless.entity.protobuf.PhoneNewsTypeProtos.PhoneNewsType> phoneNewsType_ =
      java.util.Collections.emptyList();
    public java.util.List<com.howbuy.wireless.entity.protobuf.PhoneNewsTypeProtos.PhoneNewsType> getPhoneNewsTypeList() {
      return phoneNewsType_;
    }
    public int getPhoneNewsTypeCount() { return phoneNewsType_.size(); }
    public com.howbuy.wireless.entity.protobuf.PhoneNewsTypeProtos.PhoneNewsType getPhoneNewsType(int index) {
      return phoneNewsType_.get(index);
    }
    
    // repeated .common.PhoneOpinionType phoneOpinionType = 15;
    public static final int PHONEOPINIONTYPE_FIELD_NUMBER = 15;
    private java.util.List<com.howbuy.wireless.entity.protobuf.PhoneOpinionTypeProtos.PhoneOpinionType> phoneOpinionType_ =
      java.util.Collections.emptyList();
    public java.util.List<com.howbuy.wireless.entity.protobuf.PhoneOpinionTypeProtos.PhoneOpinionType> getPhoneOpinionTypeList() {
      return phoneOpinionType_;
    }
    public int getPhoneOpinionTypeCount() { return phoneOpinionType_.size(); }
    public com.howbuy.wireless.entity.protobuf.PhoneOpinionTypeProtos.PhoneOpinionType getPhoneOpinionType(int index) {
      return phoneOpinionType_.get(index);
    }
    
    // optional string kfsNeedUpdate = 16;
    public static final int KFSNEEDUPDATE_FIELD_NUMBER = 16;
    private boolean hasKfsNeedUpdate;
    private java.lang.String kfsNeedUpdate_ = "";
    public boolean hasKfsNeedUpdate() { return hasKfsNeedUpdate; }
    public java.lang.String getKfsNeedUpdate() { return kfsNeedUpdate_; }
    
    // optional string fbsNeedUpdate = 17;
    public static final int FBSNEEDUPDATE_FIELD_NUMBER = 17;
    private boolean hasFbsNeedUpdate;
    private java.lang.String fbsNeedUpdate_ = "";
    public boolean hasFbsNeedUpdate() { return hasFbsNeedUpdate; }
    public java.lang.String getFbsNeedUpdate() { return fbsNeedUpdate_; }
    
    // optional string hbsNeedUpdate = 18;
    public static final int HBSNEEDUPDATE_FIELD_NUMBER = 18;
    private boolean hasHbsNeedUpdate;
    private java.lang.String hbsNeedUpdate_ = "";
    public boolean hasHbsNeedUpdate() { return hasHbsNeedUpdate; }
    public java.lang.String getHbsNeedUpdate() { return hbsNeedUpdate_; }
    
    // optional string smNeedUpdate = 19;
    public static final int SMNEEDUPDATE_FIELD_NUMBER = 19;
    private boolean hasSmNeedUpdate;
    private java.lang.String smNeedUpdate_ = "";
    public boolean hasSmNeedUpdate() { return hasSmNeedUpdate; }
    public java.lang.String getSmNeedUpdate() { return smNeedUpdate_; }
    
    // optional string dtNeedUpdate = 20;
    public static final int DTNEEDUPDATE_FIELD_NUMBER = 20;
    private boolean hasDtNeedUpdate;
    private java.lang.String dtNeedUpdate_ = "";
    public boolean hasDtNeedUpdate() { return hasDtNeedUpdate; }
    public java.lang.String getDtNeedUpdate() { return dtNeedUpdate_; }
    
    // optional string updateDesc = 21;
    public static final int UPDATEDESC_FIELD_NUMBER = 21;
    private boolean hasUpdateDesc;
    private java.lang.String updateDesc_ = "";
    public boolean hasUpdateDesc() { return hasUpdateDesc; }
    public java.lang.String getUpdateDesc() { return updateDesc_; }
    
    // optional string newJsVer = 22;
    public static final int NEWJSVER_FIELD_NUMBER = 22;
    private boolean hasNewJsVer;
    private java.lang.String newJsVer_ = "";
    public boolean hasNewJsVer() { return hasNewJsVer; }
    public java.lang.String getNewJsVer() { return newJsVer_; }
    
    // optional string jsUrl = 23;
    public static final int JSURL_FIELD_NUMBER = 23;
    private boolean hasJsUrl;
    private java.lang.String jsUrl_ = "";
    public boolean hasJsUrl() { return hasJsUrl; }
    public java.lang.String getJsUrl() { return jsUrl_; }
    
    private void initFields() {
      common_ = com.howbuy.wireless.entity.protobuf.CommonProtos.Common.getDefaultInstance();
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasVersionNeedUpdate()) {
        output.writeString(4, getVersionNeedUpdate());
      }
      if (hasUpdateUrl()) {
        output.writeString(5, getUpdateUrl());
      }
      if (hasServerTime()) {
        output.writeFixed64(6, getServerTime());
      }
      if (hasBasicInfoNeedUpdate()) {
        output.writeString(8, getBasicInfoNeedUpdate());
      }
      if (hasManagerNeedUpdate()) {
        output.writeString(9, getManagerNeedUpdate());
      }
      if (hasCompanyNeedUpdate()) {
        output.writeString(10, getCompanyNeedUpdate());
      }
      if (hasNewsTypeNeedUpdate()) {
        output.writeString(11, getNewsTypeNeedUpdate());
      }
      if (hasOpinionTypeNeedUpdate()) {
        output.writeString(12, getOpinionTypeNeedUpdate());
      }
      if (hasCommon()) {
        output.writeMessage(13, getCommon());
      }
      for (com.howbuy.wireless.entity.protobuf.PhoneNewsTypeProtos.PhoneNewsType element : getPhoneNewsTypeList()) {
        output.writeMessage(14, element);
      }
      for (com.howbuy.wireless.entity.protobuf.PhoneOpinionTypeProtos.PhoneOpinionType element : getPhoneOpinionTypeList()) {
        output.writeMessage(15, element);
      }
      if (hasKfsNeedUpdate()) {
        output.writeString(16, getKfsNeedUpdate());
      }
      if (hasFbsNeedUpdate()) {
        output.writeString(17, getFbsNeedUpdate());
      }
      if (hasHbsNeedUpdate()) {
        output.writeString(18, getHbsNeedUpdate());
      }
      if (hasSmNeedUpdate()) {
        output.writeString(19, getSmNeedUpdate());
      }
      if (hasDtNeedUpdate()) {
        output.writeString(20, getDtNeedUpdate());
      }
      if (hasUpdateDesc()) {
        output.writeString(21, getUpdateDesc());
      }
      if (hasNewJsVer()) {
        output.writeString(22, getNewJsVer());
      }
      if (hasJsUrl()) {
        output.writeString(23, getJsUrl());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasVersionNeedUpdate()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(4, getVersionNeedUpdate());
      }
      if (hasUpdateUrl()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(5, getUpdateUrl());
      }
      if (hasServerTime()) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed64Size(6, getServerTime());
      }
      if (hasBasicInfoNeedUpdate()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(8, getBasicInfoNeedUpdate());
      }
      if (hasManagerNeedUpdate()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(9, getManagerNeedUpdate());
      }
      if (hasCompanyNeedUpdate()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(10, getCompanyNeedUpdate());
      }
      if (hasNewsTypeNeedUpdate()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(11, getNewsTypeNeedUpdate());
      }
      if (hasOpinionTypeNeedUpdate()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(12, getOpinionTypeNeedUpdate());
      }
      if (hasCommon()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(13, getCommon());
      }
      for (com.howbuy.wireless.entity.protobuf.PhoneNewsTypeProtos.PhoneNewsType element : getPhoneNewsTypeList()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(14, element);
      }
      for (com.howbuy.wireless.entity.protobuf.PhoneOpinionTypeProtos.PhoneOpinionType element : getPhoneOpinionTypeList()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(15, element);
      }
      if (hasKfsNeedUpdate()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(16, getKfsNeedUpdate());
      }
      if (hasFbsNeedUpdate()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(17, getFbsNeedUpdate());
      }
      if (hasHbsNeedUpdate()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(18, getHbsNeedUpdate());
      }
      if (hasSmNeedUpdate()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(19, getSmNeedUpdate());
      }
      if (hasDtNeedUpdate()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(20, getDtNeedUpdate());
      }
      if (hasUpdateDesc()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(21, getUpdateDesc());
      }
      if (hasNewJsVer()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(22, getNewJsVer());
      }
      if (hasJsUrl()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(23, getJsUrl());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.howbuy.wireless.entity.protobuf.HostDistributionProtos.HostDistribution parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.howbuy.wireless.entity.protobuf.HostDistributionProtos.HostDistribution parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.howbuy.wireless.entity.protobuf.HostDistributionProtos.HostDistribution parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.howbuy.wireless.entity.protobuf.HostDistributionProtos.HostDistribution parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.howbuy.wireless.entity.protobuf.HostDistributionProtos.HostDistribution parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.howbuy.wireless.entity.protobuf.HostDistributionProtos.HostDistribution parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.howbuy.wireless.entity.protobuf.HostDistributionProtos.HostDistribution parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.howbuy.wireless.entity.protobuf.HostDistributionProtos.HostDistribution parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.howbuy.wireless.entity.protobuf.HostDistributionProtos.HostDistribution parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.howbuy.wireless.entity.protobuf.HostDistributionProtos.HostDistribution parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.howbuy.wireless.entity.protobuf.HostDistributionProtos.HostDistribution prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.howbuy.wireless.entity.protobuf.HostDistributionProtos.HostDistribution result;
      
      // Construct using com.howbuy.wireless.entity.protobuf.HostDistributionProtos.HostDistribution.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.howbuy.wireless.entity.protobuf.HostDistributionProtos.HostDistribution();
        return builder;
      }
      
      protected com.howbuy.wireless.entity.protobuf.HostDistributionProtos.HostDistribution internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.howbuy.wireless.entity.protobuf.HostDistributionProtos.HostDistribution();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.howbuy.wireless.entity.protobuf.HostDistributionProtos.HostDistribution.getDescriptor();
      }
      
      public com.howbuy.wireless.entity.protobuf.HostDistributionProtos.HostDistribution getDefaultInstanceForType() {
        return com.howbuy.wireless.entity.protobuf.HostDistributionProtos.HostDistribution.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.howbuy.wireless.entity.protobuf.HostDistributionProtos.HostDistribution build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.howbuy.wireless.entity.protobuf.HostDistributionProtos.HostDistribution buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.howbuy.wireless.entity.protobuf.HostDistributionProtos.HostDistribution buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        if (result.phoneNewsType_ != java.util.Collections.EMPTY_LIST) {
          result.phoneNewsType_ =
            java.util.Collections.unmodifiableList(result.phoneNewsType_);
        }
        if (result.phoneOpinionType_ != java.util.Collections.EMPTY_LIST) {
          result.phoneOpinionType_ =
            java.util.Collections.unmodifiableList(result.phoneOpinionType_);
        }
        com.howbuy.wireless.entity.protobuf.HostDistributionProtos.HostDistribution returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.howbuy.wireless.entity.protobuf.HostDistributionProtos.HostDistribution) {
          return mergeFrom((com.howbuy.wireless.entity.protobuf.HostDistributionProtos.HostDistribution)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.howbuy.wireless.entity.protobuf.HostDistributionProtos.HostDistribution other) {
        if (other == com.howbuy.wireless.entity.protobuf.HostDistributionProtos.HostDistribution.getDefaultInstance()) return this;
        if (other.hasVersionNeedUpdate()) {
          setVersionNeedUpdate(other.getVersionNeedUpdate());
        }
        if (other.hasUpdateUrl()) {
          setUpdateUrl(other.getUpdateUrl());
        }
        if (other.hasServerTime()) {
          setServerTime(other.getServerTime());
        }
        if (other.hasBasicInfoNeedUpdate()) {
          setBasicInfoNeedUpdate(other.getBasicInfoNeedUpdate());
        }
        if (other.hasManagerNeedUpdate()) {
          setManagerNeedUpdate(other.getManagerNeedUpdate());
        }
        if (other.hasCompanyNeedUpdate()) {
          setCompanyNeedUpdate(other.getCompanyNeedUpdate());
        }
        if (other.hasNewsTypeNeedUpdate()) {
          setNewsTypeNeedUpdate(other.getNewsTypeNeedUpdate());
        }
        if (other.hasOpinionTypeNeedUpdate()) {
          setOpinionTypeNeedUpdate(other.getOpinionTypeNeedUpdate());
        }
        if (other.hasCommon()) {
          mergeCommon(other.getCommon());
        }
        if (!other.phoneNewsType_.isEmpty()) {
          if (result.phoneNewsType_.isEmpty()) {
            result.phoneNewsType_ = new java.util.ArrayList<com.howbuy.wireless.entity.protobuf.PhoneNewsTypeProtos.PhoneNewsType>();
          }
          result.phoneNewsType_.addAll(other.phoneNewsType_);
        }
        if (!other.phoneOpinionType_.isEmpty()) {
          if (result.phoneOpinionType_.isEmpty()) {
            result.phoneOpinionType_ = new java.util.ArrayList<com.howbuy.wireless.entity.protobuf.PhoneOpinionTypeProtos.PhoneOpinionType>();
          }
          result.phoneOpinionType_.addAll(other.phoneOpinionType_);
        }
        if (other.hasKfsNeedUpdate()) {
          setKfsNeedUpdate(other.getKfsNeedUpdate());
        }
        if (other.hasFbsNeedUpdate()) {
          setFbsNeedUpdate(other.getFbsNeedUpdate());
        }
        if (other.hasHbsNeedUpdate()) {
          setHbsNeedUpdate(other.getHbsNeedUpdate());
        }
        if (other.hasSmNeedUpdate()) {
          setSmNeedUpdate(other.getSmNeedUpdate());
        }
        if (other.hasDtNeedUpdate()) {
          setDtNeedUpdate(other.getDtNeedUpdate());
        }
        if (other.hasUpdateDesc()) {
          setUpdateDesc(other.getUpdateDesc());
        }
        if (other.hasNewJsVer()) {
          setNewJsVer(other.getNewJsVer());
        }
        if (other.hasJsUrl()) {
          setJsUrl(other.getJsUrl());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 34: {
              setVersionNeedUpdate(input.readString());
              break;
            }
            case 42: {
              setUpdateUrl(input.readString());
              break;
            }
            case 49: {
              setServerTime(input.readFixed64());
              break;
            }
            case 66: {
              setBasicInfoNeedUpdate(input.readString());
              break;
            }
            case 74: {
              setManagerNeedUpdate(input.readString());
              break;
            }
            case 82: {
              setCompanyNeedUpdate(input.readString());
              break;
            }
            case 90: {
              setNewsTypeNeedUpdate(input.readString());
              break;
            }
            case 98: {
              setOpinionTypeNeedUpdate(input.readString());
              break;
            }
            case 106: {
              com.howbuy.wireless.entity.protobuf.CommonProtos.Common.Builder subBuilder = com.howbuy.wireless.entity.protobuf.CommonProtos.Common.newBuilder();
              if (hasCommon()) {
                subBuilder.mergeFrom(getCommon());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setCommon(subBuilder.buildPartial());
              break;
            }
            case 114: {
              com.howbuy.wireless.entity.protobuf.PhoneNewsTypeProtos.PhoneNewsType.Builder subBuilder = com.howbuy.wireless.entity.protobuf.PhoneNewsTypeProtos.PhoneNewsType.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addPhoneNewsType(subBuilder.buildPartial());
              break;
            }
            case 122: {
              com.howbuy.wireless.entity.protobuf.PhoneOpinionTypeProtos.PhoneOpinionType.Builder subBuilder = com.howbuy.wireless.entity.protobuf.PhoneOpinionTypeProtos.PhoneOpinionType.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addPhoneOpinionType(subBuilder.buildPartial());
              break;
            }
            case 130: {
              setKfsNeedUpdate(input.readString());
              break;
            }
            case 138: {
              setFbsNeedUpdate(input.readString());
              break;
            }
            case 146: {
              setHbsNeedUpdate(input.readString());
              break;
            }
            case 154: {
              setSmNeedUpdate(input.readString());
              break;
            }
            case 162: {
              setDtNeedUpdate(input.readString());
              break;
            }
            case 170: {
              setUpdateDesc(input.readString());
              break;
            }
            case 178: {
              setNewJsVer(input.readString());
              break;
            }
            case 186: {
              setJsUrl(input.readString());
              break;
            }
          }
        }
      }
      
      
      // optional string versionNeedUpdate = 4;
      public boolean hasVersionNeedUpdate() {
        return result.hasVersionNeedUpdate();
      }
      public java.lang.String getVersionNeedUpdate() {
        return result.getVersionNeedUpdate();
      }
      public Builder setVersionNeedUpdate(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasVersionNeedUpdate = true;
        result.versionNeedUpdate_ = value;
        return this;
      }
      public Builder clearVersionNeedUpdate() {
        result.hasVersionNeedUpdate = false;
        result.versionNeedUpdate_ = getDefaultInstance().getVersionNeedUpdate();
        return this;
      }
      
      // optional string updateUrl = 5;
      public boolean hasUpdateUrl() {
        return result.hasUpdateUrl();
      }
      public java.lang.String getUpdateUrl() {
        return result.getUpdateUrl();
      }
      public Builder setUpdateUrl(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasUpdateUrl = true;
        result.updateUrl_ = value;
        return this;
      }
      public Builder clearUpdateUrl() {
        result.hasUpdateUrl = false;
        result.updateUrl_ = getDefaultInstance().getUpdateUrl();
        return this;
      }
      
      // optional fixed64 serverTime = 6;
      public boolean hasServerTime() {
        return result.hasServerTime();
      }
      public long getServerTime() {
        return result.getServerTime();
      }
      public Builder setServerTime(long value) {
        result.hasServerTime = true;
        result.serverTime_ = value;
        return this;
      }
      public Builder clearServerTime() {
        result.hasServerTime = false;
        result.serverTime_ = 0L;
        return this;
      }
      
      // optional string basicInfoNeedUpdate = 8;
      public boolean hasBasicInfoNeedUpdate() {
        return result.hasBasicInfoNeedUpdate();
      }
      public java.lang.String getBasicInfoNeedUpdate() {
        return result.getBasicInfoNeedUpdate();
      }
      public Builder setBasicInfoNeedUpdate(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasBasicInfoNeedUpdate = true;
        result.basicInfoNeedUpdate_ = value;
        return this;
      }
      public Builder clearBasicInfoNeedUpdate() {
        result.hasBasicInfoNeedUpdate = false;
        result.basicInfoNeedUpdate_ = getDefaultInstance().getBasicInfoNeedUpdate();
        return this;
      }
      
      // optional string managerNeedUpdate = 9;
      public boolean hasManagerNeedUpdate() {
        return result.hasManagerNeedUpdate();
      }
      public java.lang.String getManagerNeedUpdate() {
        return result.getManagerNeedUpdate();
      }
      public Builder setManagerNeedUpdate(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasManagerNeedUpdate = true;
        result.managerNeedUpdate_ = value;
        return this;
      }
      public Builder clearManagerNeedUpdate() {
        result.hasManagerNeedUpdate = false;
        result.managerNeedUpdate_ = getDefaultInstance().getManagerNeedUpdate();
        return this;
      }
      
      // optional string companyNeedUpdate = 10;
      public boolean hasCompanyNeedUpdate() {
        return result.hasCompanyNeedUpdate();
      }
      public java.lang.String getCompanyNeedUpdate() {
        return result.getCompanyNeedUpdate();
      }
      public Builder setCompanyNeedUpdate(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasCompanyNeedUpdate = true;
        result.companyNeedUpdate_ = value;
        return this;
      }
      public Builder clearCompanyNeedUpdate() {
        result.hasCompanyNeedUpdate = false;
        result.companyNeedUpdate_ = getDefaultInstance().getCompanyNeedUpdate();
        return this;
      }
      
      // optional string newsTypeNeedUpdate = 11;
      public boolean hasNewsTypeNeedUpdate() {
        return result.hasNewsTypeNeedUpdate();
      }
      public java.lang.String getNewsTypeNeedUpdate() {
        return result.getNewsTypeNeedUpdate();
      }
      public Builder setNewsTypeNeedUpdate(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasNewsTypeNeedUpdate = true;
        result.newsTypeNeedUpdate_ = value;
        return this;
      }
      public Builder clearNewsTypeNeedUpdate() {
        result.hasNewsTypeNeedUpdate = false;
        result.newsTypeNeedUpdate_ = getDefaultInstance().getNewsTypeNeedUpdate();
        return this;
      }
      
      // optional string opinionTypeNeedUpdate = 12;
      public boolean hasOpinionTypeNeedUpdate() {
        return result.hasOpinionTypeNeedUpdate();
      }
      public java.lang.String getOpinionTypeNeedUpdate() {
        return result.getOpinionTypeNeedUpdate();
      }
      public Builder setOpinionTypeNeedUpdate(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasOpinionTypeNeedUpdate = true;
        result.opinionTypeNeedUpdate_ = value;
        return this;
      }
      public Builder clearOpinionTypeNeedUpdate() {
        result.hasOpinionTypeNeedUpdate = false;
        result.opinionTypeNeedUpdate_ = getDefaultInstance().getOpinionTypeNeedUpdate();
        return this;
      }
      
      // optional .common.Common common = 13;
      public boolean hasCommon() {
        return result.hasCommon();
      }
      public com.howbuy.wireless.entity.protobuf.CommonProtos.Common getCommon() {
        return result.getCommon();
      }
      public Builder setCommon(com.howbuy.wireless.entity.protobuf.CommonProtos.Common value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasCommon = true;
        result.common_ = value;
        return this;
      }
      public Builder setCommon(com.howbuy.wireless.entity.protobuf.CommonProtos.Common.Builder builderForValue) {
        result.hasCommon = true;
        result.common_ = builderForValue.build();
        return this;
      }
      public Builder mergeCommon(com.howbuy.wireless.entity.protobuf.CommonProtos.Common value) {
        if (result.hasCommon() &&
            result.common_ != com.howbuy.wireless.entity.protobuf.CommonProtos.Common.getDefaultInstance()) {
          result.common_ =
            com.howbuy.wireless.entity.protobuf.CommonProtos.Common.newBuilder(result.common_).mergeFrom(value).buildPartial();
        } else {
          result.common_ = value;
        }
        result.hasCommon = true;
        return this;
      }
      public Builder clearCommon() {
        result.hasCommon = false;
        result.common_ = com.howbuy.wireless.entity.protobuf.CommonProtos.Common.getDefaultInstance();
        return this;
      }
      
      // repeated .common.PhoneNewsType phoneNewsType = 14;
      public java.util.List<com.howbuy.wireless.entity.protobuf.PhoneNewsTypeProtos.PhoneNewsType> getPhoneNewsTypeList() {
        return java.util.Collections.unmodifiableList(result.phoneNewsType_);
      }
      public int getPhoneNewsTypeCount() {
        return result.getPhoneNewsTypeCount();
      }
      public com.howbuy.wireless.entity.protobuf.PhoneNewsTypeProtos.PhoneNewsType getPhoneNewsType(int index) {
        return result.getPhoneNewsType(index);
      }
      public Builder setPhoneNewsType(int index, com.howbuy.wireless.entity.protobuf.PhoneNewsTypeProtos.PhoneNewsType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.phoneNewsType_.set(index, value);
        return this;
      }
      public Builder setPhoneNewsType(int index, com.howbuy.wireless.entity.protobuf.PhoneNewsTypeProtos.PhoneNewsType.Builder builderForValue) {
        result.phoneNewsType_.set(index, builderForValue.build());
        return this;
      }
      public Builder addPhoneNewsType(com.howbuy.wireless.entity.protobuf.PhoneNewsTypeProtos.PhoneNewsType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        if (result.phoneNewsType_.isEmpty()) {
          result.phoneNewsType_ = new java.util.ArrayList<com.howbuy.wireless.entity.protobuf.PhoneNewsTypeProtos.PhoneNewsType>();
        }
        result.phoneNewsType_.add(value);
        return this;
      }
      public Builder addPhoneNewsType(com.howbuy.wireless.entity.protobuf.PhoneNewsTypeProtos.PhoneNewsType.Builder builderForValue) {
        if (result.phoneNewsType_.isEmpty()) {
          result.phoneNewsType_ = new java.util.ArrayList<com.howbuy.wireless.entity.protobuf.PhoneNewsTypeProtos.PhoneNewsType>();
        }
        result.phoneNewsType_.add(builderForValue.build());
        return this;
      }
      public Builder addAllPhoneNewsType(
          java.lang.Iterable<? extends com.howbuy.wireless.entity.protobuf.PhoneNewsTypeProtos.PhoneNewsType> values) {
        if (result.phoneNewsType_.isEmpty()) {
          result.phoneNewsType_ = new java.util.ArrayList<com.howbuy.wireless.entity.protobuf.PhoneNewsTypeProtos.PhoneNewsType>();
        }
        super.addAll(values, result.phoneNewsType_);
        return this;
      }
      public Builder clearPhoneNewsType() {
        result.phoneNewsType_ = java.util.Collections.emptyList();
        return this;
      }
      
      // repeated .common.PhoneOpinionType phoneOpinionType = 15;
      public java.util.List<com.howbuy.wireless.entity.protobuf.PhoneOpinionTypeProtos.PhoneOpinionType> getPhoneOpinionTypeList() {
        return java.util.Collections.unmodifiableList(result.phoneOpinionType_);
      }
      public int getPhoneOpinionTypeCount() {
        return result.getPhoneOpinionTypeCount();
      }
      public com.howbuy.wireless.entity.protobuf.PhoneOpinionTypeProtos.PhoneOpinionType getPhoneOpinionType(int index) {
        return result.getPhoneOpinionType(index);
      }
      public Builder setPhoneOpinionType(int index, com.howbuy.wireless.entity.protobuf.PhoneOpinionTypeProtos.PhoneOpinionType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.phoneOpinionType_.set(index, value);
        return this;
      }
      public Builder setPhoneOpinionType(int index, com.howbuy.wireless.entity.protobuf.PhoneOpinionTypeProtos.PhoneOpinionType.Builder builderForValue) {
        result.phoneOpinionType_.set(index, builderForValue.build());
        return this;
      }
      public Builder addPhoneOpinionType(com.howbuy.wireless.entity.protobuf.PhoneOpinionTypeProtos.PhoneOpinionType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        if (result.phoneOpinionType_.isEmpty()) {
          result.phoneOpinionType_ = new java.util.ArrayList<com.howbuy.wireless.entity.protobuf.PhoneOpinionTypeProtos.PhoneOpinionType>();
        }
        result.phoneOpinionType_.add(value);
        return this;
      }
      public Builder addPhoneOpinionType(com.howbuy.wireless.entity.protobuf.PhoneOpinionTypeProtos.PhoneOpinionType.Builder builderForValue) {
        if (result.phoneOpinionType_.isEmpty()) {
          result.phoneOpinionType_ = new java.util.ArrayList<com.howbuy.wireless.entity.protobuf.PhoneOpinionTypeProtos.PhoneOpinionType>();
        }
        result.phoneOpinionType_.add(builderForValue.build());
        return this;
      }
      public Builder addAllPhoneOpinionType(
          java.lang.Iterable<? extends com.howbuy.wireless.entity.protobuf.PhoneOpinionTypeProtos.PhoneOpinionType> values) {
        if (result.phoneOpinionType_.isEmpty()) {
          result.phoneOpinionType_ = new java.util.ArrayList<com.howbuy.wireless.entity.protobuf.PhoneOpinionTypeProtos.PhoneOpinionType>();
        }
        super.addAll(values, result.phoneOpinionType_);
        return this;
      }
      public Builder clearPhoneOpinionType() {
        result.phoneOpinionType_ = java.util.Collections.emptyList();
        return this;
      }
      
      // optional string kfsNeedUpdate = 16;
      public boolean hasKfsNeedUpdate() {
        return result.hasKfsNeedUpdate();
      }
      public java.lang.String getKfsNeedUpdate() {
        return result.getKfsNeedUpdate();
      }
      public Builder setKfsNeedUpdate(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasKfsNeedUpdate = true;
        result.kfsNeedUpdate_ = value;
        return this;
      }
      public Builder clearKfsNeedUpdate() {
        result.hasKfsNeedUpdate = false;
        result.kfsNeedUpdate_ = getDefaultInstance().getKfsNeedUpdate();
        return this;
      }
      
      // optional string fbsNeedUpdate = 17;
      public boolean hasFbsNeedUpdate() {
        return result.hasFbsNeedUpdate();
      }
      public java.lang.String getFbsNeedUpdate() {
        return result.getFbsNeedUpdate();
      }
      public Builder setFbsNeedUpdate(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasFbsNeedUpdate = true;
        result.fbsNeedUpdate_ = value;
        return this;
      }
      public Builder clearFbsNeedUpdate() {
        result.hasFbsNeedUpdate = false;
        result.fbsNeedUpdate_ = getDefaultInstance().getFbsNeedUpdate();
        return this;
      }
      
      // optional string hbsNeedUpdate = 18;
      public boolean hasHbsNeedUpdate() {
        return result.hasHbsNeedUpdate();
      }
      public java.lang.String getHbsNeedUpdate() {
        return result.getHbsNeedUpdate();
      }
      public Builder setHbsNeedUpdate(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasHbsNeedUpdate = true;
        result.hbsNeedUpdate_ = value;
        return this;
      }
      public Builder clearHbsNeedUpdate() {
        result.hasHbsNeedUpdate = false;
        result.hbsNeedUpdate_ = getDefaultInstance().getHbsNeedUpdate();
        return this;
      }
      
      // optional string smNeedUpdate = 19;
      public boolean hasSmNeedUpdate() {
        return result.hasSmNeedUpdate();
      }
      public java.lang.String getSmNeedUpdate() {
        return result.getSmNeedUpdate();
      }
      public Builder setSmNeedUpdate(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasSmNeedUpdate = true;
        result.smNeedUpdate_ = value;
        return this;
      }
      public Builder clearSmNeedUpdate() {
        result.hasSmNeedUpdate = false;
        result.smNeedUpdate_ = getDefaultInstance().getSmNeedUpdate();
        return this;
      }
      
      // optional string dtNeedUpdate = 20;
      public boolean hasDtNeedUpdate() {
        return result.hasDtNeedUpdate();
      }
      public java.lang.String getDtNeedUpdate() {
        return result.getDtNeedUpdate();
      }
      public Builder setDtNeedUpdate(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasDtNeedUpdate = true;
        result.dtNeedUpdate_ = value;
        return this;
      }
      public Builder clearDtNeedUpdate() {
        result.hasDtNeedUpdate = false;
        result.dtNeedUpdate_ = getDefaultInstance().getDtNeedUpdate();
        return this;
      }
      
      // optional string updateDesc = 21;
      public boolean hasUpdateDesc() {
        return result.hasUpdateDesc();
      }
      public java.lang.String getUpdateDesc() {
        return result.getUpdateDesc();
      }
      public Builder setUpdateDesc(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasUpdateDesc = true;
        result.updateDesc_ = value;
        return this;
      }
      public Builder clearUpdateDesc() {
        result.hasUpdateDesc = false;
        result.updateDesc_ = getDefaultInstance().getUpdateDesc();
        return this;
      }
      
      // optional string newJsVer = 22;
      public boolean hasNewJsVer() {
        return result.hasNewJsVer();
      }
      public java.lang.String getNewJsVer() {
        return result.getNewJsVer();
      }
      public Builder setNewJsVer(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasNewJsVer = true;
        result.newJsVer_ = value;
        return this;
      }
      public Builder clearNewJsVer() {
        result.hasNewJsVer = false;
        result.newJsVer_ = getDefaultInstance().getNewJsVer();
        return this;
      }
      
      // optional string jsUrl = 23;
      public boolean hasJsUrl() {
        return result.hasJsUrl();
      }
      public java.lang.String getJsUrl() {
        return result.getJsUrl();
      }
      public Builder setJsUrl(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasJsUrl = true;
        result.jsUrl_ = value;
        return this;
      }
      public Builder clearJsUrl() {
        result.hasJsUrl = false;
        result.jsUrl_ = getDefaultInstance().getJsUrl();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:HostDistribution)
    }
    
    static {
      defaultInstance = new HostDistribution(true);
      com.howbuy.wireless.entity.protobuf.HostDistributionProtos.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:HostDistribution)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_HostDistribution_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_HostDistribution_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026hostDistribution.proto\032\014common.proto\032\023" +
      "phoneNewsType.proto\032\026phoneOpinionType.pr" +
      "oto\"\212\004\n\020HostDistribution\022\031\n\021versionNeedU" +
      "pdate\030\004 \001(\t\022\021\n\tupdateUrl\030\005 \001(\t\022\022\n\nserver" +
      "Time\030\006 \001(\006\022\033\n\023basicInfoNeedUpdate\030\010 \001(\t\022" +
      "\031\n\021managerNeedUpdate\030\t \001(\t\022\031\n\021companyNee" +
      "dUpdate\030\n \001(\t\022\032\n\022newsTypeNeedUpdate\030\013 \001(" +
      "\t\022\035\n\025opinionTypeNeedUpdate\030\014 \001(\t\022\036\n\006comm" +
      "on\030\r \001(\0132\016.common.Common\022,\n\rphoneNewsTyp" +
      "e\030\016 \003(\0132\025.common.PhoneNewsType\0222\n\020phoneO",
      "pinionType\030\017 \003(\0132\030.common.PhoneOpinionTy" +
      "pe\022\025\n\rkfsNeedUpdate\030\020 \001(\t\022\025\n\rfbsNeedUpda" +
      "te\030\021 \001(\t\022\025\n\rhbsNeedUpdate\030\022 \001(\t\022\024\n\014smNee" +
      "dUpdate\030\023 \001(\t\022\024\n\014dtNeedUpdate\030\024 \001(\t\022\022\n\nu" +
      "pdateDesc\030\025 \001(\t\022\020\n\010newJsVer\030\026 \001(\t\022\r\n\005jsU" +
      "rl\030\027 \001(\tB=\n#com.howbuy.wireless.entity.p" +
      "rotobufB\026HostDistributionProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_HostDistribution_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_HostDistribution_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_HostDistribution_descriptor,
              new java.lang.String[] { "VersionNeedUpdate", "UpdateUrl", "ServerTime", "BasicInfoNeedUpdate", "ManagerNeedUpdate", "CompanyNeedUpdate", "NewsTypeNeedUpdate", "OpinionTypeNeedUpdate", "Common", "PhoneNewsType", "PhoneOpinionType", "KfsNeedUpdate", "FbsNeedUpdate", "HbsNeedUpdate", "SmNeedUpdate", "DtNeedUpdate", "UpdateDesc", "NewJsVer", "JsUrl", },
              com.howbuy.wireless.entity.protobuf.HostDistributionProtos.HostDistribution.class,
              com.howbuy.wireless.entity.protobuf.HostDistributionProtos.HostDistribution.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.howbuy.wireless.entity.protobuf.CommonProtos.getDescriptor(),
          com.howbuy.wireless.entity.protobuf.PhoneNewsTypeProtos.getDescriptor(),
          com.howbuy.wireless.entity.protobuf.PhoneOpinionTypeProtos.getDescriptor(),
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
