// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: managerDetailInfoList.proto

package com.howbuy.wireless.entity.protobuf;

public final class ManagerDetailInfoListProto {
  private ManagerDetailInfoListProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class ManagerDetailInfoList extends
      com.google.protobuf.GeneratedMessage {
    // Use ManagerDetailInfoList.newBuilder() to construct.
    private ManagerDetailInfoList() {
      initFields();
    }
    private ManagerDetailInfoList(boolean noInit) {}
    
    private static final ManagerDetailInfoList defaultInstance;
    public static ManagerDetailInfoList getDefaultInstance() {
      return defaultInstance;
    }
    
    public ManagerDetailInfoList getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.howbuy.wireless.entity.protobuf.ManagerDetailInfoListProto.internal_static_ManagerDetailInfoList_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.howbuy.wireless.entity.protobuf.ManagerDetailInfoListProto.internal_static_ManagerDetailInfoList_fieldAccessorTable;
    }
    
    // optional .common.Common common = 1;
    public static final int COMMON_FIELD_NUMBER = 1;
    private boolean hasCommon;
    private com.howbuy.wireless.entity.protobuf.CommonProtos.Common common_;
    public boolean hasCommon() { return hasCommon; }
    public com.howbuy.wireless.entity.protobuf.CommonProtos.Common getCommon() { return common_; }
    
    // optional string ryxm = 2;
    public static final int RYXM_FIELD_NUMBER = 2;
    private boolean hasRyxm;
    private java.lang.String ryxm_ = "";
    public boolean hasRyxm() { return hasRyxm; }
    public java.lang.String getRyxm() { return ryxm_; }
    
    // optional string ryxb = 3;
    public static final int RYXB_FIELD_NUMBER = 3;
    private boolean hasRyxb;
    private java.lang.String ryxb_ = "";
    public boolean hasRyxb() { return hasRyxb; }
    public java.lang.String getRyxb() { return ryxb_; }
    
    // optional string cynx = 4;
    public static final int CYNX_FIELD_NUMBER = 4;
    private boolean hasCynx;
    private java.lang.String cynx_ = "";
    public boolean hasCynx() { return hasCynx; }
    public java.lang.String getCynx() { return cynx_; }
    
    // optional string gzgs = 5;
    public static final int GZGS_FIELD_NUMBER = 5;
    private boolean hasGzgs;
    private java.lang.String gzgs_ = "";
    public boolean hasGzgs() { return hasGzgs; }
    public java.lang.String getGzgs() { return gzgs_; }
    
    // optional string ryjj = 6;
    public static final int RYJJ_FIELD_NUMBER = 6;
    private boolean hasRyjj;
    private java.lang.String ryjj_ = "";
    public boolean hasRyjj() { return hasRyjj; }
    public java.lang.String getRyjj() { return ryjj_; }
    
    // optional string zpdz = 7;
    public static final int ZPDZ_FIELD_NUMBER = 7;
    private boolean hasZpdz;
    private java.lang.String zpdz_ = "";
    public boolean hasZpdz() { return hasZpdz; }
    public java.lang.String getZpdz() { return zpdz_; }
    
    // repeated .Fund fund = 8;
    public static final int FUND_FIELD_NUMBER = 8;
    private java.util.List<com.howbuy.wireless.entity.protobuf.FundProtos.Fund> fund_ =
      java.util.Collections.emptyList();
    public java.util.List<com.howbuy.wireless.entity.protobuf.FundProtos.Fund> getFundList() {
      return fund_;
    }
    public int getFundCount() { return fund_.size(); }
    public com.howbuy.wireless.entity.protobuf.FundProtos.Fund getFund(int index) {
      return fund_.get(index);
    }
    
    // repeated .Issue issue = 9;
    public static final int ISSUE_FIELD_NUMBER = 9;
    private java.util.List<com.howbuy.wireless.entity.protobuf.IssueProtos.Issue> issue_ =
      java.util.Collections.emptyList();
    public java.util.List<com.howbuy.wireless.entity.protobuf.IssueProtos.Issue> getIssueList() {
      return issue_;
    }
    public int getIssueCount() { return issue_.size(); }
    public com.howbuy.wireless.entity.protobuf.IssueProtos.Issue getIssue(int index) {
      return issue_.get(index);
    }
    
    private void initFields() {
      common_ = com.howbuy.wireless.entity.protobuf.CommonProtos.Common.getDefaultInstance();
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasCommon()) {
        output.writeMessage(1, getCommon());
      }
      if (hasRyxm()) {
        output.writeString(2, getRyxm());
      }
      if (hasRyxb()) {
        output.writeString(3, getRyxb());
      }
      if (hasCynx()) {
        output.writeString(4, getCynx());
      }
      if (hasGzgs()) {
        output.writeString(5, getGzgs());
      }
      if (hasRyjj()) {
        output.writeString(6, getRyjj());
      }
      if (hasZpdz()) {
        output.writeString(7, getZpdz());
      }
      for (com.howbuy.wireless.entity.protobuf.FundProtos.Fund element : getFundList()) {
        output.writeMessage(8, element);
      }
      for (com.howbuy.wireless.entity.protobuf.IssueProtos.Issue element : getIssueList()) {
        output.writeMessage(9, element);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasCommon()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getCommon());
      }
      if (hasRyxm()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getRyxm());
      }
      if (hasRyxb()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(3, getRyxb());
      }
      if (hasCynx()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(4, getCynx());
      }
      if (hasGzgs()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(5, getGzgs());
      }
      if (hasRyjj()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(6, getRyjj());
      }
      if (hasZpdz()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(7, getZpdz());
      }
      for (com.howbuy.wireless.entity.protobuf.FundProtos.Fund element : getFundList()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(8, element);
      }
      for (com.howbuy.wireless.entity.protobuf.IssueProtos.Issue element : getIssueList()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(9, element);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.howbuy.wireless.entity.protobuf.ManagerDetailInfoListProto.ManagerDetailInfoList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.howbuy.wireless.entity.protobuf.ManagerDetailInfoListProto.ManagerDetailInfoList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.howbuy.wireless.entity.protobuf.ManagerDetailInfoListProto.ManagerDetailInfoList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.howbuy.wireless.entity.protobuf.ManagerDetailInfoListProto.ManagerDetailInfoList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.howbuy.wireless.entity.protobuf.ManagerDetailInfoListProto.ManagerDetailInfoList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.howbuy.wireless.entity.protobuf.ManagerDetailInfoListProto.ManagerDetailInfoList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.howbuy.wireless.entity.protobuf.ManagerDetailInfoListProto.ManagerDetailInfoList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.howbuy.wireless.entity.protobuf.ManagerDetailInfoListProto.ManagerDetailInfoList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.howbuy.wireless.entity.protobuf.ManagerDetailInfoListProto.ManagerDetailInfoList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.howbuy.wireless.entity.protobuf.ManagerDetailInfoListProto.ManagerDetailInfoList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.howbuy.wireless.entity.protobuf.ManagerDetailInfoListProto.ManagerDetailInfoList prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.howbuy.wireless.entity.protobuf.ManagerDetailInfoListProto.ManagerDetailInfoList result;
      
      // Construct using com.howbuy.wireless.entity.protobuf.ManagerDetailInfoListProto.ManagerDetailInfoList.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.howbuy.wireless.entity.protobuf.ManagerDetailInfoListProto.ManagerDetailInfoList();
        return builder;
      }
      
      protected com.howbuy.wireless.entity.protobuf.ManagerDetailInfoListProto.ManagerDetailInfoList internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.howbuy.wireless.entity.protobuf.ManagerDetailInfoListProto.ManagerDetailInfoList();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.howbuy.wireless.entity.protobuf.ManagerDetailInfoListProto.ManagerDetailInfoList.getDescriptor();
      }
      
      public com.howbuy.wireless.entity.protobuf.ManagerDetailInfoListProto.ManagerDetailInfoList getDefaultInstanceForType() {
        return com.howbuy.wireless.entity.protobuf.ManagerDetailInfoListProto.ManagerDetailInfoList.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.howbuy.wireless.entity.protobuf.ManagerDetailInfoListProto.ManagerDetailInfoList build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.howbuy.wireless.entity.protobuf.ManagerDetailInfoListProto.ManagerDetailInfoList buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.howbuy.wireless.entity.protobuf.ManagerDetailInfoListProto.ManagerDetailInfoList buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        if (result.fund_ != java.util.Collections.EMPTY_LIST) {
          result.fund_ =
            java.util.Collections.unmodifiableList(result.fund_);
        }
        if (result.issue_ != java.util.Collections.EMPTY_LIST) {
          result.issue_ =
            java.util.Collections.unmodifiableList(result.issue_);
        }
        com.howbuy.wireless.entity.protobuf.ManagerDetailInfoListProto.ManagerDetailInfoList returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.howbuy.wireless.entity.protobuf.ManagerDetailInfoListProto.ManagerDetailInfoList) {
          return mergeFrom((com.howbuy.wireless.entity.protobuf.ManagerDetailInfoListProto.ManagerDetailInfoList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.howbuy.wireless.entity.protobuf.ManagerDetailInfoListProto.ManagerDetailInfoList other) {
        if (other == com.howbuy.wireless.entity.protobuf.ManagerDetailInfoListProto.ManagerDetailInfoList.getDefaultInstance()) return this;
        if (other.hasCommon()) {
          mergeCommon(other.getCommon());
        }
        if (other.hasRyxm()) {
          setRyxm(other.getRyxm());
        }
        if (other.hasRyxb()) {
          setRyxb(other.getRyxb());
        }
        if (other.hasCynx()) {
          setCynx(other.getCynx());
        }
        if (other.hasGzgs()) {
          setGzgs(other.getGzgs());
        }
        if (other.hasRyjj()) {
          setRyjj(other.getRyjj());
        }
        if (other.hasZpdz()) {
          setZpdz(other.getZpdz());
        }
        if (!other.fund_.isEmpty()) {
          if (result.fund_.isEmpty()) {
            result.fund_ = new java.util.ArrayList<com.howbuy.wireless.entity.protobuf.FundProtos.Fund>();
          }
          result.fund_.addAll(other.fund_);
        }
        if (!other.issue_.isEmpty()) {
          if (result.issue_.isEmpty()) {
            result.issue_ = new java.util.ArrayList<com.howbuy.wireless.entity.protobuf.IssueProtos.Issue>();
          }
          result.issue_.addAll(other.issue_);
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              com.howbuy.wireless.entity.protobuf.CommonProtos.Common.Builder subBuilder = com.howbuy.wireless.entity.protobuf.CommonProtos.Common.newBuilder();
              if (hasCommon()) {
                subBuilder.mergeFrom(getCommon());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setCommon(subBuilder.buildPartial());
              break;
            }
            case 18: {
              setRyxm(input.readString());
              break;
            }
            case 26: {
              setRyxb(input.readString());
              break;
            }
            case 34: {
              setCynx(input.readString());
              break;
            }
            case 42: {
              setGzgs(input.readString());
              break;
            }
            case 50: {
              setRyjj(input.readString());
              break;
            }
            case 58: {
              setZpdz(input.readString());
              break;
            }
            case 66: {
              com.howbuy.wireless.entity.protobuf.FundProtos.Fund.Builder subBuilder = com.howbuy.wireless.entity.protobuf.FundProtos.Fund.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addFund(subBuilder.buildPartial());
              break;
            }
            case 74: {
              com.howbuy.wireless.entity.protobuf.IssueProtos.Issue.Builder subBuilder = com.howbuy.wireless.entity.protobuf.IssueProtos.Issue.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addIssue(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      
      // optional .common.Common common = 1;
      public boolean hasCommon() {
        return result.hasCommon();
      }
      public com.howbuy.wireless.entity.protobuf.CommonProtos.Common getCommon() {
        return result.getCommon();
      }
      public Builder setCommon(com.howbuy.wireless.entity.protobuf.CommonProtos.Common value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasCommon = true;
        result.common_ = value;
        return this;
      }
      public Builder setCommon(com.howbuy.wireless.entity.protobuf.CommonProtos.Common.Builder builderForValue) {
        result.hasCommon = true;
        result.common_ = builderForValue.build();
        return this;
      }
      public Builder mergeCommon(com.howbuy.wireless.entity.protobuf.CommonProtos.Common value) {
        if (result.hasCommon() &&
            result.common_ != com.howbuy.wireless.entity.protobuf.CommonProtos.Common.getDefaultInstance()) {
          result.common_ =
            com.howbuy.wireless.entity.protobuf.CommonProtos.Common.newBuilder(result.common_).mergeFrom(value).buildPartial();
        } else {
          result.common_ = value;
        }
        result.hasCommon = true;
        return this;
      }
      public Builder clearCommon() {
        result.hasCommon = false;
        result.common_ = com.howbuy.wireless.entity.protobuf.CommonProtos.Common.getDefaultInstance();
        return this;
      }
      
      // optional string ryxm = 2;
      public boolean hasRyxm() {
        return result.hasRyxm();
      }
      public java.lang.String getRyxm() {
        return result.getRyxm();
      }
      public Builder setRyxm(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasRyxm = true;
        result.ryxm_ = value;
        return this;
      }
      public Builder clearRyxm() {
        result.hasRyxm = false;
        result.ryxm_ = getDefaultInstance().getRyxm();
        return this;
      }
      
      // optional string ryxb = 3;
      public boolean hasRyxb() {
        return result.hasRyxb();
      }
      public java.lang.String getRyxb() {
        return result.getRyxb();
      }
      public Builder setRyxb(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasRyxb = true;
        result.ryxb_ = value;
        return this;
      }
      public Builder clearRyxb() {
        result.hasRyxb = false;
        result.ryxb_ = getDefaultInstance().getRyxb();
        return this;
      }
      
      // optional string cynx = 4;
      public boolean hasCynx() {
        return result.hasCynx();
      }
      public java.lang.String getCynx() {
        return result.getCynx();
      }
      public Builder setCynx(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasCynx = true;
        result.cynx_ = value;
        return this;
      }
      public Builder clearCynx() {
        result.hasCynx = false;
        result.cynx_ = getDefaultInstance().getCynx();
        return this;
      }
      
      // optional string gzgs = 5;
      public boolean hasGzgs() {
        return result.hasGzgs();
      }
      public java.lang.String getGzgs() {
        return result.getGzgs();
      }
      public Builder setGzgs(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasGzgs = true;
        result.gzgs_ = value;
        return this;
      }
      public Builder clearGzgs() {
        result.hasGzgs = false;
        result.gzgs_ = getDefaultInstance().getGzgs();
        return this;
      }
      
      // optional string ryjj = 6;
      public boolean hasRyjj() {
        return result.hasRyjj();
      }
      public java.lang.String getRyjj() {
        return result.getRyjj();
      }
      public Builder setRyjj(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasRyjj = true;
        result.ryjj_ = value;
        return this;
      }
      public Builder clearRyjj() {
        result.hasRyjj = false;
        result.ryjj_ = getDefaultInstance().getRyjj();
        return this;
      }
      
      // optional string zpdz = 7;
      public boolean hasZpdz() {
        return result.hasZpdz();
      }
      public java.lang.String getZpdz() {
        return result.getZpdz();
      }
      public Builder setZpdz(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasZpdz = true;
        result.zpdz_ = value;
        return this;
      }
      public Builder clearZpdz() {
        result.hasZpdz = false;
        result.zpdz_ = getDefaultInstance().getZpdz();
        return this;
      }
      
      // repeated .Fund fund = 8;
      public java.util.List<com.howbuy.wireless.entity.protobuf.FundProtos.Fund> getFundList() {
        return java.util.Collections.unmodifiableList(result.fund_);
      }
      public int getFundCount() {
        return result.getFundCount();
      }
      public com.howbuy.wireless.entity.protobuf.FundProtos.Fund getFund(int index) {
        return result.getFund(index);
      }
      public Builder setFund(int index, com.howbuy.wireless.entity.protobuf.FundProtos.Fund value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.fund_.set(index, value);
        return this;
      }
      public Builder setFund(int index, com.howbuy.wireless.entity.protobuf.FundProtos.Fund.Builder builderForValue) {
        result.fund_.set(index, builderForValue.build());
        return this;
      }
      public Builder addFund(com.howbuy.wireless.entity.protobuf.FundProtos.Fund value) {
        if (value == null) {
          throw new NullPointerException();
        }
        if (result.fund_.isEmpty()) {
          result.fund_ = new java.util.ArrayList<com.howbuy.wireless.entity.protobuf.FundProtos.Fund>();
        }
        result.fund_.add(value);
        return this;
      }
      public Builder addFund(com.howbuy.wireless.entity.protobuf.FundProtos.Fund.Builder builderForValue) {
        if (result.fund_.isEmpty()) {
          result.fund_ = new java.util.ArrayList<com.howbuy.wireless.entity.protobuf.FundProtos.Fund>();
        }
        result.fund_.add(builderForValue.build());
        return this;
      }
      public Builder addAllFund(
          java.lang.Iterable<? extends com.howbuy.wireless.entity.protobuf.FundProtos.Fund> values) {
        if (result.fund_.isEmpty()) {
          result.fund_ = new java.util.ArrayList<com.howbuy.wireless.entity.protobuf.FundProtos.Fund>();
        }
        super.addAll(values, result.fund_);
        return this;
      }
      public Builder clearFund() {
        result.fund_ = java.util.Collections.emptyList();
        return this;
      }
      
      // repeated .Issue issue = 9;
      public java.util.List<com.howbuy.wireless.entity.protobuf.IssueProtos.Issue> getIssueList() {
        return java.util.Collections.unmodifiableList(result.issue_);
      }
      public int getIssueCount() {
        return result.getIssueCount();
      }
      public com.howbuy.wireless.entity.protobuf.IssueProtos.Issue getIssue(int index) {
        return result.getIssue(index);
      }
      public Builder setIssue(int index, com.howbuy.wireless.entity.protobuf.IssueProtos.Issue value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.issue_.set(index, value);
        return this;
      }
      public Builder setIssue(int index, com.howbuy.wireless.entity.protobuf.IssueProtos.Issue.Builder builderForValue) {
        result.issue_.set(index, builderForValue.build());
        return this;
      }
      public Builder addIssue(com.howbuy.wireless.entity.protobuf.IssueProtos.Issue value) {
        if (value == null) {
          throw new NullPointerException();
        }
        if (result.issue_.isEmpty()) {
          result.issue_ = new java.util.ArrayList<com.howbuy.wireless.entity.protobuf.IssueProtos.Issue>();
        }
        result.issue_.add(value);
        return this;
      }
      public Builder addIssue(com.howbuy.wireless.entity.protobuf.IssueProtos.Issue.Builder builderForValue) {
        if (result.issue_.isEmpty()) {
          result.issue_ = new java.util.ArrayList<com.howbuy.wireless.entity.protobuf.IssueProtos.Issue>();
        }
        result.issue_.add(builderForValue.build());
        return this;
      }
      public Builder addAllIssue(
          java.lang.Iterable<? extends com.howbuy.wireless.entity.protobuf.IssueProtos.Issue> values) {
        if (result.issue_.isEmpty()) {
          result.issue_ = new java.util.ArrayList<com.howbuy.wireless.entity.protobuf.IssueProtos.Issue>();
        }
        super.addAll(values, result.issue_);
        return this;
      }
      public Builder clearIssue() {
        result.issue_ = java.util.Collections.emptyList();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:ManagerDetailInfoList)
    }
    
    static {
      defaultInstance = new ManagerDetailInfoList(true);
      com.howbuy.wireless.entity.protobuf.ManagerDetailInfoListProto.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:ManagerDetailInfoList)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ManagerDetailInfoList_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ManagerDetailInfoList_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033managerDetailInfoList.proto\032\nfund.prot" +
      "o\032\013issue.proto\032\014common.proto\"\267\001\n\025Manager" +
      "DetailInfoList\022\036\n\006common\030\001 \001(\0132\016.common." +
      "Common\022\014\n\004ryxm\030\002 \001(\t\022\014\n\004ryxb\030\003 \001(\t\022\014\n\004cy" +
      "nx\030\004 \001(\t\022\014\n\004gzgs\030\005 \001(\t\022\014\n\004ryjj\030\006 \001(\t\022\014\n\004" +
      "zpdz\030\007 \001(\t\022\023\n\004fund\030\010 \003(\0132\005.Fund\022\025\n\005issue" +
      "\030\t \003(\0132\006.IssueBA\n#com.howbuy.wireless.en" +
      "tity.protobufB\032ManagerDetailInfoListProt" +
      "o"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_ManagerDetailInfoList_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_ManagerDetailInfoList_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ManagerDetailInfoList_descriptor,
              new java.lang.String[] { "Common", "Ryxm", "Ryxb", "Cynx", "Gzgs", "Ryjj", "Zpdz", "Fund", "Issue", },
              com.howbuy.wireless.entity.protobuf.ManagerDetailInfoListProto.ManagerDetailInfoList.class,
              com.howbuy.wireless.entity.protobuf.ManagerDetailInfoListProto.ManagerDetailInfoList.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.howbuy.wireless.entity.protobuf.FundProtos.getDescriptor(),
          com.howbuy.wireless.entity.protobuf.IssueProtos.getDescriptor(),
          com.howbuy.wireless.entity.protobuf.CommonProtos.getDescriptor(),
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
