// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: phoneOpinionType.proto

package com.howbuy.wireless.entity.protobuf;

public final class PhoneOpinionTypeProtos {
  private PhoneOpinionTypeProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class PhoneOpinionType extends
      com.google.protobuf.GeneratedMessage {
    // Use PhoneOpinionType.newBuilder() to construct.
    private PhoneOpinionType() {
      initFields();
    }
    private PhoneOpinionType(boolean noInit) {}
    
    private static final PhoneOpinionType defaultInstance;
    public static PhoneOpinionType getDefaultInstance() {
      return defaultInstance;
    }
    
    public PhoneOpinionType getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.howbuy.wireless.entity.protobuf.PhoneOpinionTypeProtos.internal_static_common_PhoneOpinionType_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.howbuy.wireless.entity.protobuf.PhoneOpinionTypeProtos.internal_static_common_PhoneOpinionType_fieldAccessorTable;
    }
    
    // optional int32 id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private boolean hasId;
    private int id_ = 0;
    public boolean hasId() { return hasId; }
    public int getId() { return id_; }
    
    // optional string typeName = 2;
    public static final int TYPENAME_FIELD_NUMBER = 2;
    private boolean hasTypeName;
    private java.lang.String typeName_ = "";
    public boolean hasTypeName() { return hasTypeName; }
    public java.lang.String getTypeName() { return typeName_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasId()) {
        output.writeInt32(1, getId());
      }
      if (hasTypeName()) {
        output.writeString(2, getTypeName());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasId()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, getId());
      }
      if (hasTypeName()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getTypeName());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.howbuy.wireless.entity.protobuf.PhoneOpinionTypeProtos.PhoneOpinionType parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.howbuy.wireless.entity.protobuf.PhoneOpinionTypeProtos.PhoneOpinionType parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.howbuy.wireless.entity.protobuf.PhoneOpinionTypeProtos.PhoneOpinionType parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.howbuy.wireless.entity.protobuf.PhoneOpinionTypeProtos.PhoneOpinionType parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.howbuy.wireless.entity.protobuf.PhoneOpinionTypeProtos.PhoneOpinionType parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.howbuy.wireless.entity.protobuf.PhoneOpinionTypeProtos.PhoneOpinionType parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.howbuy.wireless.entity.protobuf.PhoneOpinionTypeProtos.PhoneOpinionType parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.howbuy.wireless.entity.protobuf.PhoneOpinionTypeProtos.PhoneOpinionType parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.howbuy.wireless.entity.protobuf.PhoneOpinionTypeProtos.PhoneOpinionType parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.howbuy.wireless.entity.protobuf.PhoneOpinionTypeProtos.PhoneOpinionType parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.howbuy.wireless.entity.protobuf.PhoneOpinionTypeProtos.PhoneOpinionType prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.howbuy.wireless.entity.protobuf.PhoneOpinionTypeProtos.PhoneOpinionType result;
      
      // Construct using com.howbuy.wireless.entity.protobuf.PhoneOpinionTypeProtos.PhoneOpinionType.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.howbuy.wireless.entity.protobuf.PhoneOpinionTypeProtos.PhoneOpinionType();
        return builder;
      }
      
      protected com.howbuy.wireless.entity.protobuf.PhoneOpinionTypeProtos.PhoneOpinionType internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.howbuy.wireless.entity.protobuf.PhoneOpinionTypeProtos.PhoneOpinionType();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.howbuy.wireless.entity.protobuf.PhoneOpinionTypeProtos.PhoneOpinionType.getDescriptor();
      }
      
      public com.howbuy.wireless.entity.protobuf.PhoneOpinionTypeProtos.PhoneOpinionType getDefaultInstanceForType() {
        return com.howbuy.wireless.entity.protobuf.PhoneOpinionTypeProtos.PhoneOpinionType.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.howbuy.wireless.entity.protobuf.PhoneOpinionTypeProtos.PhoneOpinionType build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.howbuy.wireless.entity.protobuf.PhoneOpinionTypeProtos.PhoneOpinionType buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.howbuy.wireless.entity.protobuf.PhoneOpinionTypeProtos.PhoneOpinionType buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.howbuy.wireless.entity.protobuf.PhoneOpinionTypeProtos.PhoneOpinionType returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.howbuy.wireless.entity.protobuf.PhoneOpinionTypeProtos.PhoneOpinionType) {
          return mergeFrom((com.howbuy.wireless.entity.protobuf.PhoneOpinionTypeProtos.PhoneOpinionType)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.howbuy.wireless.entity.protobuf.PhoneOpinionTypeProtos.PhoneOpinionType other) {
        if (other == com.howbuy.wireless.entity.protobuf.PhoneOpinionTypeProtos.PhoneOpinionType.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasTypeName()) {
          setTypeName(other.getTypeName());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              setId(input.readInt32());
              break;
            }
            case 18: {
              setTypeName(input.readString());
              break;
            }
          }
        }
      }
      
      
      // optional int32 id = 1;
      public boolean hasId() {
        return result.hasId();
      }
      public int getId() {
        return result.getId();
      }
      public Builder setId(int value) {
        result.hasId = true;
        result.id_ = value;
        return this;
      }
      public Builder clearId() {
        result.hasId = false;
        result.id_ = 0;
        return this;
      }
      
      // optional string typeName = 2;
      public boolean hasTypeName() {
        return result.hasTypeName();
      }
      public java.lang.String getTypeName() {
        return result.getTypeName();
      }
      public Builder setTypeName(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasTypeName = true;
        result.typeName_ = value;
        return this;
      }
      public Builder clearTypeName() {
        result.hasTypeName = false;
        result.typeName_ = getDefaultInstance().getTypeName();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:common.PhoneOpinionType)
    }
    
    static {
      defaultInstance = new PhoneOpinionType(true);
      com.howbuy.wireless.entity.protobuf.PhoneOpinionTypeProtos.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:common.PhoneOpinionType)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_common_PhoneOpinionType_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_common_PhoneOpinionType_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026phoneOpinionType.proto\022\006common\"0\n\020Phon" +
      "eOpinionType\022\n\n\002id\030\001 \001(\005\022\020\n\010typeName\030\002 \001" +
      "(\tB=\n#com.howbuy.wireless.entity.protobu" +
      "fB\026PhoneOpinionTypeProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_common_PhoneOpinionType_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_common_PhoneOpinionType_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_common_PhoneOpinionType_descriptor,
              new java.lang.String[] { "Id", "TypeName", },
              com.howbuy.wireless.entity.protobuf.PhoneOpinionTypeProtos.PhoneOpinionType.class,
              com.howbuy.wireless.entity.protobuf.PhoneOpinionTypeProtos.PhoneOpinionType.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
