// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: simuBasicInfo.proto

package com.howbuy.wireless.entity.protobuf;

public final class SimuBasicInfoProto {
  private SimuBasicInfoProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class SimuBasicInfo extends
      com.google.protobuf.GeneratedMessage {
    // Use SimuBasicInfo.newBuilder() to construct.
    private SimuBasicInfo() {
      initFields();
    }
    private SimuBasicInfo(boolean noInit) {}
    
    private static final SimuBasicInfo defaultInstance;
    public static SimuBasicInfo getDefaultInstance() {
      return defaultInstance;
    }
    
    public SimuBasicInfo getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.howbuy.wireless.entity.protobuf.SimuBasicInfoProto.internal_static_SimuBasicInfo_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.howbuy.wireless.entity.protobuf.SimuBasicInfoProto.internal_static_SimuBasicInfo_fieldAccessorTable;
    }
    
    // optional .common.Common common = 1;
    public static final int COMMON_FIELD_NUMBER = 1;
    private boolean hasCommon;
    private com.howbuy.wireless.entity.protobuf.CommonProtos.Common common_;
    public boolean hasCommon() { return hasCommon; }
    public com.howbuy.wireless.entity.protobuf.CommonProtos.Common getCommon() { return common_; }
    
    // optional int32 hmpj = 2;
    public static final int HMPJ_FIELD_NUMBER = 2;
    private boolean hasHmpj;
    private int hmpj_ = 0;
    public boolean hasHmpj() { return hasHmpj; }
    public int getHmpj() { return hmpj_; }
    
    // optional string gsszd = 3;
    public static final int GSSZD_FIELD_NUMBER = 3;
    private boolean hasGsszd;
    private java.lang.String gsszd_ = "";
    public boolean hasGsszd() { return hasGsszd; }
    public java.lang.String getGsszd() { return gsszd_; }
    
    private void initFields() {
      common_ = com.howbuy.wireless.entity.protobuf.CommonProtos.Common.getDefaultInstance();
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasCommon()) {
        output.writeMessage(1, getCommon());
      }
      if (hasHmpj()) {
        output.writeInt32(2, getHmpj());
      }
      if (hasGsszd()) {
        output.writeString(3, getGsszd());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasCommon()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getCommon());
      }
      if (hasHmpj()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, getHmpj());
      }
      if (hasGsszd()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(3, getGsszd());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.howbuy.wireless.entity.protobuf.SimuBasicInfoProto.SimuBasicInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.howbuy.wireless.entity.protobuf.SimuBasicInfoProto.SimuBasicInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.howbuy.wireless.entity.protobuf.SimuBasicInfoProto.SimuBasicInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.howbuy.wireless.entity.protobuf.SimuBasicInfoProto.SimuBasicInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.howbuy.wireless.entity.protobuf.SimuBasicInfoProto.SimuBasicInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.howbuy.wireless.entity.protobuf.SimuBasicInfoProto.SimuBasicInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.howbuy.wireless.entity.protobuf.SimuBasicInfoProto.SimuBasicInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.howbuy.wireless.entity.protobuf.SimuBasicInfoProto.SimuBasicInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.howbuy.wireless.entity.protobuf.SimuBasicInfoProto.SimuBasicInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.howbuy.wireless.entity.protobuf.SimuBasicInfoProto.SimuBasicInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.howbuy.wireless.entity.protobuf.SimuBasicInfoProto.SimuBasicInfo prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.howbuy.wireless.entity.protobuf.SimuBasicInfoProto.SimuBasicInfo result;
      
      // Construct using com.howbuy.wireless.entity.protobuf.SimuBasicInfoProto.SimuBasicInfo.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.howbuy.wireless.entity.protobuf.SimuBasicInfoProto.SimuBasicInfo();
        return builder;
      }
      
      protected com.howbuy.wireless.entity.protobuf.SimuBasicInfoProto.SimuBasicInfo internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.howbuy.wireless.entity.protobuf.SimuBasicInfoProto.SimuBasicInfo();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.howbuy.wireless.entity.protobuf.SimuBasicInfoProto.SimuBasicInfo.getDescriptor();
      }
      
      public com.howbuy.wireless.entity.protobuf.SimuBasicInfoProto.SimuBasicInfo getDefaultInstanceForType() {
        return com.howbuy.wireless.entity.protobuf.SimuBasicInfoProto.SimuBasicInfo.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.howbuy.wireless.entity.protobuf.SimuBasicInfoProto.SimuBasicInfo build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.howbuy.wireless.entity.protobuf.SimuBasicInfoProto.SimuBasicInfo buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.howbuy.wireless.entity.protobuf.SimuBasicInfoProto.SimuBasicInfo buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.howbuy.wireless.entity.protobuf.SimuBasicInfoProto.SimuBasicInfo returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.howbuy.wireless.entity.protobuf.SimuBasicInfoProto.SimuBasicInfo) {
          return mergeFrom((com.howbuy.wireless.entity.protobuf.SimuBasicInfoProto.SimuBasicInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.howbuy.wireless.entity.protobuf.SimuBasicInfoProto.SimuBasicInfo other) {
        if (other == com.howbuy.wireless.entity.protobuf.SimuBasicInfoProto.SimuBasicInfo.getDefaultInstance()) return this;
        if (other.hasCommon()) {
          mergeCommon(other.getCommon());
        }
        if (other.hasHmpj()) {
          setHmpj(other.getHmpj());
        }
        if (other.hasGsszd()) {
          setGsszd(other.getGsszd());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              com.howbuy.wireless.entity.protobuf.CommonProtos.Common.Builder subBuilder = com.howbuy.wireless.entity.protobuf.CommonProtos.Common.newBuilder();
              if (hasCommon()) {
                subBuilder.mergeFrom(getCommon());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setCommon(subBuilder.buildPartial());
              break;
            }
            case 16: {
              setHmpj(input.readInt32());
              break;
            }
            case 26: {
              setGsszd(input.readString());
              break;
            }
          }
        }
      }
      
      
      // optional .common.Common common = 1;
      public boolean hasCommon() {
        return result.hasCommon();
      }
      public com.howbuy.wireless.entity.protobuf.CommonProtos.Common getCommon() {
        return result.getCommon();
      }
      public Builder setCommon(com.howbuy.wireless.entity.protobuf.CommonProtos.Common value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasCommon = true;
        result.common_ = value;
        return this;
      }
      public Builder setCommon(com.howbuy.wireless.entity.protobuf.CommonProtos.Common.Builder builderForValue) {
        result.hasCommon = true;
        result.common_ = builderForValue.build();
        return this;
      }
      public Builder mergeCommon(com.howbuy.wireless.entity.protobuf.CommonProtos.Common value) {
        if (result.hasCommon() &&
            result.common_ != com.howbuy.wireless.entity.protobuf.CommonProtos.Common.getDefaultInstance()) {
          result.common_ =
            com.howbuy.wireless.entity.protobuf.CommonProtos.Common.newBuilder(result.common_).mergeFrom(value).buildPartial();
        } else {
          result.common_ = value;
        }
        result.hasCommon = true;
        return this;
      }
      public Builder clearCommon() {
        result.hasCommon = false;
        result.common_ = com.howbuy.wireless.entity.protobuf.CommonProtos.Common.getDefaultInstance();
        return this;
      }
      
      // optional int32 hmpj = 2;
      public boolean hasHmpj() {
        return result.hasHmpj();
      }
      public int getHmpj() {
        return result.getHmpj();
      }
      public Builder setHmpj(int value) {
        result.hasHmpj = true;
        result.hmpj_ = value;
        return this;
      }
      public Builder clearHmpj() {
        result.hasHmpj = false;
        result.hmpj_ = 0;
        return this;
      }
      
      // optional string gsszd = 3;
      public boolean hasGsszd() {
        return result.hasGsszd();
      }
      public java.lang.String getGsszd() {
        return result.getGsszd();
      }
      public Builder setGsszd(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasGsszd = true;
        result.gsszd_ = value;
        return this;
      }
      public Builder clearGsszd() {
        result.hasGsszd = false;
        result.gsszd_ = getDefaultInstance().getGsszd();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:SimuBasicInfo)
    }
    
    static {
      defaultInstance = new SimuBasicInfo(true);
      com.howbuy.wireless.entity.protobuf.SimuBasicInfoProto.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:SimuBasicInfo)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_SimuBasicInfo_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_SimuBasicInfo_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023simuBasicInfo.proto\032\014common.proto\"L\n\rS" +
      "imuBasicInfo\022\036\n\006common\030\001 \001(\0132\016.common.Co" +
      "mmon\022\014\n\004hmpj\030\002 \001(\005\022\r\n\005gsszd\030\003 \001(\tB9\n#com" +
      ".howbuy.wireless.entity.protobufB\022SimuBa" +
      "sicInfoProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_SimuBasicInfo_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_SimuBasicInfo_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_SimuBasicInfo_descriptor,
              new java.lang.String[] { "Common", "Hmpj", "Gsszd", },
              com.howbuy.wireless.entity.protobuf.SimuBasicInfoProto.SimuBasicInfo.class,
              com.howbuy.wireless.entity.protobuf.SimuBasicInfoProto.SimuBasicInfo.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.howbuy.wireless.entity.protobuf.CommonProtos.getDescriptor(),
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
