// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: trustInfoOfPage.proto

package com.howbuy.wireless.entity.protobuf.trustdaquan;

public final class TrustInfoOfPageProtos {
  private TrustInfoOfPageProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class TrustInfoOfPage extends
      com.google.protobuf.GeneratedMessage {
    // Use TrustInfoOfPage.newBuilder() to construct.
    private TrustInfoOfPage() {
      initFields();
    }
    private TrustInfoOfPage(boolean noInit) {}
    
    private static final TrustInfoOfPage defaultInstance;
    public static TrustInfoOfPage getDefaultInstance() {
      return defaultInstance;
    }
    
    public TrustInfoOfPage getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.howbuy.wireless.entity.protobuf.trustdaquan.TrustInfoOfPageProtos.internal_static_TrustInfoOfPage_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.howbuy.wireless.entity.protobuf.trustdaquan.TrustInfoOfPageProtos.internal_static_TrustInfoOfPage_fieldAccessorTable;
    }
    
    // optional string pid = 1;
    public static final int PID_FIELD_NUMBER = 1;
    private boolean hasPid;
    private java.lang.String pid_ = "";
    public boolean hasPid() { return hasPid; }
    public java.lang.String getPid() { return pid_; }
    
    // optional string cpmc = 2;
    public static final int CPMC_FIELD_NUMBER = 2;
    private boolean hasCpmc;
    private java.lang.String cpmc_ = "";
    public boolean hasCpmc() { return hasCpmc; }
    public java.lang.String getCpmc() { return cpmc_; }
    
    // optional string xszt = 3;
    public static final int XSZT_FIELD_NUMBER = 3;
    private boolean hasXszt;
    private java.lang.String xszt_ = "";
    public boolean hasXszt() { return hasXszt; }
    public java.lang.String getXszt() { return xszt_; }
    
    // optional string cpnx = 4;
    public static final int CPNX_FIELD_NUMBER = 4;
    private boolean hasCpnx;
    private java.lang.String cpnx_ = "";
    public boolean hasCpnx() { return hasCpnx; }
    public java.lang.String getCpnx() { return cpnx_; }
    
    // optional string yqsy = 5;
    public static final int YQSY_FIELD_NUMBER = 5;
    private boolean hasYqsy;
    private java.lang.String yqsy_ = "";
    public boolean hasYqsy() { return hasYqsy; }
    public java.lang.String getYqsy() { return yqsy_; }
    
    // optional string hmdp = 6;
    public static final int HMDP_FIELD_NUMBER = 6;
    private boolean hasHmdp;
    private java.lang.String hmdp_ = "";
    public boolean hasHmdp() { return hasHmdp; }
    public java.lang.String getHmdp() { return hmdp_; }
    
    // optional string cpmd = 7;
    public static final int CPMD_FIELD_NUMBER = 7;
    private boolean hasCpmd;
    private java.lang.String cpmd_ = "";
    public boolean hasCpmd() { return hasCpmd; }
    public java.lang.String getCpmd() { return cpmd_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasPid()) {
        output.writeString(1, getPid());
      }
      if (hasCpmc()) {
        output.writeString(2, getCpmc());
      }
      if (hasXszt()) {
        output.writeString(3, getXszt());
      }
      if (hasCpnx()) {
        output.writeString(4, getCpnx());
      }
      if (hasYqsy()) {
        output.writeString(5, getYqsy());
      }
      if (hasHmdp()) {
        output.writeString(6, getHmdp());
      }
      if (hasCpmd()) {
        output.writeString(7, getCpmd());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasPid()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getPid());
      }
      if (hasCpmc()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getCpmc());
      }
      if (hasXszt()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(3, getXszt());
      }
      if (hasCpnx()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(4, getCpnx());
      }
      if (hasYqsy()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(5, getYqsy());
      }
      if (hasHmdp()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(6, getHmdp());
      }
      if (hasCpmd()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(7, getCpmd());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.howbuy.wireless.entity.protobuf.trustdaquan.TrustInfoOfPageProtos.TrustInfoOfPage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.howbuy.wireless.entity.protobuf.trustdaquan.TrustInfoOfPageProtos.TrustInfoOfPage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.howbuy.wireless.entity.protobuf.trustdaquan.TrustInfoOfPageProtos.TrustInfoOfPage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.howbuy.wireless.entity.protobuf.trustdaquan.TrustInfoOfPageProtos.TrustInfoOfPage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.howbuy.wireless.entity.protobuf.trustdaquan.TrustInfoOfPageProtos.TrustInfoOfPage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.howbuy.wireless.entity.protobuf.trustdaquan.TrustInfoOfPageProtos.TrustInfoOfPage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.howbuy.wireless.entity.protobuf.trustdaquan.TrustInfoOfPageProtos.TrustInfoOfPage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.howbuy.wireless.entity.protobuf.trustdaquan.TrustInfoOfPageProtos.TrustInfoOfPage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.howbuy.wireless.entity.protobuf.trustdaquan.TrustInfoOfPageProtos.TrustInfoOfPage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.howbuy.wireless.entity.protobuf.trustdaquan.TrustInfoOfPageProtos.TrustInfoOfPage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.howbuy.wireless.entity.protobuf.trustdaquan.TrustInfoOfPageProtos.TrustInfoOfPage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.howbuy.wireless.entity.protobuf.trustdaquan.TrustInfoOfPageProtos.TrustInfoOfPage result;
      
      // Construct using com.howbuy.wireless.entity.protobuf.trustdaquan.TrustInfoOfPageProtos.TrustInfoOfPage.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.howbuy.wireless.entity.protobuf.trustdaquan.TrustInfoOfPageProtos.TrustInfoOfPage();
        return builder;
      }
      
      protected com.howbuy.wireless.entity.protobuf.trustdaquan.TrustInfoOfPageProtos.TrustInfoOfPage internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.howbuy.wireless.entity.protobuf.trustdaquan.TrustInfoOfPageProtos.TrustInfoOfPage();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.howbuy.wireless.entity.protobuf.trustdaquan.TrustInfoOfPageProtos.TrustInfoOfPage.getDescriptor();
      }
      
      public com.howbuy.wireless.entity.protobuf.trustdaquan.TrustInfoOfPageProtos.TrustInfoOfPage getDefaultInstanceForType() {
        return com.howbuy.wireless.entity.protobuf.trustdaquan.TrustInfoOfPageProtos.TrustInfoOfPage.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.howbuy.wireless.entity.protobuf.trustdaquan.TrustInfoOfPageProtos.TrustInfoOfPage build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.howbuy.wireless.entity.protobuf.trustdaquan.TrustInfoOfPageProtos.TrustInfoOfPage buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.howbuy.wireless.entity.protobuf.trustdaquan.TrustInfoOfPageProtos.TrustInfoOfPage buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.howbuy.wireless.entity.protobuf.trustdaquan.TrustInfoOfPageProtos.TrustInfoOfPage returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.howbuy.wireless.entity.protobuf.trustdaquan.TrustInfoOfPageProtos.TrustInfoOfPage) {
          return mergeFrom((com.howbuy.wireless.entity.protobuf.trustdaquan.TrustInfoOfPageProtos.TrustInfoOfPage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.howbuy.wireless.entity.protobuf.trustdaquan.TrustInfoOfPageProtos.TrustInfoOfPage other) {
        if (other == com.howbuy.wireless.entity.protobuf.trustdaquan.TrustInfoOfPageProtos.TrustInfoOfPage.getDefaultInstance()) return this;
        if (other.hasPid()) {
          setPid(other.getPid());
        }
        if (other.hasCpmc()) {
          setCpmc(other.getCpmc());
        }
        if (other.hasXszt()) {
          setXszt(other.getXszt());
        }
        if (other.hasCpnx()) {
          setCpnx(other.getCpnx());
        }
        if (other.hasYqsy()) {
          setYqsy(other.getYqsy());
        }
        if (other.hasHmdp()) {
          setHmdp(other.getHmdp());
        }
        if (other.hasCpmd()) {
          setCpmd(other.getCpmd());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              setPid(input.readString());
              break;
            }
            case 18: {
              setCpmc(input.readString());
              break;
            }
            case 26: {
              setXszt(input.readString());
              break;
            }
            case 34: {
              setCpnx(input.readString());
              break;
            }
            case 42: {
              setYqsy(input.readString());
              break;
            }
            case 50: {
              setHmdp(input.readString());
              break;
            }
            case 58: {
              setCpmd(input.readString());
              break;
            }
          }
        }
      }
      
      
      // optional string pid = 1;
      public boolean hasPid() {
        return result.hasPid();
      }
      public java.lang.String getPid() {
        return result.getPid();
      }
      public Builder setPid(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasPid = true;
        result.pid_ = value;
        return this;
      }
      public Builder clearPid() {
        result.hasPid = false;
        result.pid_ = getDefaultInstance().getPid();
        return this;
      }
      
      // optional string cpmc = 2;
      public boolean hasCpmc() {
        return result.hasCpmc();
      }
      public java.lang.String getCpmc() {
        return result.getCpmc();
      }
      public Builder setCpmc(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasCpmc = true;
        result.cpmc_ = value;
        return this;
      }
      public Builder clearCpmc() {
        result.hasCpmc = false;
        result.cpmc_ = getDefaultInstance().getCpmc();
        return this;
      }
      
      // optional string xszt = 3;
      public boolean hasXszt() {
        return result.hasXszt();
      }
      public java.lang.String getXszt() {
        return result.getXszt();
      }
      public Builder setXszt(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasXszt = true;
        result.xszt_ = value;
        return this;
      }
      public Builder clearXszt() {
        result.hasXszt = false;
        result.xszt_ = getDefaultInstance().getXszt();
        return this;
      }
      
      // optional string cpnx = 4;
      public boolean hasCpnx() {
        return result.hasCpnx();
      }
      public java.lang.String getCpnx() {
        return result.getCpnx();
      }
      public Builder setCpnx(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasCpnx = true;
        result.cpnx_ = value;
        return this;
      }
      public Builder clearCpnx() {
        result.hasCpnx = false;
        result.cpnx_ = getDefaultInstance().getCpnx();
        return this;
      }
      
      // optional string yqsy = 5;
      public boolean hasYqsy() {
        return result.hasYqsy();
      }
      public java.lang.String getYqsy() {
        return result.getYqsy();
      }
      public Builder setYqsy(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasYqsy = true;
        result.yqsy_ = value;
        return this;
      }
      public Builder clearYqsy() {
        result.hasYqsy = false;
        result.yqsy_ = getDefaultInstance().getYqsy();
        return this;
      }
      
      // optional string hmdp = 6;
      public boolean hasHmdp() {
        return result.hasHmdp();
      }
      public java.lang.String getHmdp() {
        return result.getHmdp();
      }
      public Builder setHmdp(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasHmdp = true;
        result.hmdp_ = value;
        return this;
      }
      public Builder clearHmdp() {
        result.hasHmdp = false;
        result.hmdp_ = getDefaultInstance().getHmdp();
        return this;
      }
      
      // optional string cpmd = 7;
      public boolean hasCpmd() {
        return result.hasCpmd();
      }
      public java.lang.String getCpmd() {
        return result.getCpmd();
      }
      public Builder setCpmd(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasCpmd = true;
        result.cpmd_ = value;
        return this;
      }
      public Builder clearCpmd() {
        result.hasCpmd = false;
        result.cpmd_ = getDefaultInstance().getCpmd();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:TrustInfoOfPage)
    }
    
    static {
      defaultInstance = new TrustInfoOfPage(true);
      com.howbuy.wireless.entity.protobuf.trustdaquan.TrustInfoOfPageProtos.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:TrustInfoOfPage)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_TrustInfoOfPage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_TrustInfoOfPage_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025trustInfoOfPage.proto\"r\n\017TrustInfoOfPa" +
      "ge\022\013\n\003pid\030\001 \001(\t\022\014\n\004cpmc\030\002 \001(\t\022\014\n\004xszt\030\003 " +
      "\001(\t\022\014\n\004cpnx\030\004 \001(\t\022\014\n\004yqsy\030\005 \001(\t\022\014\n\004hmdp\030" +
      "\006 \001(\t\022\014\n\004cpmd\030\007 \001(\tBH\n/com.howbuy.wirele" +
      "ss.entity.protobuf.trustdaquanB\025TrustInf" +
      "oOfPageProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_TrustInfoOfPage_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_TrustInfoOfPage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_TrustInfoOfPage_descriptor,
              new java.lang.String[] { "Pid", "Cpmc", "Xszt", "Cpnx", "Yqsy", "Hmdp", "Cpmd", },
              com.howbuy.wireless.entity.protobuf.trustdaquan.TrustInfoOfPageProtos.TrustInfoOfPage.class,
              com.howbuy.wireless.entity.protobuf.trustdaquan.TrustInfoOfPageProtos.TrustInfoOfPage.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
